// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:fr-syntax-sa",
	"name": "French Syntax Share-Alike Composite Textpack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-fr-syntax-sa",
	"targets": {
		"languages": [
			"fr"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [],
	"components": [
		{
			"packageName": "@ismail-elkorchi/textpack-fr-syntax-ud-gsd-sa",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Share-alike isolated UD French GSD annotation-derived syntax and tagging resources.",
			"licensePolicy": "allow-share-alike",
			"capabilityPolicy": "available-optional",
			"artifactPolicy": "none"
		}
	],
	"capabilitySlots": [
		{
			"slot": "syntax",
			"status": "task-supported",
			"notes": [
				"The required component graph provides UD French GSD dependency-label, dependency-integrity, sentence-profile, and token/part-of-speech tagging signals under the share-alike policy surface."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"notes": [
				"Generated component reports and evaluation records are available for the required share-alike syntax component."
			]
		}
	],
	"license": "CC-BY-SA-4.0",
	"citations": [
		"Universal Dependencies French GSD r2.18 annotations."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
