// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:fr-segmentation",
	"name": "French Segmentation Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-fr-segmentation",
	"targets": {
		"languages": [
			"fr"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "fr-segmentation-boundary-properties",
			"kind": "segmentation-profile",
			"path": "resources/fr.segmentation-boundary-properties.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			]
		},
		{
			"id": "fr-grapheme-segmentation-profile",
			"kind": "segmentation-profile",
			"path": "resources/fr.segmentation.grapheme.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"metadata": {
				"canonicalSchema": "textpack-segmentation-resource.schema.json"
			}
		},
		{
			"id": "fr-word-segmentation-profile",
			"kind": "segmentation-profile",
			"path": "resources/fr.segmentation.word.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"metadata": {
				"canonicalSchema": "textpack-segmentation-resource.schema.json"
			}
		},
		{
			"id": "fr-sentence-segmentation-profile",
			"kind": "segmentation-profile",
			"path": "resources/fr.segmentation.sentence.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"metadata": {
				"canonicalSchema": "textpack-segmentation-resource.schema.json"
			}
		},
		{
			"id": "fr-segmentation-quality",
			"kind": "quality-profile",
			"path": "resources/fr.segmentation.quality.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			]
		},
		{
			"id": "fr-segmentation-quality-profile",
			"kind": "quality-profile",
			"path": "resources/fr.segmentation.quality-profile.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"metadata": {
				"canonicalSchema": "textpack-quality-profile-resource.schema.json"
			}
		}
	],
	"capabilitySlots": [
		{
			"slot": "segmentation",
			"status": "task-supported",
			"resourceIds": [
				"fr-segmentation-boundary-properties",
				"fr-grapheme-segmentation-profile",
				"fr-word-segmentation-profile",
				"fr-sentence-segmentation-profile"
			],
			"capabilities": {
				"segmentation": "profile"
			},
			"notes": [
				"Unicode UAX #29 grapheme, word, and sentence boundary profiles are available for modern typed French text."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"fr-segmentation-quality",
				"fr-segmentation-quality-profile"
			],
			"notes": [
				"Generated quality profile records boundary-property coverage, source counts, accepted records, and scope limitations."
			]
		}
	],
	"license": "Unicode-3.0",
	"citations": [
		"Unicode Character Database 17.0.0.",
		"Unicode CLDR core data, cldr-core npm package 48.2.0."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
