// Generated by tools/textpack-forge. Do not edit.

export type {
	TextPackLanguageSupportEntry,
	TextPackLanguageSupportLevel,
} from "./language-support.js";
export {
	getLanguageSupport,
	hasLanguageSupport,
	languageSupport,
	listLanguageSupport,
	listLanguagesBySupportLevel,
} from "./language-support.js";
export { manifest } from "./manifest.js";
export { pack } from "./pack.js";
export { resources } from "./resources.js";

import { pack } from "./pack.js";

export default pack;
