// Generated by tools/textpack-forge. Do not edit.

export type {
	TextPackLanguageSupportEntry,
	TextPackLanguageSupportLevel,
} from "./language-support.js";
export {
	getLanguageSupport,
	hasLanguageSupport,
	languageSupport,
	listLanguageSupport,
	listLanguagesBySupportLevel,
} from "./language-support.js";
export { manifest } from "./manifest.js";
export { resources } from "./resources.js";

import {
	loadPack,
	type ResolveTextPackComponentsOptions,
	resolvePackComponents,
	type TextPackComponent,
} from "@ismail-elkorchi/textpack";
import { manifest } from "./manifest.js";
import { resources } from "./resources.js";

export interface LoadFoundationOptions
	extends Omit<ResolveTextPackComponentsOptions, "resolveComponent"> {
	readonly resolveComponent?: ResolveTextPackComponentsOptions["resolveComponent"];
}

async function resolveGeneratedComponent(
	component: TextPackComponent,
	options: LoadFoundationOptions,
): Promise<unknown> {
	void options;
	switch (component.packageName) {
		case "@ismail-elkorchi/textpack-language-registry":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-unicode-17":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-cldr-core":
			return import(component.packageName);
		default:
			throw new TypeError(
				`No generated resolver entry for ${component.packageName}.`,
			);
	}
}

export async function loadFoundation(options: LoadFoundationOptions = {}) {
	return resolvePackComponents(await loadPack({ manifest, resources }), {
		...options,
		licensePolicy: options.licensePolicy ?? "default",
		artifactPolicy: options.artifactPolicy ?? "none",
		conflictPolicy: options.conflictPolicy ?? "first",
		resolveComponent:
			options.resolveComponent ??
			((component) => resolveGeneratedComponent(component, options)),
	});
}

export default { manifest, resources, loadFoundation };
