// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:foundation",
	"name": "Foundation Composite Textpack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-foundation",
	"targets": {
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [],
	"components": [
		{
			"packageName": "@ismail-elkorchi/textpack-language-registry",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Default BCP 47 language/script/region registry foundation resources.",
			"licensePolicy": "default",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-unicode-17",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Default Unicode 17 script, block, and property alias foundation resources.",
			"licensePolicy": "default",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-cldr-core",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Default CLDR likely-subtag, alias, and script-variant foundation resources.",
			"licensePolicy": "default",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		}
	],
	"capabilitySlots": [
		{
			"slot": "language-registry",
			"status": "task-supported",
			"notes": [
				"BCP 47 language, script, region, variant, grandfathered, and redundant tag registry resources are available through the generated foundation graph."
			]
		},
		{
			"slot": "unicode-profile",
			"status": "task-supported",
			"notes": [
				"Unicode 17 script, block, and property alias resources are available through the generated foundation graph."
			]
		},
		{
			"slot": "locale-profile",
			"status": "task-supported",
			"notes": [
				"CLDR likely-subtag, alias, and script variant resources are available through the generated foundation graph."
			]
		}
	],
	"license": "MIT AND LicenseRef-IANA-Language-Subtag-Registry AND Unicode-3.0",
	"citations": [
		"repo:tools/textpack-forge/composites/textpack-foundation.composite.json"
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
