// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:en-segmentation",
	"name": "English Segmentation Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-en-segmentation",
	"targets": {
		"languages": [
			"en"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "en-segmentation-boundary-properties",
			"kind": "segmentation-profile",
			"path": "resources/en.segmentation-boundary-properties.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			]
		},
		{
			"id": "en-grapheme-segmentation-profile",
			"kind": "segmentation-profile",
			"path": "resources/en.segmentation.grapheme.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"metadata": {
				"canonicalSchema": "textpack-segmentation-resource.schema.json"
			}
		},
		{
			"id": "en-word-segmentation-profile",
			"kind": "segmentation-profile",
			"path": "resources/en.segmentation.word.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"metadata": {
				"canonicalSchema": "textpack-segmentation-resource.schema.json"
			}
		},
		{
			"id": "en-sentence-segmentation-profile",
			"kind": "segmentation-profile",
			"path": "resources/en.segmentation.sentence.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"metadata": {
				"canonicalSchema": "textpack-segmentation-resource.schema.json"
			}
		},
		{
			"id": "en-segmentation-quality",
			"kind": "quality-profile",
			"path": "resources/en.segmentation.quality.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			]
		},
		{
			"id": "en-segmentation-quality-profile",
			"kind": "quality-profile",
			"path": "resources/en.segmentation.quality-profile.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"metadata": {
				"canonicalSchema": "textpack-quality-profile-resource.schema.json"
			}
		}
	],
	"capabilitySlots": [
		{
			"slot": "segmentation",
			"status": "task-supported",
			"resourceIds": [
				"en-segmentation-boundary-properties",
				"en-grapheme-segmentation-profile",
				"en-word-segmentation-profile",
				"en-sentence-segmentation-profile"
			],
			"capabilities": {
				"segmentation": "profile"
			},
			"notes": [
				"Unicode UAX #29 grapheme, word, and sentence boundary profiles are available for modern typed English text."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"en-segmentation-quality",
				"en-segmentation-quality-profile"
			],
			"notes": [
				"Generated quality profile records boundary-property coverage, source counts, accepted records, and scope limitations."
			]
		}
	],
	"license": "Unicode-3.0",
	"citations": [
		"Unicode Character Database 17.0.0.",
		"Unicode CLDR core data, cldr-core npm package 48.2.0."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
