// Generated by tools/textpack-forge. Do not edit.

import { createPack } from "@ismail-elkorchi/textpack";

import { manifest } from "./manifest.js";
import { resources } from "./resources.js";

export const pack = createPack(manifest, resources);
