// Generated by tools/textpack-forge. Do not edit.

export { manifest } from "./manifest.js";
export { resources } from "./resources.js";

import {
	loadPack,
	type ResolveTextPackComponentsOptions,
	resolvePackComponents,
	type TextPackComponent,
} from "@ismail-elkorchi/textpack";
import { manifest } from "./manifest.js";
import { resources } from "./resources.js";

export interface LoadEnglishOptions
	extends Omit<ResolveTextPackComponentsOptions, "resolveComponent"> {
	readonly resolveComponent?: ResolveTextPackComponentsOptions["resolveComponent"];
}

async function resolveGeneratedComponent(
	component: TextPackComponent,
	options: LoadEnglishOptions,
): Promise<unknown> {
	void options;
	switch (component.packageName) {
		case "@ismail-elkorchi/textpack-foundation": {
			const module = await import(component.packageName);
			const loader = module.loadFoundation;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFoundation.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-en-core":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-en-normalization":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-en-segmentation":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-en-lexicon": {
			const module = await import(component.packageName);
			const loader = module.loadEnglishLexicon;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadEnglishLexicon.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-en-morphology": {
			const module = await import(component.packageName);
			const loader = module.loadEnglishMorphology;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadEnglishMorphology.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-en-syntax": {
			const module = await import(component.packageName);
			const loader = module.loadEnglishSyntax;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadEnglishSyntax.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-en-kb": {
			const module = await import(component.packageName);
			const loader = module.loadEnglishKnowledgeBase;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadEnglishKnowledgeBase.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-en-search": {
			const module = await import(component.packageName);
			const loader = module.loadEnglishSearch;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadEnglishSearch.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-en-corpus":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-en-parallel":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-en-quality": {
			const module = await import(component.packageName);
			const loader = module.loadEnglishQuality;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadEnglishQuality.`,
				);
			}
			return loader(options);
		}
		default:
			throw new TypeError(
				`No generated resolver entry for ${component.packageName}.`,
			);
	}
}

export async function loadEnglish(options: LoadEnglishOptions = {}) {
	return resolvePackComponents(await loadPack({ manifest, resources }), {
		...options,
		licensePolicy: options.licensePolicy ?? "allow-attribution",
		artifactPolicy: options.artifactPolicy ?? "none",
		conflictPolicy: options.conflictPolicy ?? "first",
		resolveComponent:
			options.resolveComponent ??
			((component) => resolveGeneratedComponent(component, options)),
	});
}

export default { manifest, resources, loadEnglish };
