// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:en",
	"name": "English Developer Textpack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-en",
	"targets": {
		"languages": [
			"en"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [],
	"components": [
		{
			"packageName": "@ismail-elkorchi/textpack-foundation",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Default Unicode, CLDR, and BCP 47 foundation resources.",
			"licensePolicy": "default",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-en-core",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "English core language profile resources.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-en-normalization",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "English normalization policy and quality resources.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-en-segmentation",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "English segmentation profiles.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-en-lexicon",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "English spelling, inflection-inventory, and lexical-semantic lexicon resources.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-en-morphology",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "English lookup morphology resources.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-en-syntax",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "English UD-derived syntax and tagging resources.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-en-kb",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "English WordNet lexical-semantic resources and local Wikidata core entity extract.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-en-search",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "English search analyzer profile resources.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-en-corpus",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "English local Tatoeba corpus rows and quality evidence.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-en-parallel",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "English-linked local Tatoeba parallel alignment rows and quality evidence.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-en-quality",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "English generated quality evidence over the required default component graph.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		}
	],
	"capabilitySlots": [
		{
			"slot": "foundation",
			"status": "task-supported",
			"notes": [
				"The required component graph provides Unicode, CLDR, and BCP 47 foundation resources."
			]
		},
		{
			"slot": "core",
			"status": "task-supported",
			"notes": [
				"The required component graph provides the English core language profile."
			]
		},
		{
			"slot": "normalization",
			"status": "task-supported",
			"notes": [
				"The required component graph provides English normalization resources."
			]
		},
		{
			"slot": "segmentation",
			"status": "task-supported",
			"notes": [
				"The required component graph provides English segmentation resources."
			]
		},
		{
			"slot": "lexicon",
			"status": "task-supported",
			"notes": [
				"The required component graph provides English spelling, inflection-inventory, and lexical-semantic lexicon resources."
			]
		},
		{
			"slot": "morphology",
			"status": "task-supported",
			"notes": [
				"The required component graph provides English SCOWLv2 lookup morphology resources; isolated UniMorph paradigm tables are not included."
			]
		},
		{
			"slot": "syntax",
			"status": "task-supported",
			"notes": [
				"The required component graph provides English UD-derived syntax and tagging resources."
			]
		},
		{
			"slot": "kb",
			"status": "task-supported",
			"notes": [
				"The required component graph provides Open English WordNet resources and a local Wikidata English core entity extract."
			]
		},
		{
			"slot": "search",
			"status": "task-supported",
			"notes": [
				"The required component graph provides English search analyzer resources."
			]
		},
		{
			"slot": "corpus",
			"status": "task-supported",
			"notes": [
				"The required component graph provides local Tatoeba English sentence rows and canonical corpus metadata."
			]
		},
		{
			"slot": "parallel",
			"status": "task-supported",
			"notes": [
				"The required component graph provides local Tatoeba English-linked sentence-id alignment rows for selected target languages."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"notes": [
				"The required component graph provides generated English quality evidence and coverage reports over the required local component graph."
			]
		}
	],
	"license": "MIT AND LicenseRef-IANA-Language-Subtag-Registry AND Unicode-3.0 AND LicenseRef-ESDB-MIT-Like AND CC-BY-4.0 AND LicenseRef-Princeton-WordNet AND CC0-1.0 AND CC-BY-2.0-FR",
	"citations": [
		"IANA Language Subtag Registry, File-Date 2026-05-05.",
		"Unicode Character Database 17.0.0.",
		"Unicode CLDR core data, cldr-core npm package 48.2.0.",
		"English Speller Database generated wordlist outputs, rel-2026.02.25.",
		"SCOWLv2 rich text export, rel-2026.02.25.",
		"Universal Dependencies English GUMReddit r2.18 annotations.",
		"Open English WordNet 2025.",
		"Wikidata main structured data dump, 2026-06-08.",
		"Tatoeba weekly exports, 2026-06-06."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
