// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:en",
	"name": "English Capability Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-en",
	"targets": {
		"languages": [
			"en"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"resources": [
		{
			"id": "bcp47-language-subtags",
			"kind": "language-registry",
			"path": "resources/bcp47.language-subtags.tsv.gz.b64",
			"format": "tsv",
			"license": "LicenseRef-IANA-Language-Subtag-Registry",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05."
			],
			"schemaId": "textfacts.language-registry.v1"
		},
		{
			"id": "bcp47-language-registry-summary",
			"kind": "language-registry",
			"path": "resources/bcp47.language-registry.summary.json",
			"format": "json",
			"license": "LicenseRef-IANA-Language-Subtag-Registry",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05."
			],
			"schemaId": "textfacts.language-registry.v1"
		},
		{
			"id": "unicode-17-blocks",
			"kind": "unicode-profile",
			"path": "resources/unicode-17.blocks.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			],
			"schemaId": "textfacts.unicode-profile.v1"
		},
		{
			"id": "unicode-17-property-value-aliases",
			"kind": "unicode-profile",
			"path": "resources/unicode-17.property-value-aliases.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			],
			"schemaId": "textfacts.unicode-profile.v1"
		},
		{
			"id": "unicode-17-scripts",
			"kind": "unicode-profile",
			"path": "resources/unicode-17.scripts.tsv.gz.b64",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			],
			"schemaId": "textfacts.unicode-profile.v1"
		},
		{
			"id": "unicode-17-core-summary",
			"kind": "unicode-profile",
			"path": "resources/unicode-17.core.summary.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			],
			"schemaId": "textfacts.unicode-profile.v1"
		},
		{
			"id": "cldr-48-likely-subtags",
			"kind": "locale-profile",
			"path": "resources/cldr-48.likely-subtags.tsv.gz.b64",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textfacts.locale-profile.v1"
		},
		{
			"id": "cldr-48-locale-aliases",
			"kind": "locale-profile",
			"path": "resources/cldr-48.locale-aliases.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textfacts.locale-profile.v1"
		},
		{
			"id": "cldr-48-script-data",
			"kind": "locale-profile",
			"path": "resources/cldr-48.script-data.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textfacts.locale-profile.v1"
		},
		{
			"id": "cldr-48-core-summary",
			"kind": "locale-profile",
			"path": "resources/cldr-48.core.summary.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textfacts.locale-profile.v1"
		},
		{
			"id": "en-core-language-profile",
			"kind": "locale-profile",
			"path": "resources/en.core.language-profile.json",
			"format": "json",
			"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry AND LicenseRef-ESDB-MIT-Like",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05.",
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"English Speller Database generated wordlist outputs, rel-2026.02.25.",
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textfacts.locale-profile.v1"
		},
		{
			"id": "en-core-orthography",
			"kind": "locale-profile",
			"path": "resources/en.core.orthography.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			],
			"schemaId": "textfacts.locale-profile.v1"
		},
		{
			"id": "en-core-punctuation",
			"kind": "locale-profile",
			"path": "resources/en.core.punctuation.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			],
			"schemaId": "textfacts.locale-profile.v1"
		},
		{
			"id": "en-core-abbreviations",
			"kind": "abbreviation-table",
			"path": "resources/en.core.abbreviations.tsv.gz.b64",
			"format": "tsv",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textlex.abbreviation-table.v1"
		},
		{
			"id": "en-core-function-words",
			"kind": "stoplist",
			"path": "resources/en.core.function-words.tsv",
			"format": "tsv",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textlex.stoplist.v1"
		},
		{
			"id": "en-core-basic-segmentation",
			"kind": "segmentation-profile",
			"path": "resources/en.core.basic-segmentation.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textdata.segmentation-profile.v1"
		},
		{
			"id": "en-core-quality",
			"kind": "quality-profile",
			"path": "resources/en.core.quality.json",
			"format": "json",
			"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry AND LicenseRef-ESDB-MIT-Like",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05.",
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"English Speller Database generated wordlist outputs, rel-2026.02.25.",
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textquality.evidence.v1"
		},
		{
			"id": "en-core-quality-profile",
			"kind": "quality-profile",
			"path": "resources/en.core.quality-profile.json",
			"format": "json",
			"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry AND LicenseRef-ESDB-MIT-Like",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05.",
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"English Speller Database generated wordlist outputs, rel-2026.02.25.",
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textquality.profile.v1"
		},
		{
			"id": "en-normalization-rules",
			"kind": "normalization-profile",
			"path": "resources/en.normalization-rules.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textnorm.rules.v1"
		},
		{
			"id": "en-normalization-profile",
			"kind": "normalization-profile",
			"path": "resources/en.normalization.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textnorm.profile.v1"
		},
		{
			"id": "en-normalization-quality",
			"kind": "quality-profile",
			"path": "resources/en.normalization.quality.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textquality.evidence.v1"
		},
		{
			"id": "en-normalization-quality-profile",
			"kind": "quality-profile",
			"path": "resources/en.normalization.quality-profile.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textquality.profile.v1"
		},
		{
			"id": "en-segmentation-boundary-properties",
			"kind": "segmentation-profile",
			"path": "resources/en.segmentation-boundary-properties.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textdata.segmentation-table.v1"
		},
		{
			"id": "en-grapheme-segmentation-profile",
			"kind": "segmentation-profile",
			"path": "resources/en.segmentation.grapheme.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textdata.segmentation-profile.v1"
		},
		{
			"id": "en-word-segmentation-profile",
			"kind": "segmentation-profile",
			"path": "resources/en.segmentation.word.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textdata.segmentation-profile.v1"
		},
		{
			"id": "en-sentence-segmentation-profile",
			"kind": "segmentation-profile",
			"path": "resources/en.segmentation.sentence.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textdata.segmentation-profile.v1"
		},
		{
			"id": "en-segmentation-quality",
			"kind": "quality-profile",
			"path": "resources/en.segmentation.quality.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textquality.evidence.v1"
		},
		{
			"id": "en-segmentation-quality-profile",
			"kind": "quality-profile",
			"path": "resources/en.segmentation.quality-profile.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textquality.profile.v1"
		},
		{
			"id": "en-esdb-default-wordlists",
			"kind": "lexicon",
			"path": "resources/esdb-2026.default-wordlists.lookup-index.v1.txt",
			"format": "textpack-indexed-table-v1",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"English Speller Database generated wordlist outputs, rel-2026.02.25."
			],
			"schemaId": "textlex.lexicon.rows.v1",
			"metadata": {
				"storageFormat": "textpack-indexed-table-v1",
				"lookupIndexResourceId": "en-esdb-default-wordlists-lookup-index",
				"logicalFormat": "tsv+gzip+base64",
				"logicalPath": "resources/esdb-2026.default-wordlists.tsv.gz.b64",
				"logicalTextChecksum": "sha256:a21cffb19ea0c58045a6939601430be9c066a26294b1602285ccbd5177ba5ba2",
				"logicalTextByteLength": 20301511,
				"logicalRowCount": 548642
			}
		},
		{
			"id": "en-esdb-default-profiles",
			"kind": "lexicon",
			"path": "resources/esdb-2026.default-profiles.tsv",
			"format": "tsv",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"English Speller Database generated wordlist outputs, rel-2026.02.25."
			],
			"schemaId": "textlex.lexicon.rows.v1"
		},
		{
			"id": "en-esdb-wordlist-lexicon-canonical",
			"kind": "lexicon",
			"path": "resources/esdb-2026.lexicon.json",
			"format": "json",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"English Speller Database generated wordlist outputs, rel-2026.02.25."
			],
			"schemaId": "textlex.lexicon.v1"
		},
		{
			"id": "en-esdb-wordlist-search-profile",
			"kind": "search-profile",
			"path": "resources/esdb-2026.search-profile.json",
			"format": "json",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"English Speller Database generated wordlist outputs, rel-2026.02.25."
			],
			"schemaId": "textsearch.analyzer-profile.v1"
		},
		{
			"id": "en-esdb-wordlist-quality",
			"kind": "quality-profile",
			"path": "resources/esdb-2026.quality.json",
			"format": "json",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"English Speller Database generated wordlist outputs, rel-2026.02.25."
			],
			"schemaId": "textquality.evidence.v1"
		},
		{
			"id": "en-esdb-wordlist-quality-profile",
			"kind": "quality-profile",
			"path": "resources/esdb-2026.quality-profile.json",
			"format": "json",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"English Speller Database generated wordlist outputs, rel-2026.02.25."
			],
			"schemaId": "textquality.profile.v1"
		},
		{
			"id": "en-esdb-default-wordlists-lookup-index",
			"kind": "dataset",
			"path": "resources/esdb-2026.default-wordlists.lookup-index.v1.txt",
			"format": "textpack-indexed-table-v1",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"English Speller Database generated wordlist outputs, rel-2026.02.25."
			],
			"schemaId": "textpack.lookup-index.v1",
			"metadata": {
				"indexFormat": "normalized-key-bucketed-rows-v1",
				"indexedResourceId": "en-esdb-default-wordlists",
				"indexedResourceSchemaId": "textlex.lexicon.rows.v1",
				"indexedResourceTextChecksum": "sha256:a21cffb19ea0c58045a6939601430be9c066a26294b1602285ccbd5177ba5ba2",
				"keyNormalization": "NFKC-casefold-Unicode-17",
				"keyColumns": [
					"word"
				],
				"emptyKeyColumns": [],
				"fuzzyColumns": [],
				"patternColumns": [
					"word"
				],
				"bucketCount": 2048,
				"sourceRowCount": 548642,
				"recordCount": 111648,
				"rowReferenceCount": 548642,
				"indexedResourceTextByteLength": 20301511,
				"lookupIndexShippedByteLength": 5071007,
				"lookupIndexHeaderByteLength": 799507,
				"lookupIndexHeaderChecksum": "sha256:e85fcd2161d0adb22348305cbf89e5b0bea4c02827c7320965345fed79b58214",
				"storageBudgetByteLength": 26391965,
				"storageSizeRatio": 0.24978470814315248,
				"maximumBucketByteLength": 94700
			}
		},
		{
			"id": "en-scowl-inflection-entries",
			"kind": "morphology",
			"path": "resources/scowl-v2.inflections.lookup-index.v1.txt",
			"format": "textpack-indexed-table-v1",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textlex.morphology.rows.v1",
			"metadata": {
				"storageFormat": "textpack-indexed-table-v1",
				"lookupIndexResourceId": "en-scowl-inflection-entries-lookup-index",
				"logicalFormat": "tsv+gzip+base64",
				"logicalPath": "resources/scowl-v2.inflections.tsv.gz.b64",
				"logicalTextChecksum": "sha256:cf7637649c1ccb607c5a09898dfc838a1f49557d0ba289bff1033c5a93cf0ea4",
				"logicalTextByteLength": 33487594,
				"logicalRowCount": 401709
			}
		},
		{
			"id": "en-scowl-pos-inventory",
			"kind": "morphology",
			"path": "resources/scowl-v2.pos.tsv",
			"format": "tsv",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textlex.morphology.rows.v1"
		},
		{
			"id": "en-scowl-inflection-lexicon-canonical",
			"kind": "lexicon",
			"path": "resources/scowl-v2.lexicon.json",
			"format": "json",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textlex.lexicon.v1"
		},
		{
			"id": "en-scowl-inflection-morphology-canonical",
			"kind": "morphology",
			"path": "resources/scowl-v2.morphology.json",
			"format": "json",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textlex.morphology.v1"
		},
		{
			"id": "en-scowl-inflection-quality",
			"kind": "quality-profile",
			"path": "resources/scowl-v2.quality.json",
			"format": "json",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textquality.evidence.v1"
		},
		{
			"id": "en-scowl-inflection-quality-profile",
			"kind": "quality-profile",
			"path": "resources/scowl-v2.quality-profile.json",
			"format": "json",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textquality.profile.v1"
		},
		{
			"id": "en-scowl-inflection-entries-lookup-index",
			"kind": "dataset",
			"path": "resources/scowl-v2.inflections.lookup-index.v1.txt",
			"format": "textpack-indexed-table-v1",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textpack.lookup-index.v1",
			"metadata": {
				"indexFormat": "normalized-key-bucketed-rows-v1",
				"indexedResourceId": "en-scowl-inflection-entries",
				"indexedResourceSchemaId": "textlex.morphology.rows.v1",
				"indexedResourceTextChecksum": "sha256:cf7637649c1ccb607c5a09898dfc838a1f49557d0ba289bff1033c5a93cf0ea4",
				"keyNormalization": "NFKC-casefold-Unicode-17",
				"keyColumns": [
					"form",
					"lemma"
				],
				"emptyKeyColumns": [],
				"fuzzyColumns": [],
				"patternColumns": [
					"form"
				],
				"bucketCount": 2048,
				"sourceRowCount": 401709,
				"recordCount": 548801,
				"rowReferenceCount": 800253,
				"indexedResourceTextByteLength": 33487594,
				"lookupIndexShippedByteLength": 14811047,
				"lookupIndexHeaderByteLength": 817067,
				"lookupIndexHeaderChecksum": "sha256:dcf4bc0731f51a68aea8d7279635b4ac9c57f07447fab1d43f145710bbb1490e",
				"storageBudgetByteLength": 43533873,
				"storageSizeRatio": 0.4422845964986317,
				"maximumBucketByteLength": 265908
			}
		},
		{
			"id": "wordnet-en-lexical-entries",
			"kind": "lexicon",
			"path": "resources/wordnet-en.lexical-entries.lookup-index.v1.txt",
			"format": "textpack-indexed-table-v1",
			"license": "LicenseRef-Princeton-WordNet AND CC-BY-4.0",
			"citations": [
				"Open English WordNet 2025."
			],
			"schemaId": "textlex.lexicon.rows.v1",
			"metadata": {
				"storageFormat": "textpack-indexed-table-v1",
				"lookupIndexResourceId": "wordnet-en-lexical-entries-lookup-index",
				"logicalFormat": "tsv",
				"logicalPath": "resources/wordnet-en.lexical-entries.tsv",
				"logicalTextChecksum": "sha256:f664206820369a0d71b9e969a1727df6f7646fb76261297630b78426d410342b",
				"logicalTextByteLength": 4485654,
				"logicalRowCount": 135969
			}
		},
		{
			"id": "wordnet-en-senses",
			"kind": "knowledge-base",
			"path": "resources/wordnet-en.senses.tsv.gz.b64",
			"format": "tsv",
			"license": "LicenseRef-Princeton-WordNet AND CC-BY-4.0",
			"citations": [
				"Open English WordNet 2025."
			],
			"schemaId": "textkb.knowledge-base.rows.v1"
		},
		{
			"id": "wordnet-en-synsets",
			"kind": "knowledge-base",
			"path": "resources/wordnet-en.synsets.tsv.gz.b64",
			"format": "tsv",
			"license": "LicenseRef-Princeton-WordNet AND CC-BY-4.0",
			"citations": [
				"Open English WordNet 2025."
			],
			"schemaId": "textkb.knowledge-base.rows.v1"
		},
		{
			"id": "wordnet-en-relations",
			"kind": "knowledge-base",
			"path": "resources/wordnet-en.relations.tsv.gz.b64",
			"format": "tsv",
			"license": "LicenseRef-Princeton-WordNet AND CC-BY-4.0",
			"citations": [
				"Open English WordNet 2025."
			],
			"schemaId": "textkb.knowledge-base.rows.v1"
		},
		{
			"id": "wordnet-en-quality",
			"kind": "quality-profile",
			"path": "resources/wordnet-en.quality.json",
			"format": "json",
			"license": "LicenseRef-Princeton-WordNet AND CC-BY-4.0",
			"citations": [
				"Open English WordNet 2025."
			],
			"schemaId": "textquality.evidence.v1"
		},
		{
			"id": "wordnet-en-lexicon-canonical",
			"kind": "lexicon",
			"path": "resources/wordnet-en.lexicon.json",
			"format": "json",
			"license": "LicenseRef-Princeton-WordNet AND CC-BY-4.0",
			"citations": [
				"Open English WordNet 2025."
			],
			"schemaId": "textlex.lexicon.v1"
		},
		{
			"id": "wordnet-en-kb-canonical",
			"kind": "knowledge-base",
			"path": "resources/wordnet-en.kb.json",
			"format": "json",
			"license": "LicenseRef-Princeton-WordNet AND CC-BY-4.0",
			"citations": [
				"Open English WordNet 2025."
			],
			"schemaId": "textkb.knowledge-base.v1"
		},
		{
			"id": "wordnet-en-quality-profile",
			"kind": "quality-profile",
			"path": "resources/wordnet-en.quality-profile.json",
			"format": "json",
			"license": "LicenseRef-Princeton-WordNet AND CC-BY-4.0",
			"citations": [
				"Open English WordNet 2025."
			],
			"schemaId": "textquality.profile.v1"
		},
		{
			"id": "wordnet-en-lexical-entries-lookup-index",
			"kind": "dataset",
			"path": "resources/wordnet-en.lexical-entries.lookup-index.v1.txt",
			"format": "textpack-indexed-table-v1",
			"license": "LicenseRef-Princeton-WordNet AND CC-BY-4.0",
			"citations": [
				"Open English WordNet 2025."
			],
			"schemaId": "textpack.lookup-index.v1",
			"metadata": {
				"indexFormat": "normalized-key-bucketed-rows-v1",
				"indexedResourceId": "wordnet-en-lexical-entries",
				"indexedResourceSchemaId": "textlex.lexicon.rows.v1",
				"indexedResourceTextChecksum": "sha256:f664206820369a0d71b9e969a1727df6f7646fb76261297630b78426d410342b",
				"keyNormalization": "NFKC-casefold-Unicode-17",
				"keyColumns": [
					"lemma"
				],
				"emptyKeyColumns": [],
				"fuzzyColumns": [],
				"patternColumns": [
					"lemma"
				],
				"bucketCount": 512,
				"sourceRowCount": 135969,
				"recordCount": 127311,
				"rowReferenceCount": 135969,
				"indexedResourceTextByteLength": 4485654,
				"lookupIndexShippedByteLength": 3792047,
				"lookupIndexHeaderByteLength": 213911,
				"lookupIndexHeaderChecksum": "sha256:e52fe20acfec9efeb6d94c0c63988768ec600f325a14dc62901e0012afed6048",
				"storageBudgetByteLength": 5831351,
				"storageSizeRatio": 0.8453721575493786,
				"maximumBucketByteLength": 77984
			}
		},
		{
			"id": "wikidata-en-entities",
			"kind": "knowledge-base",
			"path": "resources/wikidata-en.entities.lookup-index.v1.txt",
			"format": "textpack-indexed-table-v1",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08.",
				"Wikidata Query Service English core entity extract, retrieved 2026-06-12."
			],
			"schemaId": "textkb.knowledge-base.rows.v1",
			"metadata": {
				"storageFormat": "textpack-indexed-table-v1",
				"lookupIndexResourceId": "wikidata-en-entities-lookup-index",
				"logicalFormat": "text/tab-separated-values",
				"logicalPath": "resources/wikidata-en.entities.tsv.gz.b64",
				"logicalTextChecksum": "sha256:340b6adb308d3a6d96bbaafc23e74d0b61ff510d504ca2ce44acf0ea7dca4d18",
				"logicalTextByteLength": 1207330,
				"logicalRowCount": 11618
			}
		},
		{
			"id": "wikidata-en-aliases",
			"kind": "knowledge-base",
			"path": "resources/wikidata-en.aliases.lookup-index.v1.txt",
			"format": "textpack-indexed-table-v1",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08.",
				"Wikidata Query Service English core entity extract, retrieved 2026-06-12."
			],
			"schemaId": "textkb.knowledge-base.rows.v1",
			"metadata": {
				"storageFormat": "textpack-indexed-table-v1",
				"lookupIndexResourceId": "wikidata-en-aliases-lookup-index",
				"logicalFormat": "text/tab-separated-values",
				"logicalPath": "resources/wikidata-en.aliases.tsv.gz.b64",
				"logicalTextChecksum": "sha256:12902fab6a73fc4ead00c4e5dfe0050be3c6018797ecb86762132984c383c34f",
				"logicalTextByteLength": 507718,
				"logicalRowCount": 19781
			}
		},
		{
			"id": "wikidata-en-relations",
			"kind": "knowledge-base",
			"path": "resources/wikidata-en.relations.lookup-index.v1.txt",
			"format": "textpack-indexed-table-v1",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08.",
				"Wikidata Query Service English core entity extract, retrieved 2026-06-12."
			],
			"schemaId": "textkb.knowledge-base.rows.v1",
			"metadata": {
				"storageFormat": "textpack-indexed-table-v1",
				"lookupIndexResourceId": "wikidata-en-relations-lookup-index",
				"logicalFormat": "text/tab-separated-values",
				"logicalPath": "resources/wikidata-en.relations.tsv.gz.b64",
				"logicalTextChecksum": "sha256:c3d1e904cc688092411dc84d6b800d6502f745fcb7d4e29fc95c9ba8a2e2caf2",
				"logicalTextByteLength": 363996,
				"logicalRowCount": 11618
			}
		},
		{
			"id": "wikidata-en-kb-canonical",
			"kind": "knowledge-base",
			"path": "resources/wikidata-en.kb.json",
			"format": "json",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08.",
				"Wikidata Query Service English core entity extract, retrieved 2026-06-12."
			],
			"schemaId": "textkb.knowledge-base.v1"
		},
		{
			"id": "wikidata-en-quality",
			"kind": "quality-profile",
			"path": "resources/wikidata-en.quality.json",
			"format": "json",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08.",
				"Wikidata Query Service English core entity extract, retrieved 2026-06-12."
			],
			"schemaId": "textquality.evidence.v1"
		},
		{
			"id": "wikidata-en-quality-profile",
			"kind": "quality-profile",
			"path": "resources/wikidata-en.quality-profile.json",
			"format": "json",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08.",
				"Wikidata Query Service English core entity extract, retrieved 2026-06-12."
			],
			"schemaId": "textquality.profile.v1"
		},
		{
			"id": "wikidata-en-entities-lookup-index",
			"kind": "dataset",
			"path": "resources/wikidata-en.entities.lookup-index.v1.txt",
			"format": "textpack-indexed-table-v1",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08.",
				"Wikidata Query Service English core entity extract, retrieved 2026-06-12."
			],
			"schemaId": "textpack.lookup-index.v1",
			"metadata": {
				"indexFormat": "normalized-key-bucketed-rows-v1",
				"indexedResourceId": "wikidata-en-entities",
				"indexedResourceSchemaId": "textkb.knowledge-base.rows.v1",
				"indexedResourceTextChecksum": "sha256:340b6adb308d3a6d96bbaafc23e74d0b61ff510d504ca2ce44acf0ea7dca4d18",
				"keyNormalization": "NFKC-casefold-Unicode-17",
				"keyColumns": [
					"entityId",
					"label"
				],
				"emptyKeyColumns": [],
				"fuzzyColumns": [
					"label"
				],
				"patternColumns": [],
				"bucketCount": 128,
				"sourceRowCount": 11618,
				"recordCount": 23061,
				"rowReferenceCount": 23236,
				"indexedResourceTextByteLength": 1207330,
				"lookupIndexShippedByteLength": 768146,
				"lookupIndexHeaderByteLength": 60090,
				"lookupIndexHeaderChecksum": "sha256:f66040ddc8725caf324c103e0111cb7af7f40fe31823f29142e3d7ada1cf76d9",
				"storageBudgetByteLength": 1569529,
				"storageSizeRatio": 0.6362353291974854,
				"maximumBucketByteLength": 8248
			}
		},
		{
			"id": "wikidata-en-aliases-lookup-index",
			"kind": "dataset",
			"path": "resources/wikidata-en.aliases.lookup-index.v1.txt",
			"format": "textpack-indexed-table-v1",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08.",
				"Wikidata Query Service English core entity extract, retrieved 2026-06-12."
			],
			"schemaId": "textpack.lookup-index.v1",
			"metadata": {
				"indexFormat": "normalized-key-bucketed-rows-v1",
				"indexedResourceId": "wikidata-en-aliases",
				"indexedResourceSchemaId": "textkb.knowledge-base.rows.v1",
				"indexedResourceTextChecksum": "sha256:12902fab6a73fc4ead00c4e5dfe0050be3c6018797ecb86762132984c383c34f",
				"keyNormalization": "NFKC-casefold-Unicode-17",
				"keyColumns": [
					"alias",
					"entityId"
				],
				"emptyKeyColumns": [],
				"fuzzyColumns": [
					"alias"
				],
				"patternColumns": [],
				"bucketCount": 8,
				"sourceRowCount": 19781,
				"recordCount": 28613,
				"rowReferenceCount": 39562,
				"indexedResourceTextByteLength": 507718,
				"lookupIndexShippedByteLength": 656947,
				"lookupIndexHeaderByteLength": 16727,
				"lookupIndexHeaderChecksum": "sha256:f37bede7c299705485d6c7273c1c8d5f1186ca7767f1dde3e48a461584778204",
				"storageBudgetByteLength": 660034,
				"storageSizeRatio": 1.2939210349052033,
				"maximumBucketByteLength": 38972
			}
		},
		{
			"id": "wikidata-en-relations-lookup-index",
			"kind": "dataset",
			"path": "resources/wikidata-en.relations.lookup-index.v1.txt",
			"format": "textpack-indexed-table-v1",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08.",
				"Wikidata Query Service English core entity extract, retrieved 2026-06-12."
			],
			"schemaId": "textpack.lookup-index.v1",
			"metadata": {
				"indexFormat": "normalized-key-bucketed-rows-v1",
				"indexedResourceId": "wikidata-en-relations",
				"indexedResourceSchemaId": "textkb.knowledge-base.rows.v1",
				"indexedResourceTextChecksum": "sha256:c3d1e904cc688092411dc84d6b800d6502f745fcb7d4e29fc95c9ba8a2e2caf2",
				"keyNormalization": "NFKC-casefold-Unicode-17",
				"keyColumns": [
					"sourceId",
					"targetId"
				],
				"emptyKeyColumns": [],
				"fuzzyColumns": [],
				"patternColumns": [],
				"bucketCount": 32,
				"sourceRowCount": 11618,
				"recordCount": 11623,
				"rowReferenceCount": 23236,
				"indexedResourceTextByteLength": 363996,
				"lookupIndexShippedByteLength": 158068,
				"lookupIndexHeaderByteLength": 12760,
				"lookupIndexHeaderChecksum": "sha256:b30f7cfde297d99f6d413f708b570de1077bb811fc97cfbbeac7ae88d108a4fe",
				"storageBudgetByteLength": 473195,
				"storageSizeRatio": 0.43425751931339907,
				"maximumBucketByteLength": 8028
			}
		}
	],
	"capabilitySlots": [
		{
			"slot": "core",
			"status": "profiled",
			"tier": "resource-only",
			"resourceIds": [
				"en-core-language-profile",
				"en-core-orthography",
				"en-core-punctuation",
				"en-core-abbreviations",
				"en-core-function-words",
				"en-core-basic-segmentation"
			],
			"bindings": [
				{
					"role": "profile",
					"resourceId": "en-core-basic-segmentation",
					"schemaId": "textdata.segmentation-profile.v1",
					"required": true
				},
				{
					"role": "profile",
					"resourceId": "en-core-language-profile",
					"schemaId": "textfacts.locale-profile.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "en-core-abbreviations",
					"schemaId": "textlex.abbreviation-table.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "en-core-function-words",
					"schemaId": "textlex.stoplist.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "en-core-orthography",
					"schemaId": "textfacts.locale-profile.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "en-core-punctuation",
					"schemaId": "textfacts.locale-profile.v1",
					"required": true
				}
			],
			"readerRequired": true,
			"notes": [
				"The bundled distribution resources provide the English core language profile.",
				"Core profile resources cover modern typed English identity, Latin-script orthography, Unicode punctuation, SCOWLv2 abbreviation rows, SCOWLv2 POS-derived function-word stoplist candidates, and a basic UAX #29 segmentation baseline."
			],
			"capabilities": {
				"segmentation": "profile",
				"normalization": "unicode"
			}
		},
		{
			"slot": "corpus",
			"status": "planned",
			"tier": "none",
			"notes": [
				"Large corpus payloads are explicit forge acquisitions, not part of the ordinary language package."
			]
		},
		{
			"slot": "foundation",
			"status": "profiled",
			"tier": "resource-only",
			"notes": [
				"The bundled distribution resources provide Unicode, CLDR, and BCP 47 foundation data."
			]
		},
		{
			"slot": "kb",
			"status": "task-supported",
			"tier": "lookup",
			"resourceIds": [
				"wordnet-en-senses",
				"wordnet-en-synsets",
				"wordnet-en-relations",
				"wordnet-en-kb-canonical",
				"wikidata-en-entities",
				"wikidata-en-aliases",
				"wikidata-en-relations",
				"wikidata-en-kb-canonical",
				"wikidata-en-entities-lookup-index",
				"wikidata-en-aliases-lookup-index",
				"wikidata-en-relations-lookup-index"
			],
			"artifactIds": [
				"artifact:textpack-wikidata-en:full:wikidata-entities-json:20260608"
			],
			"bindings": [
				{
					"role": "index",
					"resourceId": "wikidata-en-aliases-lookup-index",
					"schemaId": "textpack.lookup-index.v1",
					"required": true
				},
				{
					"role": "index",
					"resourceId": "wikidata-en-entities-lookup-index",
					"schemaId": "textpack.lookup-index.v1",
					"required": true
				},
				{
					"role": "index",
					"resourceId": "wikidata-en-relations-lookup-index",
					"schemaId": "textpack.lookup-index.v1",
					"required": true
				},
				{
					"role": "primary",
					"resourceId": "wikidata-en-kb-canonical",
					"schemaId": "textkb.knowledge-base.v1",
					"required": true
				},
				{
					"role": "primary",
					"resourceId": "wordnet-en-kb-canonical",
					"schemaId": "textkb.knowledge-base.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "wikidata-en-aliases",
					"schemaId": "textkb.knowledge-base.rows.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "wikidata-en-entities",
					"schemaId": "textkb.knowledge-base.rows.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "wikidata-en-relations",
					"schemaId": "textkb.knowledge-base.rows.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "wordnet-en-relations",
					"schemaId": "textkb.knowledge-base.rows.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "wordnet-en-senses",
					"schemaId": "textkb.knowledge-base.rows.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "wordnet-en-synsets",
					"schemaId": "textkb.knowledge-base.rows.v1",
					"required": true
				}
			],
			"readerRequired": true,
			"notes": [
				"The bundled distribution resources provide Open English WordNet data and a local Wikidata English core entity extract.",
				"Open English WordNet senses, synsets, and semantic relations are available as generated KB resources.",
				"Wikidata English core entity rows, aliases, and P31 relations are materialized locally for the declared class-and-sitelink-threshold extract scope.",
				"The pack does not claim complete Wikidata dump coverage."
			],
			"capabilities": {
				"terminology": "kb",
				"extraction": "gazetteer"
			}
		},
		{
			"slot": "language-registry",
			"status": "profiled",
			"tier": "resource-only",
			"resourceIds": [
				"bcp47-language-subtags",
				"bcp47-language-registry-summary"
			],
			"bindings": [
				{
					"role": "primary",
					"resourceId": "bcp47-language-registry-summary",
					"schemaId": "textfacts.language-registry.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "bcp47-language-subtags",
					"schemaId": "textfacts.language-registry.v1",
					"required": true
				}
			],
			"readerRequired": true,
			"notes": [
				"BCP 47 subtag registry resources are available for language, script, region, variant, grandfathered, and redundant tag consumers."
			]
		},
		{
			"slot": "lexicon",
			"status": "task-supported",
			"tier": "lookup",
			"resourceIds": [
				"en-esdb-default-wordlists",
				"en-esdb-default-profiles",
				"en-esdb-wordlist-lexicon-canonical",
				"en-esdb-default-wordlists-lookup-index",
				"en-scowl-inflection-lexicon-canonical",
				"wordnet-en-lexical-entries",
				"wordnet-en-lexicon-canonical",
				"wordnet-en-lexical-entries-lookup-index"
			],
			"bindings": [
				{
					"role": "index",
					"resourceId": "en-esdb-default-wordlists-lookup-index",
					"schemaId": "textpack.lookup-index.v1",
					"required": true
				},
				{
					"role": "index",
					"resourceId": "wordnet-en-lexical-entries-lookup-index",
					"schemaId": "textpack.lookup-index.v1",
					"required": true
				},
				{
					"role": "primary",
					"resourceId": "en-esdb-wordlist-lexicon-canonical",
					"schemaId": "textlex.lexicon.v1",
					"required": true
				},
				{
					"role": "primary",
					"resourceId": "en-scowl-inflection-lexicon-canonical",
					"schemaId": "textlex.lexicon.v1",
					"required": true
				},
				{
					"role": "primary",
					"resourceId": "wordnet-en-lexicon-canonical",
					"schemaId": "textlex.lexicon.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "en-esdb-default-profiles",
					"schemaId": "textlex.lexicon.rows.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "en-esdb-default-wordlists",
					"schemaId": "textlex.lexicon.rows.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "wordnet-en-lexical-entries",
					"schemaId": "textlex.lexicon.rows.v1",
					"required": true
				}
			],
			"readerRequired": true,
			"notes": [
				"The bundled distribution resources provide English spelling, inflection-inventory, and lexical-semantic lexicon data.",
				"ESDB default regional spell-checker wordlists are available as generated English spelling-form resources. This pack does not claim full lexical semantics or morphology coverage.",
				"Generated canonical lexicon resource references SCOWLv2 lemma and form inventory coverage for lookup consumers.",
				"Open English WordNet lexical entries are available as generated lexicon resources."
			],
			"capabilities": {
				"terminology": "lexicon",
				"extraction": "gazetteer"
			}
		},
		{
			"slot": "locale-profile",
			"status": "profiled",
			"tier": "resource-only",
			"resourceIds": [
				"cldr-48-likely-subtags",
				"cldr-48-locale-aliases",
				"cldr-48-script-data",
				"cldr-48-core-summary"
			],
			"bindings": [
				{
					"role": "profile",
					"resourceId": "cldr-48-core-summary",
					"schemaId": "textfacts.locale-profile.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "cldr-48-likely-subtags",
					"schemaId": "textfacts.locale-profile.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "cldr-48-locale-aliases",
					"schemaId": "textfacts.locale-profile.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "cldr-48-script-data",
					"schemaId": "textfacts.locale-profile.v1",
					"required": true
				}
			],
			"readerRequired": true,
			"notes": [
				"CLDR likely-subtag, alias, and script variant resources are available for locale and script profile consumers."
			]
		},
		{
			"slot": "morphology",
			"status": "task-supported",
			"tier": "lookup",
			"resourceIds": [
				"en-scowl-inflection-entries",
				"en-scowl-pos-inventory",
				"en-scowl-inflection-morphology-canonical",
				"en-scowl-inflection-entries-lookup-index"
			],
			"bindings": [
				{
					"role": "index",
					"resourceId": "en-scowl-inflection-entries-lookup-index",
					"schemaId": "textpack.lookup-index.v1",
					"required": true
				},
				{
					"role": "primary",
					"resourceId": "en-scowl-inflection-morphology-canonical",
					"schemaId": "textlex.morphology.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "en-scowl-inflection-entries",
					"schemaId": "textlex.morphology.rows.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "en-scowl-pos-inventory",
					"schemaId": "textlex.morphology.rows.v1",
					"required": true
				}
			],
			"readerRequired": true,
			"notes": [
				"The bundled distribution resources provide English SCOWLv2 lookup morphology data; isolated UniMorph paradigm tables are not included.",
				"One SCOWLv2 inflection table serves targeted form-to-lemma analysis and lemma-to-form generation through its form-and-lemma lookup index."
			],
			"capabilities": {
				"morphology": "lookup"
			}
		},
		{
			"slot": "normalization",
			"status": "task-supported",
			"tier": "baseline",
			"resourceIds": [
				"en-normalization-rules",
				"en-normalization-profile"
			],
			"bindings": [
				{
					"role": "profile",
					"resourceId": "en-normalization-profile",
					"schemaId": "textnorm.profile.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "en-normalization-rules",
					"schemaId": "textnorm.rules.v1",
					"required": true
				}
			],
			"readerRequired": true,
			"notes": [
				"The bundled distribution resources provide English normalization data.",
				"Unicode/CLDR-backed NFC and lookup casefold policy for modern typed English text."
			],
			"capabilities": {
				"normalization": "unicode"
			}
		},
		{
			"slot": "parallel",
			"status": "planned",
			"tier": "none",
			"notes": [
				"Large alignment payloads are explicit forge acquisitions, not part of the ordinary language package."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"tier": "rule-based",
			"resourceIds": [
				"en-core-quality",
				"en-core-quality-profile",
				"en-normalization-quality",
				"en-normalization-quality-profile",
				"en-segmentation-quality",
				"en-segmentation-quality-profile",
				"en-esdb-wordlist-quality",
				"en-esdb-wordlist-quality-profile",
				"en-scowl-inflection-quality",
				"en-scowl-inflection-quality-profile",
				"wordnet-en-quality",
				"wordnet-en-quality-profile",
				"wikidata-en-quality",
				"wikidata-en-quality-profile"
			],
			"bindings": [
				{
					"role": "evidence",
					"resourceId": "en-core-quality",
					"schemaId": "textquality.evidence.v1",
					"required": true
				},
				{
					"role": "evidence",
					"resourceId": "en-esdb-wordlist-quality",
					"schemaId": "textquality.evidence.v1",
					"required": true
				},
				{
					"role": "evidence",
					"resourceId": "en-normalization-quality",
					"schemaId": "textquality.evidence.v1",
					"required": true
				},
				{
					"role": "evidence",
					"resourceId": "en-scowl-inflection-quality",
					"schemaId": "textquality.evidence.v1",
					"required": true
				},
				{
					"role": "evidence",
					"resourceId": "en-segmentation-quality",
					"schemaId": "textquality.evidence.v1",
					"required": true
				},
				{
					"role": "evidence",
					"resourceId": "wikidata-en-quality",
					"schemaId": "textquality.evidence.v1",
					"required": true
				},
				{
					"role": "evidence",
					"resourceId": "wordnet-en-quality",
					"schemaId": "textquality.evidence.v1",
					"required": true
				},
				{
					"role": "quality",
					"resourceId": "en-core-quality-profile",
					"schemaId": "textquality.profile.v1",
					"required": true
				},
				{
					"role": "quality",
					"resourceId": "en-esdb-wordlist-quality-profile",
					"schemaId": "textquality.profile.v1",
					"required": true
				},
				{
					"role": "quality",
					"resourceId": "en-normalization-quality-profile",
					"schemaId": "textquality.profile.v1",
					"required": true
				},
				{
					"role": "quality",
					"resourceId": "en-scowl-inflection-quality-profile",
					"schemaId": "textquality.profile.v1",
					"required": true
				},
				{
					"role": "quality",
					"resourceId": "en-segmentation-quality-profile",
					"schemaId": "textquality.profile.v1",
					"required": true
				},
				{
					"role": "quality",
					"resourceId": "wikidata-en-quality-profile",
					"schemaId": "textquality.profile.v1",
					"required": true
				},
				{
					"role": "quality",
					"resourceId": "wordnet-en-quality-profile",
					"schemaId": "textquality.profile.v1",
					"required": true
				}
			],
			"readerRequired": true,
			"notes": [
				"The bundled distribution resources provide generated English quality evidence and coverage reports over the selected local build units.",
				"Generated quality profile records source coverage, accepted records, rejected records, and scope limitations.",
				"Generated quality profile records source coverage, accepted records, and scope limitations.",
				"Generated quality profile records boundary-property coverage, source counts, accepted records, and scope limitations.",
				"Generated quality profile records profile counts, word counts, and transform integrity.",
				"Generated quality profile records lemma, form, POS, and transform-integrity counts.",
				"Generated quality profile records lexical-entry, sense, synset, and relation counts.",
				"Generated quality profile records local entity, alias, relation, scope, and checksum evidence."
			]
		},
		{
			"slot": "search",
			"status": "task-supported",
			"tier": "baseline",
			"resourceIds": [
				"en-esdb-wordlist-search-profile"
			],
			"bindings": [
				{
					"role": "profile",
					"resourceId": "en-esdb-wordlist-search-profile",
					"schemaId": "textsearch.analyzer-profile.v1",
					"required": true
				}
			],
			"readerRequired": true,
			"notes": [
				"The bundled distribution resources provide English search analyzer data.",
				"The executable profile performs Unicode word tokenization and casefolding. ESDB spelling forms remain available through the lexicon slot for explicit spelling or suggestion logic; they are not silently used as a token filter."
			],
			"capabilities": {
				"search": "analyzer"
			}
		},
		{
			"slot": "segmentation",
			"status": "task-supported",
			"tier": "baseline",
			"resourceIds": [
				"en-grapheme-segmentation-profile",
				"en-word-segmentation-profile",
				"en-sentence-segmentation-profile"
			],
			"bindings": [
				{
					"role": "profile",
					"resourceId": "en-grapheme-segmentation-profile",
					"schemaId": "textdata.segmentation-profile.v1",
					"required": true
				},
				{
					"role": "profile",
					"resourceId": "en-sentence-segmentation-profile",
					"schemaId": "textdata.segmentation-profile.v1",
					"required": true
				},
				{
					"role": "profile",
					"resourceId": "en-word-segmentation-profile",
					"schemaId": "textdata.segmentation-profile.v1",
					"required": true
				}
			],
			"readerRequired": true,
			"notes": [
				"The bundled distribution executes pinned Unicode 17 UAX #29 segmentation with explicit title-abbreviation sentence exceptions.",
				"The built-in adapter executes pinned Unicode 17 UAX #29 grapheme, word, and sentence segmentation plus the profile's explicit title-abbreviation sentence exceptions."
			],
			"capabilities": {
				"segmentation": "profile"
			}
		},
		{
			"slot": "syntax",
			"status": "planned",
			"tier": "none",
			"notes": [
				"UD annotation datasets are explicit forge acquisitions, not part of the ordinary language package."
			]
		},
		{
			"slot": "unicode-profile",
			"status": "profiled",
			"tier": "resource-only",
			"resourceIds": [
				"unicode-17-blocks",
				"unicode-17-property-value-aliases",
				"unicode-17-scripts",
				"unicode-17-core-summary"
			],
			"bindings": [
				{
					"role": "profile",
					"resourceId": "unicode-17-core-summary",
					"schemaId": "textfacts.unicode-profile.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "unicode-17-blocks",
					"schemaId": "textfacts.unicode-profile.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "unicode-17-property-value-aliases",
					"schemaId": "textfacts.unicode-profile.v1",
					"required": true
				},
				{
					"role": "table",
					"resourceId": "unicode-17-scripts",
					"schemaId": "textfacts.unicode-profile.v1",
					"required": true
				}
			],
			"readerRequired": true,
			"notes": [
				"Unicode 17 script, block, and property-value alias resources are available for Unicode profile consumers."
			]
		}
	],
	"license": "MIT AND LicenseRef-IANA-Language-Subtag-Registry AND Unicode-3.0 AND LicenseRef-ESDB-MIT-Like AND LicenseRef-Princeton-WordNet AND CC-BY-4.0 AND CC0-1.0",
	"citations": [
		"IANA Language Subtag Registry, File-Date 2026-05-05.",
		"Unicode Character Database 17.0.0.",
		"Unicode CLDR core data, cldr-core npm package 48.2.0.",
		"English Speller Database generated wordlist outputs, rel-2026.02.25.",
		"SCOWLv2 rich text export, rel-2026.02.25.",
		"Open English WordNet 2025.",
		"Wikidata main structured data dump, 2026-06-08.",
		"Wikidata Query Service English core entity extract, retrieved 2026-06-12."
	],
	"gapNotes": [
		{
			"id": "gap:pack:en:syntax",
			"slot": "syntax",
			"status": "planned",
			"message": "syntax is planned in this source-backed self-contained language distribution."
		},
		{
			"id": "gap:pack:en:corpus",
			"slot": "corpus",
			"status": "planned",
			"message": "corpus is planned in this source-backed self-contained language distribution."
		},
		{
			"id": "gap:pack:en:parallel",
			"slot": "parallel",
			"status": "planned",
			"message": "parallel is planned in this source-backed self-contained language distribution."
		}
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:0f3b3b639c8736f6bf21ce1275847d9d5e24907b193fa549604faf67c0c77fbf",
		"generatedAt": "2026-06-12T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	},
	"artifacts": [
		{
			"artifactId": "artifact:textpack-wikidata-en:full:wikidata-entities-json:20260608",
			"sourceIds": [
				"source:wikidata:main"
			],
			"version": "20260608",
			"profile": "full",
			"sizeBytes": 142291512349,
			"mediaType": "application/json",
			"compression": "gzip",
			"checksum": {
				"algorithm": "sha1",
				"value": "7a1165f121e50eca8f2e11674971d7f2d3c47b98"
			},
			"licenseExpression": "CC0-1.0",
			"redistributionPolicy": "redistributable",
			"retrieval": {
				"kind": "https",
				"uri": "https://dumps.wikimedia.org/wikidatawiki/entities/20260608/wikidata-20260608-all.json.gz",
				"instructions": "Fetch explicitly and verify against the upstream SHA-1 checksum sidecar before unpacking or indexing."
			},
			"cacheKey": "wikidata-main-20260608-all-json-gzip",
			"expectedFiles": [
				{
					"path": "wikidata-20260608-all.json.gz",
					"sizeBytes": 142291512349,
					"checksum": "sha1:7a1165f121e50eca8f2e11674971d7f2d3c47b98"
				}
			]
		}
	]
} as const;
