// Generated by tools/textpack-forge. Do not edit.

export { manifest } from "./manifest.js";
export { pack } from "./pack.js";
export { resources } from "./resources.js";

import { pack } from "./pack.js";

export default pack;
