// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:en-core",
	"name": "English Core Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-en-core",
	"targets": {
		"languages": [
			"en"
		],
		"scripts": [
			"Latn"
		],
		"regions": [
			"US"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "en-core-language-profile",
			"kind": "locale-profile",
			"path": "resources/en.core.language-profile.json",
			"format": "json",
			"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry AND LicenseRef-ESDB-MIT-Like",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05.",
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"English Speller Database generated wordlist outputs, rel-2026.02.25.",
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textfacts.locale-profile.v1"
		},
		{
			"id": "en-core-orthography",
			"kind": "locale-profile",
			"path": "resources/en.core.orthography.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			],
			"schemaId": "textfacts.locale-profile.v1"
		},
		{
			"id": "en-core-punctuation",
			"kind": "locale-profile",
			"path": "resources/en.core.punctuation.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			],
			"schemaId": "textfacts.locale-profile.v1"
		},
		{
			"id": "en-core-abbreviations",
			"kind": "abbreviation-table",
			"path": "resources/en.core.abbreviations.tsv",
			"format": "tsv",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textlex.abbreviation-table.v1"
		},
		{
			"id": "en-core-function-words",
			"kind": "stoplist",
			"path": "resources/en.core.function-words.tsv",
			"format": "tsv",
			"license": "LicenseRef-ESDB-MIT-Like",
			"citations": [
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textlex.stoplist.v1"
		},
		{
			"id": "en-core-basic-segmentation",
			"kind": "segmentation-profile",
			"path": "resources/en.core.basic-segmentation.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textdata.segmentation-profile.v1"
		},
		{
			"id": "en-core-quality",
			"kind": "quality-profile",
			"path": "resources/en.core.quality.json",
			"format": "json",
			"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry AND LicenseRef-ESDB-MIT-Like",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05.",
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"English Speller Database generated wordlist outputs, rel-2026.02.25.",
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textquality.evidence.v1"
		},
		{
			"id": "en-core-quality-profile",
			"kind": "quality-profile",
			"path": "resources/en.core.quality-profile.json",
			"format": "json",
			"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry AND LicenseRef-ESDB-MIT-Like",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05.",
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"English Speller Database generated wordlist outputs, rel-2026.02.25.",
				"SCOWLv2 rich text export, rel-2026.02.25."
			],
			"schemaId": "textquality.profile.v1"
		}
	],
	"capabilitySlots": [
		{
			"slot": "core",
			"status": "task-supported",
			"resourceIds": [
				"en-core-language-profile",
				"en-core-orthography",
				"en-core-punctuation",
				"en-core-abbreviations",
				"en-core-function-words",
				"en-core-basic-segmentation"
			],
			"bindings": [
				{
					"role": "profile",
					"resourceId": "en-core-basic-segmentation",
					"schemaId": "textdata.segmentation-profile.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textdata"
				},
				{
					"role": "table",
					"resourceId": "en-core-abbreviations",
					"schemaId": "textlex.abbreviation-table.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textlex"
				},
				{
					"role": "table",
					"resourceId": "en-core-function-words",
					"schemaId": "textlex.stoplist.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textlex"
				}
			],
			"readerRequired": true,
			"notes": [
				"Core profile resources cover modern typed English identity, Latin-script orthography, Unicode punctuation, SCOWLv2 abbreviation rows, SCOWLv2 POS-derived function-word stoplist candidates, and a basic UAX #29 segmentation baseline."
			],
			"capabilities": {
				"segmentation": "profile",
				"normalization": "unicode"
			}
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"en-core-quality",
				"en-core-quality-profile"
			],
			"bindings": [
				{
					"role": "evidence",
					"resourceId": "en-core-quality",
					"schemaId": "textquality.evidence.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textquality"
				},
				{
					"role": "quality",
					"resourceId": "en-core-quality-profile",
					"schemaId": "textquality.profile.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textquality"
				}
			],
			"readerRequired": true,
			"notes": [
				"Generated quality profile records source coverage, accepted records, rejected records, and scope limitations."
			]
		}
	],
	"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry AND LicenseRef-ESDB-MIT-Like",
	"citations": [
		"IANA Language Subtag Registry, File-Date 2026-05-05.",
		"Unicode Character Database 17.0.0.",
		"Unicode CLDR core data, cldr-core npm package 48.2.0.",
		"English Speller Database generated wordlist outputs, rel-2026.02.25.",
		"SCOWLv2 rich text export, rel-2026.02.25."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
