// Generated by tools/textpack-forge. Do not edit.

export { manifest } from "./manifest.js";
export { resources } from "./resources.js";

import {
	loadPack,
	type ResolveTextPackComponentsOptions,
	resolvePackComponents,
	type TextPackComponent,
} from "@ismail-elkorchi/textpack";
import { manifest } from "./manifest.js";
import { resources } from "./resources.js";

export interface LoadFrenchOptions
	extends Omit<ResolveTextPackComponentsOptions, "resolveComponent"> {
	readonly resolveComponent?: ResolveTextPackComponentsOptions["resolveComponent"];
}

async function resolveGeneratedComponent(
	component: TextPackComponent,
	options: LoadFrenchOptions,
): Promise<unknown> {
	void options;
	switch (component.packageName) {
		case "@ismail-elkorchi/textpack-foundation": {
			const module = await import(component.packageName);
			const loader = module.loadFoundation;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFoundation.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-fr-core":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-fr-normalization":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-fr-segmentation":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-fr-lexicon": {
			const module = await import(component.packageName);
			const loader = module.loadFrenchLexicon;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFrenchLexicon.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-fr-morphology": {
			const module = await import(component.packageName);
			const loader = module.loadFrenchMorphology;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFrenchMorphology.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-fr-syntax": {
			const module = await import(component.packageName);
			const loader = module.loadFrenchSyntax;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFrenchSyntax.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-fr-kb": {
			const module = await import(component.packageName);
			const loader = module.loadFrenchKnowledgeBase;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFrenchKnowledgeBase.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-fr-search": {
			const module = await import(component.packageName);
			const loader = module.loadFrenchSearch;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFrenchSearch.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-fr-corpus":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-fr-parallel":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-fr-quality": {
			const module = await import(component.packageName);
			const loader = module.loadFrenchQuality;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFrenchQuality.`,
				);
			}
			return loader(options);
		}
		default:
			throw new TypeError(
				`No generated resolver entry for ${component.packageName}.`,
			);
	}
}

export async function loadFrench(options: LoadFrenchOptions = {}) {
	return resolvePackComponents(await loadPack({ manifest, resources }), {
		...options,
		licensePolicy: options.licensePolicy ?? "allow-share-alike",
		artifactPolicy: options.artifactPolicy ?? "fetch-explicit",
		conflictPolicy: options.conflictPolicy ?? "first",
		resolveComponent:
			options.resolveComponent ??
			((component) => resolveGeneratedComponent(component, options)),
	});
}

export default { manifest, resources, loadFrench };
