// Generated by tools/textpack-forge. Do not edit.

import {
	composePacks,
	createPack,
	type PackComposeOptions,
} from "@ismail-elkorchi/textpack";
import componentPack0 from "@ismail-elkorchi/textpack-foundation";
import componentPack1 from "@ismail-elkorchi/textpack-fr-core";
import componentPack9 from "@ismail-elkorchi/textpack-fr-corpus";
import componentPack7 from "@ismail-elkorchi/textpack-fr-kb";
import componentPack4 from "@ismail-elkorchi/textpack-fr-lexicon";
import componentPack5 from "@ismail-elkorchi/textpack-fr-morphology";
import componentPack2 from "@ismail-elkorchi/textpack-fr-normalization";
import componentPack10 from "@ismail-elkorchi/textpack-fr-parallel";
import componentPack11 from "@ismail-elkorchi/textpack-fr-quality";
import componentPack8 from "@ismail-elkorchi/textpack-fr-search";
import componentPack3 from "@ismail-elkorchi/textpack-fr-segmentation";
import componentPack6 from "@ismail-elkorchi/textpack-fr-syntax";

import { manifest } from "./manifest.js";
import { resources } from "./resources.js";

const basePack = createPack(manifest, resources);
const composeOptions: PackComposeOptions = {
	id: manifest.id,
	name: manifest.name,
	version: manifest.version,
	packageName: manifest.packageName,
	conflictPolicy: "first",
	...(manifest.license === undefined ? {} : { license: manifest.license }),
	...(manifest.citations === undefined
		? {}
		: { citations: manifest.citations }),
};
const composedPack = composePacks(
	[
		basePack,
		componentPack0,
		componentPack1,
		componentPack2,
		componentPack3,
		componentPack4,
		componentPack5,
		componentPack6,
		componentPack7,
		componentPack8,
		componentPack9,
		componentPack10,
		componentPack11,
	],
	composeOptions,
);
const composedManifest = {
	...composedPack.manifest,
	...(manifest.components === undefined
		? {}
		: { components: manifest.components }),
};

export const pack = createPack(composedManifest, composedPack.resources);
