// Generated by tools/textpack-forge. Do not edit.

import {
	composePacks,
	createPack,
	type PackComposeOptions,
} from "@ismail-elkorchi/textpack";
import componentPack1 from "@ismail-elkorchi/textpack-wikidata-ar";
import componentPack0 from "@ismail-elkorchi/textpack-wordnet-ar";

import { manifest } from "./manifest.js";
import { resources } from "./resources.js";

const basePack = createPack(manifest, resources);
const composeOptions: PackComposeOptions = {
	id: manifest.id,
	name: manifest.name,
	version: manifest.version,
	packageName: manifest.packageName,
	conflictPolicy: "first",
	...(manifest.license === undefined ? {} : { license: manifest.license }),
	...(manifest.citations === undefined
		? {}
		: { citations: manifest.citations }),
};
const composedPack = composePacks(
	[basePack, componentPack0, componentPack1],
	composeOptions,
);
const composedManifest = {
	...composedPack.manifest,
	...(manifest.components === undefined
		? {}
		: { components: manifest.components }),
};

export const pack = createPack(composedManifest, composedPack.resources);
