// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:cldr-core",
	"name": "CLDR Core Foundation Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-cldr-core",
	"targets": {
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "cldr-48-likely-subtags",
			"kind": "locale-profile",
			"path": "resources/cldr-48.likely-subtags.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			]
		},
		{
			"id": "cldr-48-locale-aliases",
			"kind": "locale-profile",
			"path": "resources/cldr-48.locale-aliases.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			]
		},
		{
			"id": "cldr-48-script-data",
			"kind": "locale-profile",
			"path": "resources/cldr-48.script-data.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			]
		},
		{
			"id": "cldr-48-core-summary",
			"kind": "locale-profile",
			"path": "resources/cldr-48.core.summary.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			]
		}
	],
	"capabilitySlots": [
		{
			"slot": "locale-profile",
			"status": "task-supported",
			"resourceIds": [
				"cldr-48-likely-subtags",
				"cldr-48-locale-aliases",
				"cldr-48-script-data",
				"cldr-48-core-summary"
			],
			"notes": [
				"CLDR likely-subtag, alias, and script variant resources are available for locale and script profile consumers."
			]
		}
	],
	"license": "Unicode-3.0",
	"citations": [
		"Unicode CLDR core data, cldr-core npm package 48.2.0."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:e22af87557cf790195f6e875fdc88877a93cd20b82299a27b03d3c2eda141118",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
