// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"cldr-48-likely-subtags": {"byteLength":126509,"checksum":"sha256:8babca7d23a8e0e784f0fc609a8719e6424fa0804e87444f764740aca2b10fac","encoding":"utf8","kind":"file-backed-resource","lineCount":7790,"nonEmptyLineCount":7789,"path":"resources/cldr-48.likely-subtags.tsv","resourceTextByteLength":126509},
	"cldr-48-locale-aliases": {"byteLength":36386,"checksum":"sha256:9c4e018288bde0698003a52fcba6dad6b907f65ba4585bb142db8cc1c9733419","encoding":"utf8","kind":"file-backed-resource","lineCount":1308,"nonEmptyLineCount":1307,"path":"resources/cldr-48.locale-aliases.tsv","resourceTextByteLength":36386},
	"cldr-48-script-data": {"byteLength":326,"checksum":"sha256:e48aef1d01403e80be986717f4dcccda20064d7cf46a15436f1d921b617f4ab0","encoding":"utf8","kind":"file-backed-resource","lineCount":17,"nonEmptyLineCount":16,"path":"resources/cldr-48.script-data.tsv","resourceTextByteLength":326},
	"cldr-48-core-summary": {"byteLength":192,"checksum":"sha256:274ed6518c70f5ea0f92990b53b3d64ff1834af03b2c655b33a7992bde5d0ff7","encoding":"utf8","kind":"file-backed-resource","lineCount":10,"nonEmptyLineCount":9,"path":"resources/cldr-48.core.summary.json","resourceTextByteLength":192},
} as const;
