export type {
	AliasEntry,
	AliasEntryInput,
	AliasIndex,
	BuildAliasIndexInput,
	ConceptRecord,
	ConceptRecordStore,
	CreateKnowledgeBaseOptions,
	EntityRecord,
	EntityRecordStore,
	EntityRowParseOptions,
	JsonObject,
	JsonValue,
	KnowledgeBase,
	SemanticRelation,
	SemanticRelationStore,
	SemanticRelationStoreOptions,
	SenseRecord,
	SenseRecordStore,
	SourceMapping,
} from "../internal/core.js";
export {
	assertJsonObject,
	assertJsonValue,
	buildAliasIndex,
	createConceptRecordStore,
	createEntityRecordStore,
	createKnowledgeBase,
	createSemanticRelationStore,
	createSenseRecordStore,
	parseAliasRows,
	parseEntityRows,
	parseRelationRows,
} from "../internal/core.js";
