// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:ar-syntax-ud-nyuad-sa",
	"name": "Arabic UD NYUAD Syntax Share-Alike Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-ar-syntax-ud-nyuad-sa",
	"targets": {
		"languages": [
			"ar"
		],
		"scripts": [
			"Arab"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "ar-ud-nyuad-upos",
			"kind": "grammar",
			"path": "resources/ud-nyuad.upos.tsv",
			"format": "tsv",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies Arabic NYUAD r2.18 annotations."
			],
			"schemaId": "textdata.syntax-table.v1"
		},
		{
			"id": "ar-ud-nyuad-features",
			"kind": "morphology",
			"path": "resources/ud-nyuad.features.tsv",
			"format": "tsv",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies Arabic NYUAD r2.18 annotations."
			],
			"schemaId": "textlex.morphology.rows.v1"
		},
		{
			"id": "ar-ud-nyuad-dependencies",
			"kind": "grammar",
			"path": "resources/ud-nyuad.dependencies.tsv",
			"format": "tsv",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies Arabic NYUAD r2.18 annotations."
			],
			"schemaId": "textdata.syntax-table.v1"
		},
		{
			"id": "ar-ud-nyuad-sentence-profile",
			"kind": "statistical-model",
			"path": "resources/ud-nyuad.sentence-profile.tsv",
			"format": "tsv",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies Arabic NYUAD r2.18 annotations."
			],
			"schemaId": "textdata.syntax-profile.v1"
		},
		{
			"id": "ar-ud-nyuad-annotations",
			"kind": "dataset",
			"path": "resources/ud-nyuad.annotations.tsv",
			"format": "tsv",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies Arabic NYUAD r2.18 annotations."
			],
			"schemaId": "textdata.dataset.v1"
		},
		{
			"id": "ar-ud-nyuad-quality",
			"kind": "quality-profile",
			"path": "resources/ud-nyuad.quality.json",
			"format": "json",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies Arabic NYUAD r2.18 annotations."
			],
			"schemaId": "textquality.evidence.v1"
		},
		{
			"id": "ar-ud-nyuad-syntax-canonical",
			"kind": "grammar",
			"path": "resources/ud-nyuad.syntax.json",
			"format": "json",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies Arabic NYUAD r2.18 annotations."
			],
			"schemaId": "textdata.syntax.v1"
		},
		{
			"id": "ar-ud-nyuad-morphology-canonical",
			"kind": "morphology",
			"path": "resources/ud-nyuad.morphology.json",
			"format": "json",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies Arabic NYUAD r2.18 annotations."
			],
			"schemaId": "textlex.morphology.v1"
		},
		{
			"id": "ar-ud-nyuad-quality-profile",
			"kind": "quality-profile",
			"path": "resources/ud-nyuad.quality-profile.json",
			"format": "json",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies Arabic NYUAD r2.18 annotations."
			],
			"schemaId": "textquality.profile.v1"
		}
	],
	"capabilitySlots": [
		{
			"slot": "tagging",
			"status": "task-supported",
			"resourceIds": [
				"ar-ud-nyuad-upos",
				"ar-ud-nyuad-features",
				"ar-ud-nyuad-annotations",
				"ar-ud-nyuad-morphology-canonical"
			],
			"capabilities": {
				"tagging": "statistical",
				"morphology": "statistical"
			},
			"notes": [
				"Annotation-derived UPOS, XPOS, and morphological feature profiles are available without redistributing LDC text.",
				"This package is share-alike isolated and is not eligible for the default Arabic composite."
			]
		},
		{
			"slot": "syntax",
			"status": "task-supported",
			"resourceIds": [
				"ar-ud-nyuad-dependencies",
				"ar-ud-nyuad-sentence-profile",
				"ar-ud-nyuad-annotations",
				"ar-ud-nyuad-syntax-canonical"
			],
			"notes": [
				"Annotation-derived dependency and sentence profiles are available without redistributing LDC text.",
				"This package is share-alike isolated and is not eligible for the default Arabic composite."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"ar-ud-nyuad-quality",
				"ar-ud-nyuad-quality-profile"
			],
			"notes": [
				"Generated quality profile records annotation counts and confirms no raw text fields are emitted."
			]
		}
	],
	"license": "CC-BY-SA-4.0",
	"citations": [
		"Universal Dependencies Arabic NYUAD r2.18 annotations."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
