// Generated by tools/textpack-forge. Do not edit.

import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import type { PackResourceMap } from "@ismail-elkorchi/textpack";

const resourceRoot = new URL("../resources/", import.meta.url);

async function readResource(
	resourcePath: string,
	encoding: "gzip-base64" | "utf8",
): Promise<string> {
	const text = await readFile(new URL(resourcePath, resourceRoot), "utf8");
	if (encoding === "utf8") return text;
	return gunzipSync(Buffer.from(text.trim(), "base64")).toString("utf8");
}

export async function resources(): Promise<PackResourceMap> {
	// biome-ignore format: generated resource map preserves deterministic resource ordering.
	return {
		"ar-ud-nyuad-upos": await readResource(
			"ud-nyuad.upos.tsv",
			"utf8",
		),
		"ar-ud-nyuad-features": await readResource(
			"ud-nyuad.features.tsv",
			"utf8",
		),
		"ar-ud-nyuad-dependencies": await readResource(
			"ud-nyuad.dependencies.tsv",
			"utf8",
		),
		"ar-ud-nyuad-sentence-profile": await readResource(
			"ud-nyuad.sentence-profile.tsv",
			"utf8",
		),
		"ar-ud-nyuad-annotations": await readResource(
			"ud-nyuad.annotations.tsv",
			"utf8",
		),
		"ar-ud-nyuad-quality": await readResource(
			"ud-nyuad.quality.json",
			"utf8",
		),
		"ar-ud-nyuad-syntax-canonical": await readResource(
			"ud-nyuad.syntax.json",
			"utf8",
		),
		"ar-ud-nyuad-morphology-canonical": await readResource(
			"ud-nyuad.morphology.json",
			"utf8",
		),
		"ar-ud-nyuad-quality-profile": await readResource(
			"ud-nyuad.quality-profile.json",
			"utf8",
		),
	};
}
