// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"ar-ud-nyuad-upos": {"byteLength":40222,"checksum":"sha256:413084a984b08297efb8f408ddee4f981a87adbd9d9ee13a2a2c28670fe924f9","encoding":"utf8","kind":"file-backed-resource","lineCount":1379,"nonEmptyLineCount":1378,"path":"resources/ud-nyuad.upos.tsv","resourceTextByteLength":40222},
	"ar-ud-nyuad-features": {"byteLength":495,"checksum":"sha256:6c94897f1024eba539363416b8644e729e620ba2269a20ba220d79b1638cb593","encoding":"utf8","kind":"file-backed-resource","lineCount":30,"nonEmptyLineCount":29,"path":"resources/ud-nyuad.features.tsv","resourceTextByteLength":495},
	"ar-ud-nyuad-dependencies": {"byteLength":1176,"checksum":"sha256:762087457e838a9b29477d1ade830a7d01654cc1980549841078d268e8b3a558","encoding":"utf8","kind":"file-backed-resource","lineCount":78,"nonEmptyLineCount":77,"path":"resources/ud-nyuad.dependencies.tsv","resourceTextByteLength":1176},
	"ar-ud-nyuad-sentence-profile": {"byteLength":143,"checksum":"sha256:6b342fc2f96e2da2858b6c77ed231cbe858a22604b60099776ebd9f23ab13dac","encoding":"utf8","kind":"file-backed-resource","lineCount":5,"nonEmptyLineCount":4,"path":"resources/ud-nyuad.sentence-profile.tsv","resourceTextByteLength":143},
	"ar-ud-nyuad-annotations": {"byteLength":59041977,"checksum":"sha256:e90c72c7bb9aa9cb5667a6e6b4ced59abe2f1bc98a7cf63be3fd2c414d5cf774","encoding":"utf8","kind":"file-backed-resource","lineCount":738891,"nonEmptyLineCount":738890,"path":"resources/ud-nyuad.annotations.tsv","resourceTextByteLength":59041977},
	"ar-ud-nyuad-quality": {"byteLength":1066,"checksum":"sha256:c858445393c6b017aab3128e043bde6e74225ee7d2b075376daa1f58b8b7a053","encoding":"utf8","kind":"file-backed-resource","lineCount":40,"nonEmptyLineCount":39,"path":"resources/ud-nyuad.quality.json","resourceTextByteLength":1066},
	"ar-ud-nyuad-syntax-canonical": {"byteLength":172617,"checksum":"sha256:a99ba8765205902901e2052297f9ded56375cf318ebe4dda638d140b2cf6a6ae","encoding":"utf8","kind":"file-backed-resource","lineCount":7478,"nonEmptyLineCount":7477,"path":"resources/ud-nyuad.syntax.json","resourceTextByteLength":172617},
	"ar-ud-nyuad-morphology-canonical": {"byteLength":2147,"checksum":"sha256:b02cf6237a33fcab766c8bbcee12e703e47f41e6c29d696129b9fd427a652862","encoding":"utf8","kind":"file-backed-resource","lineCount":136,"nonEmptyLineCount":135,"path":"resources/ud-nyuad.morphology.json","resourceTextByteLength":2147},
	"ar-ud-nyuad-quality-profile": {"byteLength":925,"checksum":"sha256:636213b26ac55c5e312a473b6981265480a081a3dc3ac6aafdb5f72bdfc50639","encoding":"utf8","kind":"file-backed-resource","lineCount":41,"nonEmptyLineCount":40,"path":"resources/ud-nyuad.quality-profile.json","resourceTextByteLength":925},
} as const;
