// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:ar-normalization",
	"name": "Arabic MSA Normalization Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-ar-normalization",
	"targets": {
		"languages": [
			"ar"
		],
		"scripts": [
			"Arab"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "ar-normalization-rules",
			"kind": "normalization-profile",
			"path": "resources/ar.normalization-rules.tsv",
			"format": "tsv",
			"license": "Unicode-3.0 AND CC-BY-4.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-normalization-observed-codepoints",
			"kind": "normalization-profile",
			"path": "resources/ar.normalization-observed-codepoints.tsv",
			"format": "tsv",
			"license": "Unicode-3.0 AND CC-BY-4.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-normalization-profile",
			"kind": "normalization-profile",
			"path": "resources/ar.normalization.json",
			"format": "json",
			"license": "Unicode-3.0 AND CC-BY-4.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"CAMeL Morph MSA LREC-COLING 2024 release."
			],
			"metadata": {
				"canonicalSchema": "textpack-normalization-resource.schema.json"
			}
		},
		{
			"id": "ar-normalization-quality",
			"kind": "quality-profile",
			"path": "resources/ar.normalization.quality.json",
			"format": "json",
			"license": "Unicode-3.0 AND CC-BY-4.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-normalization-quality-profile",
			"kind": "quality-profile",
			"path": "resources/ar.normalization.quality-profile.json",
			"format": "json",
			"license": "Unicode-3.0 AND CC-BY-4.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"CAMeL Morph MSA LREC-COLING 2024 release."
			],
			"metadata": {
				"canonicalSchema": "textpack-quality-profile-resource.schema.json"
			}
		}
	],
	"capabilitySlots": [
		{
			"slot": "normalization",
			"status": "task-supported",
			"resourceIds": [
				"ar-normalization-rules",
				"ar-normalization-observed-codepoints",
				"ar-normalization-profile"
			],
			"capabilities": {
				"normalization": "rules"
			},
			"notes": [
				"Arabic MSA lookup normalization is generated from Unicode/CLDR policy plus CAMeL Morph MSA observed character evidence."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"ar-normalization-quality",
				"ar-normalization-quality-profile"
			],
			"notes": [
				"Generated quality profile records source coverage, rule counts, observed codepoint evidence, accepted records, rejected records, and scope limitations."
			]
		}
	],
	"license": "Unicode-3.0 AND CC-BY-4.0",
	"citations": [
		"Unicode Character Database 17.0.0.",
		"Unicode CLDR core data, cldr-core npm package 48.2.0.",
		"CAMeL Morph MSA LREC-COLING 2024 release."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
