// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"ar-normalization-rules": {"byteLength":1238,"checksum":"sha256:6f774cf6f8c74b95465107f08c5efbd35afe2efcbbe5e46f493217f66bfc840f","encoding":"utf8","kind":"file-backed-resource","lineCount":12,"nonEmptyLineCount":11,"path":"resources/ar.normalization-rules.tsv","resourceTextByteLength":1238},
	"ar-normalization-observed-codepoints": {"byteLength":162,"checksum":"sha256:29d2973b1436014af335788e0e6b98f1f2f699d93be4ec38e23e7311807be094","encoding":"utf8","kind":"file-backed-resource","lineCount":10,"nonEmptyLineCount":9,"path":"resources/ar.normalization-observed-codepoints.tsv","resourceTextByteLength":162},
	"ar-normalization-profile": {"byteLength":5772,"checksum":"sha256:815e26c0aa1d45f19e2fec5893932be98a7d0ecfd71326a6f82330beb9a5d240","encoding":"utf8","kind":"file-backed-resource","lineCount":198,"nonEmptyLineCount":197,"path":"resources/ar.normalization.json","resourceTextByteLength":5772},
	"ar-normalization-quality": {"byteLength":811,"checksum":"sha256:94d1d277a949f8a692671c5f540ed19b80ff5544d793374316fb2b5996577e98","encoding":"utf8","kind":"file-backed-resource","lineCount":25,"nonEmptyLineCount":24,"path":"resources/ar.normalization.quality.json","resourceTextByteLength":811},
	"ar-normalization-quality-profile": {"byteLength":1163,"checksum":"sha256:5affbca0b05411e2868442f1a24dcf1958e4b787cb697c2edbd4a0fb87beb28d","encoding":"utf8","kind":"file-backed-resource","lineCount":46,"nonEmptyLineCount":45,"path":"resources/ar.normalization.quality-profile.json","resourceTextByteLength":1163},
} as const;
