// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:en-parallel",
	"name": "English Tatoeba Parallel Textpack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-en-parallel",
	"targets": {
		"languages": [
			"en"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "en-tatoeba-parallel-ara",
			"kind": "alignment-table",
			"path": "resources/tatoeba-en.parallel-ara.tsv.gz.b64",
			"format": "text/tab-separated-values",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly exports, 2026-06-06."
			]
		},
		{
			"id": "en-tatoeba-parallel-deu",
			"kind": "alignment-table",
			"path": "resources/tatoeba-en.parallel-deu.tsv.gz.b64",
			"format": "text/tab-separated-values",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly exports, 2026-06-06."
			]
		},
		{
			"id": "en-tatoeba-parallel-fra",
			"kind": "alignment-table",
			"path": "resources/tatoeba-en.parallel-fra.tsv.gz.b64",
			"format": "text/tab-separated-values",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly exports, 2026-06-06."
			]
		},
		{
			"id": "en-tatoeba-parallel-spa",
			"kind": "alignment-table",
			"path": "resources/tatoeba-en.parallel-spa.tsv.gz.b64",
			"format": "text/tab-separated-values",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly exports, 2026-06-06."
			]
		},
		{
			"id": "en-tatoeba-parallel-ita",
			"kind": "alignment-table",
			"path": "resources/tatoeba-en.parallel-ita.tsv.gz.b64",
			"format": "text/tab-separated-values",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly exports, 2026-06-06."
			]
		},
		{
			"id": "en-tatoeba-parallel-ell",
			"kind": "alignment-table",
			"path": "resources/tatoeba-en.parallel-ell.tsv.gz.b64",
			"format": "text/tab-separated-values",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly exports, 2026-06-06."
			]
		},
		{
			"id": "en-tatoeba-parallel-grc",
			"kind": "alignment-table",
			"path": "resources/tatoeba-en.parallel-grc.tsv.gz.b64",
			"format": "text/tab-separated-values",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly exports, 2026-06-06."
			]
		},
		{
			"id": "en-tatoeba-parallel-lat",
			"kind": "alignment-table",
			"path": "resources/tatoeba-en.parallel-lat.tsv.gz.b64",
			"format": "text/tab-separated-values",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly exports, 2026-06-06."
			]
		},
		{
			"id": "en-tatoeba-parallel-quality",
			"kind": "quality-profile",
			"path": "resources/tatoeba-en.parallel-quality.json",
			"format": "json",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly exports, 2026-06-06."
			]
		},
		{
			"id": "en-tatoeba-parallel-quality-profile",
			"kind": "quality-profile",
			"path": "resources/tatoeba-en.parallel-quality-profile.json",
			"format": "json",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly exports, 2026-06-06."
			],
			"metadata": {
				"canonicalSchema": "textpack-quality-profile-resource.schema.json"
			}
		}
	],
	"artifacts": [
		{
			"artifactId": "artifact:textpack-en-parallel:full:tatoeba-eng-ara-links:2026-06-06",
			"sourceIds": [
				"source:tatoeba:weekly-2026-06-06"
			],
			"version": "2026-06-06",
			"profile": "full",
			"sizeBytes": 298001,
			"mediaType": "text/tab-separated-values",
			"compression": "bzip2",
			"checksum": {
				"algorithm": "sha256",
				"value": "c48698582a583ea1e259dceacdc4ed663c3f615d846ca7c1fc449397a1d8d3c1"
			},
			"licenseExpression": "CC-BY-2.0-FR",
			"redistributionPolicy": "redistributable-with-attribution",
			"retrieval": {
				"kind": "https",
				"uri": "https://downloads.tatoeba.org/exports/per_language/eng/eng-ara_links.tsv.bz2",
				"instructions": "Fetch explicitly from Tatoeba weekly exports and verify the SHA-256 checksum before unpacking or indexing."
			},
			"cacheKey": "tatoeba-eng-ara-links-tsv-bz2-2026-06-06",
			"expectedFiles": [
				{
					"path": "eng-ara_links.tsv.bz2",
					"sizeBytes": 298001,
					"checksum": "sha256:c48698582a583ea1e259dceacdc4ed663c3f615d846ca7c1fc449397a1d8d3c1"
				}
			]
		},
		{
			"artifactId": "artifact:textpack-en-parallel:full:tatoeba-eng-deu-links:2026-06-06",
			"sourceIds": [
				"source:tatoeba:weekly-2026-06-06"
			],
			"version": "2026-06-06",
			"profile": "full",
			"sizeBytes": 3515460,
			"mediaType": "text/tab-separated-values",
			"compression": "bzip2",
			"checksum": {
				"algorithm": "sha256",
				"value": "7588e11c3088c648fd1a5cf60ca87bd809a08f45d1533f7d52c03174356eb94e"
			},
			"licenseExpression": "CC-BY-2.0-FR",
			"redistributionPolicy": "redistributable-with-attribution",
			"retrieval": {
				"kind": "https",
				"uri": "https://downloads.tatoeba.org/exports/per_language/eng/eng-deu_links.tsv.bz2",
				"instructions": "Fetch explicitly from Tatoeba weekly exports and verify the SHA-256 checksum before unpacking or indexing."
			},
			"cacheKey": "tatoeba-eng-deu-links-tsv-bz2-2026-06-06",
			"expectedFiles": [
				{
					"path": "eng-deu_links.tsv.bz2",
					"sizeBytes": 3515460,
					"checksum": "sha256:7588e11c3088c648fd1a5cf60ca87bd809a08f45d1533f7d52c03174356eb94e"
				}
			]
		},
		{
			"artifactId": "artifact:textpack-en-parallel:full:tatoeba-eng-fra-links:2026-06-06",
			"sourceIds": [
				"source:tatoeba:weekly-2026-06-06"
			],
			"version": "2026-06-06",
			"profile": "full",
			"sizeBytes": 2631564,
			"mediaType": "text/tab-separated-values",
			"compression": "bzip2",
			"checksum": {
				"algorithm": "sha256",
				"value": "b3e2018d6afa03ca9efb11e907674dde519fcb288707ac130d5a1ca61989c23d"
			},
			"licenseExpression": "CC-BY-2.0-FR",
			"redistributionPolicy": "redistributable-with-attribution",
			"retrieval": {
				"kind": "https",
				"uri": "https://downloads.tatoeba.org/exports/per_language/eng/eng-fra_links.tsv.bz2",
				"instructions": "Fetch explicitly from Tatoeba weekly exports and verify the SHA-256 checksum before unpacking or indexing."
			},
			"cacheKey": "tatoeba-eng-fra-links-tsv-bz2-2026-06-06",
			"expectedFiles": [
				{
					"path": "eng-fra_links.tsv.bz2",
					"sizeBytes": 2631564,
					"checksum": "sha256:b3e2018d6afa03ca9efb11e907674dde519fcb288707ac130d5a1ca61989c23d"
				}
			]
		},
		{
			"artifactId": "artifact:textpack-en-parallel:full:tatoeba-eng-spa-links:2026-06-06",
			"sourceIds": [
				"source:tatoeba:weekly-2026-06-06"
			],
			"version": "2026-06-06",
			"profile": "full",
			"sizeBytes": 1750446,
			"mediaType": "text/tab-separated-values",
			"compression": "bzip2",
			"checksum": {
				"algorithm": "sha256",
				"value": "976715308d3d034a1487f056cb95ad6dc9cb67c6a5410bb5c60170366d4c024e"
			},
			"licenseExpression": "CC-BY-2.0-FR",
			"redistributionPolicy": "redistributable-with-attribution",
			"retrieval": {
				"kind": "https",
				"uri": "https://downloads.tatoeba.org/exports/per_language/eng/eng-spa_links.tsv.bz2",
				"instructions": "Fetch explicitly from Tatoeba weekly exports and verify the SHA-256 checksum before unpacking or indexing."
			},
			"cacheKey": "tatoeba-eng-spa-links-tsv-bz2-2026-06-06",
			"expectedFiles": [
				{
					"path": "eng-spa_links.tsv.bz2",
					"sizeBytes": 1750446,
					"checksum": "sha256:976715308d3d034a1487f056cb95ad6dc9cb67c6a5410bb5c60170366d4c024e"
				}
			]
		},
		{
			"artifactId": "artifact:textpack-en-parallel:full:tatoeba-eng-ita-links:2026-06-06",
			"sourceIds": [
				"source:tatoeba:weekly-2026-06-06"
			],
			"version": "2026-06-06",
			"profile": "full",
			"sizeBytes": 3721027,
			"mediaType": "text/tab-separated-values",
			"compression": "bzip2",
			"checksum": {
				"algorithm": "sha256",
				"value": "47187cc3ddc4be8e0083a6a60f683c06e2341d1f459ce067f7dace9dd469ef4f"
			},
			"licenseExpression": "CC-BY-2.0-FR",
			"redistributionPolicy": "redistributable-with-attribution",
			"retrieval": {
				"kind": "https",
				"uri": "https://downloads.tatoeba.org/exports/per_language/eng/eng-ita_links.tsv.bz2",
				"instructions": "Fetch explicitly from Tatoeba weekly exports and verify the SHA-256 checksum before unpacking or indexing."
			},
			"cacheKey": "tatoeba-eng-ita-links-tsv-bz2-2026-06-06",
			"expectedFiles": [
				{
					"path": "eng-ita_links.tsv.bz2",
					"sizeBytes": 3721027,
					"checksum": "sha256:47187cc3ddc4be8e0083a6a60f683c06e2341d1f459ce067f7dace9dd469ef4f"
				}
			]
		},
		{
			"artifactId": "artifact:textpack-en-parallel:full:tatoeba-eng-ell-links:2026-06-06",
			"sourceIds": [
				"source:tatoeba:weekly-2026-06-06"
			],
			"version": "2026-06-06",
			"profile": "full",
			"sizeBytes": 191418,
			"mediaType": "text/tab-separated-values",
			"compression": "bzip2",
			"checksum": {
				"algorithm": "sha256",
				"value": "a711268471634a2b169c824a2fcdab336555d3a2d83a812bf8796ae3fcd8df08"
			},
			"licenseExpression": "CC-BY-2.0-FR",
			"redistributionPolicy": "redistributable-with-attribution",
			"retrieval": {
				"kind": "https",
				"uri": "https://downloads.tatoeba.org/exports/per_language/eng/eng-ell_links.tsv.bz2",
				"instructions": "Fetch explicitly from Tatoeba weekly exports and verify the SHA-256 checksum before unpacking or indexing."
			},
			"cacheKey": "tatoeba-eng-ell-links-tsv-bz2-2026-06-06",
			"expectedFiles": [
				{
					"path": "eng-ell_links.tsv.bz2",
					"sizeBytes": 191418,
					"checksum": "sha256:a711268471634a2b169c824a2fcdab336555d3a2d83a812bf8796ae3fcd8df08"
				}
			]
		},
		{
			"artifactId": "artifact:textpack-en-parallel:full:tatoeba-eng-grc-links:2026-06-06",
			"sourceIds": [
				"source:tatoeba:weekly-2026-06-06"
			],
			"version": "2026-06-06",
			"profile": "full",
			"sizeBytes": 9451,
			"mediaType": "text/tab-separated-values",
			"compression": "bzip2",
			"checksum": {
				"algorithm": "sha256",
				"value": "b9659a219c5d8742257e60ca3876b2ad3869984f4437931f31419456126bada2"
			},
			"licenseExpression": "CC-BY-2.0-FR",
			"redistributionPolicy": "redistributable-with-attribution",
			"retrieval": {
				"kind": "https",
				"uri": "https://downloads.tatoeba.org/exports/per_language/eng/eng-grc_links.tsv.bz2",
				"instructions": "Fetch explicitly from Tatoeba weekly exports and verify the SHA-256 checksum before unpacking or indexing."
			},
			"cacheKey": "tatoeba-eng-grc-links-tsv-bz2-2026-06-06",
			"expectedFiles": [
				{
					"path": "eng-grc_links.tsv.bz2",
					"sizeBytes": 9451,
					"checksum": "sha256:b9659a219c5d8742257e60ca3876b2ad3869984f4437931f31419456126bada2"
				}
			]
		},
		{
			"artifactId": "artifact:textpack-en-parallel:full:tatoeba-eng-lat-links:2026-06-06",
			"sourceIds": [
				"source:tatoeba:weekly-2026-06-06"
			],
			"version": "2026-06-06",
			"profile": "full",
			"sizeBytes": 279658,
			"mediaType": "text/tab-separated-values",
			"compression": "bzip2",
			"checksum": {
				"algorithm": "sha256",
				"value": "83ffb4716016e7b8889b562c3ced046d0b168a8b81954f9994d88bfd83a8e2df"
			},
			"licenseExpression": "CC-BY-2.0-FR",
			"redistributionPolicy": "redistributable-with-attribution",
			"retrieval": {
				"kind": "https",
				"uri": "https://downloads.tatoeba.org/exports/per_language/eng/eng-lat_links.tsv.bz2",
				"instructions": "Fetch explicitly from Tatoeba weekly exports and verify the SHA-256 checksum before unpacking or indexing."
			},
			"cacheKey": "tatoeba-eng-lat-links-tsv-bz2-2026-06-06",
			"expectedFiles": [
				{
					"path": "eng-lat_links.tsv.bz2",
					"sizeBytes": 279658,
					"checksum": "sha256:83ffb4716016e7b8889b562c3ced046d0b168a8b81954f9994d88bfd83a8e2df"
				}
			]
		}
	],
	"capabilitySlots": [
		{
			"slot": "parallel",
			"status": "task-supported",
			"resourceIds": [
				"en-tatoeba-parallel-ara",
				"en-tatoeba-parallel-deu",
				"en-tatoeba-parallel-ell",
				"en-tatoeba-parallel-fra",
				"en-tatoeba-parallel-grc",
				"en-tatoeba-parallel-ita",
				"en-tatoeba-parallel-lat",
				"en-tatoeba-parallel-spa"
			],
			"artifactIds": [
				"artifact:textpack-en-parallel:full:tatoeba-eng-ara-links:2026-06-06",
				"artifact:textpack-en-parallel:full:tatoeba-eng-deu-links:2026-06-06",
				"artifact:textpack-en-parallel:full:tatoeba-eng-ell-links:2026-06-06",
				"artifact:textpack-en-parallel:full:tatoeba-eng-fra-links:2026-06-06",
				"artifact:textpack-en-parallel:full:tatoeba-eng-grc-links:2026-06-06",
				"artifact:textpack-en-parallel:full:tatoeba-eng-ita-links:2026-06-06",
				"artifact:textpack-en-parallel:full:tatoeba-eng-lat-links:2026-06-06",
				"artifact:textpack-en-parallel:full:tatoeba-eng-spa-links:2026-06-06"
			],
			"capabilities": {
				"parallel": true
			},
			"notes": [
				"Tatoeba English-linked sentence-id alignment rows are materialized locally as canonical TSV from verified 2026-06-06 source artifacts.",
				"Sentence text must be resolved from compatible Tatoeba sentence resources when a caller needs bilingual text pairs rather than ID alignments."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"en-tatoeba-parallel-quality",
				"en-tatoeba-parallel-quality-profile"
			],
			"notes": [
				"Generated quality profile records local link row counts, source checksum evidence, transform acceptance, and language-pair coverage."
			]
		}
	],
	"license": "CC-BY-2.0-FR",
	"citations": [
		"Tatoeba weekly exports, 2026-06-06."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
