// Generated by tools/textpack-forge. Do not edit.

import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import type { PackResourceMap } from "@ismail-elkorchi/textpack";

const resourceRoot = new URL("../resources/", import.meta.url);

async function readResource(
	resourcePath: string,
	encoding: "gzip-base64" | "utf8",
): Promise<string> {
	const text = await readFile(new URL(resourcePath, resourceRoot), "utf8");
	if (encoding === "utf8") return text;
	return gunzipSync(Buffer.from(text.trim(), "base64")).toString("utf8");
}

export async function resources(): Promise<PackResourceMap> {
	// biome-ignore format: generated resource map preserves deterministic resource ordering.
	return {
		"en-tatoeba-parallel-ara": await readResource(
			"tatoeba-en.parallel-ara.tsv.gz.b64",
			"gzip-base64",
		),
		"en-tatoeba-parallel-deu": await readResource(
			"tatoeba-en.parallel-deu.tsv.gz.b64",
			"gzip-base64",
		),
		"en-tatoeba-parallel-fra": await readResource(
			"tatoeba-en.parallel-fra.tsv.gz.b64",
			"gzip-base64",
		),
		"en-tatoeba-parallel-spa": await readResource(
			"tatoeba-en.parallel-spa.tsv.gz.b64",
			"gzip-base64",
		),
		"en-tatoeba-parallel-ita": await readResource(
			"tatoeba-en.parallel-ita.tsv.gz.b64",
			"gzip-base64",
		),
		"en-tatoeba-parallel-ell": await readResource(
			"tatoeba-en.parallel-ell.tsv.gz.b64",
			"gzip-base64",
		),
		"en-tatoeba-parallel-grc": await readResource(
			"tatoeba-en.parallel-grc.tsv.gz.b64",
			"gzip-base64",
		),
		"en-tatoeba-parallel-lat": await readResource(
			"tatoeba-en.parallel-lat.tsv.gz.b64",
			"gzip-base64",
		),
		"en-tatoeba-parallel-quality": await readResource(
			"tatoeba-en.parallel-quality.json",
			"utf8",
		),
		"en-tatoeba-parallel-quality-profile": await readResource(
			"tatoeba-en.parallel-quality-profile.json",
			"utf8",
		),
	};
}
