// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"wikidata-ar-entities": {"byteLength":134633,"checksum":"sha256:bfde77b44f2a2180da72bb9bc8874fb85262a69f25275b218fd71937a101181f","encoding":"gzip-base64","kind":"file-backed-resource","lineCount":3011,"nonEmptyLineCount":3010,"path":"resources/wikidata-ar.entities.tsv.gz.b64","resourceTextByteLength":601528},
	"wikidata-ar-aliases": {"byteLength":35629,"checksum":"sha256:ddf27c30b153ee9e4941a438ec96cce399f7f335ed270442090b10bdb1b365c8","encoding":"gzip-base64","kind":"file-backed-resource","lineCount":2778,"nonEmptyLineCount":2777,"path":"resources/wikidata-ar.aliases.tsv.gz.b64","resourceTextByteLength":176372},
	"wikidata-ar-relations": {"byteLength":16457,"checksum":"sha256:e9b2117bec25186e241f1b68347caf2b2fce8d7ed95e6c4e9344adaf04bd7d9a","encoding":"gzip-base64","kind":"file-backed-resource","lineCount":3011,"nonEmptyLineCount":3010,"path":"resources/wikidata-ar.relations.tsv.gz.b64","resourceTextByteLength":181451},
	"wikidata-ar-kb-canonical": {"byteLength":523,"checksum":"sha256:bb58bdd4440a0884b24b4f0189a8e4f31a01d36c235ed253536e0341a905335b","encoding":"utf8","kind":"file-backed-resource","lineCount":28,"nonEmptyLineCount":27,"path":"resources/wikidata-ar.kb.json","resourceTextByteLength":523},
	"wikidata-ar-quality": {"byteLength":968,"checksum":"sha256:6b18694e3b24875a4b6268fbeb71ed978d17327b455e38d443124d801219dd40","encoding":"utf8","kind":"file-backed-resource","lineCount":27,"nonEmptyLineCount":26,"path":"resources/wikidata-ar.quality.json","resourceTextByteLength":968},
	"wikidata-ar-quality-profile": {"byteLength":2789,"checksum":"sha256:688883a208a912f996fef965c46d04720e4494295003542ed1cbc48d3601050d","encoding":"utf8","kind":"file-backed-resource","lineCount":102,"nonEmptyLineCount":101,"path":"resources/wikidata-ar.quality-profile.json","resourceTextByteLength":2789},
} as const;
