// Generated by tools/textpack-forge. Do not edit.

import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import type { PackResourceMap } from "@ismail-elkorchi/textpack";

const resourceRoot = new URL("../resources/", import.meta.url);

async function readResource(
	resourcePath: string,
	encoding: "gzip-base64" | "utf8",
): Promise<string> {
	const text = await readFile(new URL(resourcePath, resourceRoot), "utf8");
	if (encoding === "utf8") return text;
	return gunzipSync(Buffer.from(text.trim(), "base64")).toString("utf8");
}

export async function resources(): Promise<PackResourceMap> {
	// biome-ignore format: generated resource map preserves deterministic resource ordering.
	return {
		"en-scowl-inflection-entries": await readResource(
			"scowl-v2.inflections.tsv.gz.b64",
			"gzip-base64",
		),
		"en-scowl-pos-inventory": await readResource(
			"scowl-v2.pos.tsv",
			"utf8",
		),
		"en-scowl-lookup-analyzer": await readResource(
			"scowl-v2.lookup-analyzer.tsv.gz.b64",
			"gzip-base64",
		),
		"en-scowl-lookup-generator": await readResource(
			"scowl-v2.lookup-generator.tsv.gz.b64",
			"gzip-base64",
		),
		"en-scowl-inflection-lexicon-canonical": await readResource(
			"scowl-v2.lexicon.json",
			"utf8",
		),
		"en-scowl-inflection-morphology-canonical": await readResource(
			"scowl-v2.morphology.json",
			"utf8",
		),
		"en-scowl-inflection-quality": await readResource(
			"scowl-v2.quality.json",
			"utf8",
		),
		"en-scowl-inflection-quality-profile": await readResource(
			"scowl-v2.quality-profile.json",
			"utf8",
		),
	};
}
