// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"en-scowl-inflection-entries": {"byteLength":7328209,"checksum":"sha256:2aff974f56754dc4190f7c9d79084efac7a8ddfd1be566d9084b47c61213d7d8","encoding":"gzip-base64","kind":"file-backed-resource","lineCount":401711,"nonEmptyLineCount":401710,"path":"resources/scowl-v2.inflections.tsv.gz.b64","resourceTextByteLength":33487594},
	"en-scowl-pos-inventory": {"byteLength":1953,"checksum":"sha256:0235931224b8488aa53ba2008d02dff457301d7e2a586ed82f6b55de09e59e3c","encoding":"utf8","kind":"file-backed-resource","lineCount":105,"nonEmptyLineCount":104,"path":"resources/scowl-v2.pos.tsv","resourceTextByteLength":1953},
	"en-scowl-lookup-analyzer": {"byteLength":5129709,"checksum":"sha256:bf0b7f4d223444618a650ae5ff9f908099590776c0895b0b6ddfd32bec22c15c","encoding":"gzip-base64","kind":"file-backed-resource","lineCount":401711,"nonEmptyLineCount":401710,"path":"resources/scowl-v2.lookup-analyzer.tsv.gz.b64","resourceTextByteLength":22622235},
	"en-scowl-lookup-generator": {"byteLength":4819189,"checksum":"sha256:771f858c850bca4e3e1018ea2b053d22735658f63ecf827c5c79948d1df3c079","encoding":"gzip-base64","kind":"file-backed-resource","lineCount":401711,"nonEmptyLineCount":401710,"path":"resources/scowl-v2.lookup-generator.tsv.gz.b64","resourceTextByteLength":22622235},
	"en-scowl-inflection-lexicon-canonical": {"byteLength":412,"checksum":"sha256:434af7796427f70752f91a1952078f1faff44440693669097ba7249934059007","encoding":"utf8","kind":"file-backed-resource","lineCount":21,"nonEmptyLineCount":20,"path":"resources/scowl-v2.lexicon.json","resourceTextByteLength":412},
	"en-scowl-inflection-morphology-canonical": {"byteLength":1856,"checksum":"sha256:546c40de190116857b21e009974063ae9b28d09980153cb7d2c42d04020708ca","encoding":"utf8","kind":"file-backed-resource","lineCount":97,"nonEmptyLineCount":96,"path":"resources/scowl-v2.morphology.json","resourceTextByteLength":1856},
	"en-scowl-inflection-quality": {"byteLength":842,"checksum":"sha256:322086f21d57e011b7c51faaf8da127a5410d2f1b0339d6ce046732af8c063f5","encoding":"utf8","kind":"file-backed-resource","lineCount":24,"nonEmptyLineCount":23,"path":"resources/scowl-v2.quality.json","resourceTextByteLength":842},
	"en-scowl-inflection-quality-profile": {"byteLength":1079,"checksum":"sha256:5ab60db572325548aaee12a4d3055b52f251f65a7bafb1831b7e968cd0210fde","encoding":"utf8","kind":"file-backed-resource","lineCount":47,"nonEmptyLineCount":46,"path":"resources/scowl-v2.quality-profile.json","resourceTextByteLength":1079},
} as const;
