// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:ar-parallel",
	"name": "Arabic Tatoeba Parallel Artifact Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-ar-parallel",
	"targets": {
		"languages": [
			"ar"
		],
		"scripts": [
			"Arab"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "ar-tatoeba-parallel-eng",
			"kind": "alignment-table",
			"path": "resources/tatoeba-ar.parallel-eng.json",
			"format": "json",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly Arabic exports, 2026-06-06."
			],
			"metadata": {
				"canonicalSchema": "textpack-parallel-resource.schema.json"
			}
		},
		{
			"id": "ar-tatoeba-parallel-fra",
			"kind": "alignment-table",
			"path": "resources/tatoeba-ar.parallel-fra.json",
			"format": "json",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly Arabic exports, 2026-06-06."
			],
			"metadata": {
				"canonicalSchema": "textpack-parallel-resource.schema.json"
			}
		},
		{
			"id": "ar-tatoeba-parallel-spa",
			"kind": "alignment-table",
			"path": "resources/tatoeba-ar.parallel-spa.json",
			"format": "json",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly Arabic exports, 2026-06-06."
			],
			"metadata": {
				"canonicalSchema": "textpack-parallel-resource.schema.json"
			}
		},
		{
			"id": "ar-tatoeba-parallel-deu",
			"kind": "alignment-table",
			"path": "resources/tatoeba-ar.parallel-deu.json",
			"format": "json",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly Arabic exports, 2026-06-06."
			],
			"metadata": {
				"canonicalSchema": "textpack-parallel-resource.schema.json"
			}
		},
		{
			"id": "ar-tatoeba-parallel-quality",
			"kind": "quality-profile",
			"path": "resources/tatoeba-ar.parallel-quality.json",
			"format": "json",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly Arabic exports, 2026-06-06."
			]
		},
		{
			"id": "ar-tatoeba-parallel-quality-profile",
			"kind": "quality-profile",
			"path": "resources/tatoeba-ar.parallel-quality-profile.json",
			"format": "json",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly Arabic exports, 2026-06-06."
			],
			"metadata": {
				"canonicalSchema": "textpack-quality-profile-resource.schema.json"
			}
		}
	],
	"artifacts": [
		{
			"artifactId": "artifact:textpack-ar-parallel:full:tatoeba-ara-eng-links:2026-06-06",
			"sourceIds": [
				"source:tatoeba:weekly-arabic-2026-06-06"
			],
			"version": "2026-06-06",
			"profile": "full",
			"sizeBytes": 297959,
			"mediaType": "text/tab-separated-values",
			"compression": "bzip2",
			"checksum": {
				"algorithm": "sha256",
				"value": "e053b397b50ff0f622b6104b62e4939658e876fccdaffa8f5b29fcce98800d83"
			},
			"licenseExpression": "CC-BY-2.0-FR",
			"redistributionPolicy": "redistributable-with-attribution",
			"retrieval": {
				"kind": "https",
				"uri": "https://downloads.tatoeba.org/exports/per_language/ara/ara-eng_links.tsv.bz2",
				"instructions": "Fetch explicitly from Tatoeba weekly exports and verify the SHA-256 checksum before unpacking or indexing."
			},
			"cacheKey": "tatoeba-ara-eng-links-tsv-bz2-2026-06-06",
			"expectedFiles": [
				{
					"path": "ara-eng_links.tsv.bz2",
					"sizeBytes": 297959,
					"checksum": "sha256:e053b397b50ff0f622b6104b62e4939658e876fccdaffa8f5b29fcce98800d83"
				}
			]
		},
		{
			"artifactId": "artifact:textpack-ar-parallel:full:tatoeba-ara-fra-links:2026-06-06",
			"sourceIds": [
				"source:tatoeba:weekly-arabic-2026-06-06"
			],
			"version": "2026-06-06",
			"profile": "full",
			"sizeBytes": 19407,
			"mediaType": "text/tab-separated-values",
			"compression": "bzip2",
			"checksum": {
				"algorithm": "sha256",
				"value": "1d465582dd31e7cf73fabc86df8c595340d98f76b8ca8dacddd4f15a26e9d947"
			},
			"licenseExpression": "CC-BY-2.0-FR",
			"redistributionPolicy": "redistributable-with-attribution",
			"retrieval": {
				"kind": "https",
				"uri": "https://downloads.tatoeba.org/exports/per_language/ara/ara-fra_links.tsv.bz2",
				"instructions": "Fetch explicitly from Tatoeba weekly exports and verify the SHA-256 checksum before unpacking or indexing."
			},
			"cacheKey": "tatoeba-ara-fra-links-tsv-bz2-2026-06-06",
			"expectedFiles": [
				{
					"path": "ara-fra_links.tsv.bz2",
					"sizeBytes": 19407,
					"checksum": "sha256:1d465582dd31e7cf73fabc86df8c595340d98f76b8ca8dacddd4f15a26e9d947"
				}
			]
		},
		{
			"artifactId": "artifact:textpack-ar-parallel:full:tatoeba-ara-spa-links:2026-06-06",
			"sourceIds": [
				"source:tatoeba:weekly-arabic-2026-06-06"
			],
			"version": "2026-06-06",
			"profile": "full",
			"sizeBytes": 21075,
			"mediaType": "text/tab-separated-values",
			"compression": "bzip2",
			"checksum": {
				"algorithm": "sha256",
				"value": "45620b4d7e1b2ddfae38b95b060d557940c10dd3c16055e870dd92720d3019bc"
			},
			"licenseExpression": "CC-BY-2.0-FR",
			"redistributionPolicy": "redistributable-with-attribution",
			"retrieval": {
				"kind": "https",
				"uri": "https://downloads.tatoeba.org/exports/per_language/ara/ara-spa_links.tsv.bz2",
				"instructions": "Fetch explicitly from Tatoeba weekly exports and verify the SHA-256 checksum before unpacking or indexing."
			},
			"cacheKey": "tatoeba-ara-spa-links-tsv-bz2-2026-06-06",
			"expectedFiles": [
				{
					"path": "ara-spa_links.tsv.bz2",
					"sizeBytes": 21075,
					"checksum": "sha256:45620b4d7e1b2ddfae38b95b060d557940c10dd3c16055e870dd92720d3019bc"
				}
			]
		},
		{
			"artifactId": "artifact:textpack-ar-parallel:full:tatoeba-ara-deu-links:2026-06-06",
			"sourceIds": [
				"source:tatoeba:weekly-arabic-2026-06-06"
			],
			"version": "2026-06-06",
			"profile": "full",
			"sizeBytes": 18446,
			"mediaType": "text/tab-separated-values",
			"compression": "bzip2",
			"checksum": {
				"algorithm": "sha256",
				"value": "63c69fb6b074f918126f47e532dd3e6bd4aad35e2fad62708c0d468f58a8d124"
			},
			"licenseExpression": "CC-BY-2.0-FR",
			"redistributionPolicy": "redistributable-with-attribution",
			"retrieval": {
				"kind": "https",
				"uri": "https://downloads.tatoeba.org/exports/per_language/ara/ara-deu_links.tsv.bz2",
				"instructions": "Fetch explicitly from Tatoeba weekly exports and verify the SHA-256 checksum before unpacking or indexing."
			},
			"cacheKey": "tatoeba-ara-deu-links-tsv-bz2-2026-06-06",
			"expectedFiles": [
				{
					"path": "ara-deu_links.tsv.bz2",
					"sizeBytes": 18446,
					"checksum": "sha256:63c69fb6b074f918126f47e532dd3e6bd4aad35e2fad62708c0d468f58a8d124"
				}
			]
		}
	],
	"capabilitySlots": [
		{
			"slot": "parallel",
			"status": "task-supported",
			"resourceIds": [
				"ar-tatoeba-parallel-eng",
				"ar-tatoeba-parallel-fra",
				"ar-tatoeba-parallel-spa",
				"ar-tatoeba-parallel-deu"
			],
			"artifactIds": [
				"artifact:textpack-ar-parallel:full:tatoeba-ara-eng-links:2026-06-06",
				"artifact:textpack-ar-parallel:full:tatoeba-ara-fra-links:2026-06-06",
				"artifact:textpack-ar-parallel:full:tatoeba-ara-spa-links:2026-06-06",
				"artifact:textpack-ar-parallel:full:tatoeba-ara-deu-links:2026-06-06"
			],
			"capabilities": {
				"parallel": true
			},
			"notes": [
				"Tatoeba Arabic-linked alignment tables are available through explicit full artifact descriptors for English, French, Spanish, and German."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"ar-tatoeba-parallel-quality",
				"ar-tatoeba-parallel-quality-profile"
			],
			"notes": [
				"Generated quality profile records language-pair count, link row count, artifact sizes, checksum evidence, and explicit fetch limitations."
			]
		}
	],
	"license": "CC-BY-2.0-FR",
	"citations": [
		"Tatoeba weekly Arabic exports, 2026-06-06."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
