// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"en-tatoeba-corpus-sentences": {"byteLength": 64521961,"checksum": "sha256:0128b2b5da9034e745a093c886f393fa6d17402f0d768b80b57ff2d89da5a350","encoding": "gzip-base64","kind": "file-backed-resource","lineCount": 2028857,"nonEmptyLineCount": 2028856,"packageName": "@ismail-elkorchi/textpack-en-corpus","packageRoot": new URL("../", import.meta.url).href,"path": "resources/tatoeba-en.sentences.tsv.gz.b64","resourceTextByteLength": 203768554},
	"en-tatoeba-corpus-canonical": {"byteLength": 1111,"checksum": "sha256:4d40aeee3ad15448b80c68182eddbd4f8ebaacd9b5bbe6e36cb11db527548c07","encoding": "utf8","kind": "file-backed-resource","lineCount": 34,"nonEmptyLineCount": 33,"packageName": "@ismail-elkorchi/textpack-en-corpus","packageRoot": new URL("../", import.meta.url).href,"path": "resources/tatoeba-en.corpus.json","resourceTextByteLength": 1111},
	"en-tatoeba-corpus-quality": {"byteLength": 896,"checksum": "sha256:4d9416ec737ac55c72af18b3d0218001328284f31d76d32ad128565db8d1c1eb","encoding": "utf8","kind": "file-backed-resource","lineCount": 21,"nonEmptyLineCount": 20,"packageName": "@ismail-elkorchi/textpack-en-corpus","packageRoot": new URL("../", import.meta.url).href,"path": "resources/tatoeba-en.corpus-quality.json","resourceTextByteLength": 896},
	"en-tatoeba-corpus-quality-profile": {"byteLength": 1347,"checksum": "sha256:673c4873ff7eea8142d4712b3c34f8d97e69fc8f356935f04378c2e80956b85b","encoding": "utf8","kind": "file-backed-resource","lineCount": 46,"nonEmptyLineCount": 45,"packageName": "@ismail-elkorchi/textpack-en-corpus","packageRoot": new URL("../", import.meta.url).href,"path": "resources/tatoeba-en.corpus-quality-profile.json","resourceTextByteLength": 1347},
} as const;
