// Generated by tools/textpack-forge. Do not edit.

import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import type { PackResourceMap } from "@ismail-elkorchi/textpack";

const resourceRoot = new URL("../resources/", import.meta.url);

async function readResource(
	resourcePath: string,
	encoding: "gzip-base64" | "utf8",
): Promise<string> {
	const text = await readFile(new URL(resourcePath, resourceRoot), "utf8");
	if (encoding === "utf8") return text;
	return gunzipSync(Buffer.from(text.trim(), "base64")).toString("utf8");
}

export async function resources(): Promise<PackResourceMap> {
	// biome-ignore format: generated resource map preserves deterministic resource ordering.
	return {
		"en-esdb-default-wordlists": await readResource(
			"esdb-2026.default-wordlists.tsv.gz.b64",
			"gzip-base64",
		),
		"en-esdb-default-profiles": await readResource(
			"esdb-2026.default-profiles.tsv",
			"utf8",
		),
		"en-esdb-wordlist-lexicon-canonical": await readResource(
			"esdb-2026.lexicon.json",
			"utf8",
		),
		"en-esdb-wordlist-search-profile": await readResource(
			"esdb-2026.search-profile.json",
			"utf8",
		),
		"en-esdb-wordlist-quality": await readResource(
			"esdb-2026.quality.json",
			"utf8",
		),
		"en-esdb-wordlist-quality-profile": await readResource(
			"esdb-2026.quality-profile.json",
			"utf8",
		),
	};
}
