// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:wikidata-en",
	"name": "Wikidata English Entity Artifact Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-wikidata-en",
	"targets": {
		"languages": [
			"en"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "wikidata-en-kb-artifact",
			"kind": "knowledge-base",
			"path": "resources/wikidata-en.kb-artifact.json",
			"format": "json",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08."
			],
			"metadata": {
				"canonicalSchema": "textpack-kb-resource.schema.json"
			}
		},
		{
			"id": "wikidata-en-quality",
			"kind": "quality-profile",
			"path": "resources/wikidata-en.quality.json",
			"format": "json",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08."
			]
		},
		{
			"id": "wikidata-en-quality-profile",
			"kind": "quality-profile",
			"path": "resources/wikidata-en.quality-profile.json",
			"format": "json",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08."
			],
			"metadata": {
				"canonicalSchema": "textpack-quality-profile-resource.schema.json"
			}
		}
	],
	"artifacts": [
		{
			"artifactId": "artifact:textpack-wikidata-en:full:wikidata-entities-json:20260608",
			"sourceIds": [
				"source:wikidata:main"
			],
			"version": "20260608",
			"profile": "full",
			"sizeBytes": 142291512349,
			"mediaType": "application/json",
			"compression": "gzip",
			"checksum": {
				"algorithm": "sha1",
				"value": "7a1165f121e50eca8f2e11674971d7f2d3c47b98"
			},
			"licenseExpression": "CC0-1.0",
			"redistributionPolicy": "redistributable",
			"retrieval": {
				"kind": "https",
				"uri": "https://dumps.wikimedia.org/wikidatawiki/entities/20260608/wikidata-20260608-all.json.gz",
				"instructions": "Fetch explicitly and verify against the upstream SHA-1 checksum sidecar before unpacking or indexing."
			},
			"cacheKey": "wikidata-main-20260608-all-json-gzip",
			"expectedFiles": [
				{
					"path": "wikidata-20260608-all.json.gz",
					"sizeBytes": 142291512349,
					"checksum": "sha1:7a1165f121e50eca8f2e11674971d7f2d3c47b98"
				}
			]
		}
	],
	"capabilitySlots": [
		{
			"slot": "kb",
			"status": "artifact-backed",
			"resourceIds": [
				"wikidata-en-kb-artifact"
			],
			"artifactIds": [
				"artifact:textpack-wikidata-en:full:wikidata-entities-json:20260608"
			],
			"capabilities": {
				"terminology": "kb",
				"extraction": "gazetteer"
			},
			"notes": [
				"Wikidata main entity labels, aliases, relations, and ontology data are available through an explicit artifact descriptor.",
				"Descriptor-only artifact metadata does not satisfy task-supported readiness until local generated rows, extracts, indexes, or databases are materialized."
			]
		},
		{
			"slot": "quality",
			"status": "artifact-backed",
			"resourceIds": [
				"wikidata-en-quality",
				"wikidata-en-quality-profile"
			],
			"notes": [
				"Generated quality profile records artifact size, upstream checksum sidecar evidence, and local materialization limitations.",
				"Descriptor-only artifact metadata does not satisfy task-supported readiness until local generated rows, extracts, indexes, or databases are materialized."
			]
		}
	],
	"license": "CC0-1.0",
	"citations": [
		"Wikidata main structured data dump, 2026-06-08."
	],
	"gapNotes": [
		{
			"id": "gap:pack:wikidata-en:kb",
			"slot": "kb",
			"status": "artifact-backed",
			"message": "kb is artifact-backed in this source-backed concrete pack."
		},
		{
			"id": "gap:pack:wikidata-en:quality",
			"slot": "quality",
			"status": "artifact-backed",
			"message": "quality is artifact-backed in this source-backed concrete pack."
		}
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
