// Generated by tools/textpack-forge. Do not edit.

import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import type { PackResourceMap } from "@ismail-elkorchi/textpack";

const resourceRoot = new URL("../resources/", import.meta.url);

async function readResource(
	resourcePath: string,
	encoding: "gzip-base64" | "utf8",
): Promise<string> {
	const text = await readFile(new URL(resourcePath, resourceRoot), "utf8");
	if (encoding === "utf8") return text;
	return gunzipSync(Buffer.from(text.trim(), "base64")).toString("utf8");
}

export async function resources(): Promise<PackResourceMap> {
	// biome-ignore format: generated resource map preserves deterministic resource ordering.
	return {
		"wikidata-en-entities": await readResource(
			"wikidata-en.entities.tsv.gz.b64",
			"gzip-base64",
		),
		"wikidata-en-aliases": await readResource(
			"wikidata-en.aliases.tsv.gz.b64",
			"gzip-base64",
		),
		"wikidata-en-relations": await readResource(
			"wikidata-en.relations.tsv.gz.b64",
			"gzip-base64",
		),
		"wikidata-en-kb-canonical": await readResource(
			"wikidata-en.kb.json",
			"utf8",
		),
		"wikidata-en-quality": await readResource(
			"wikidata-en.quality.json",
			"utf8",
		),
		"wikidata-en-quality-profile": await readResource(
			"wikidata-en.quality-profile.json",
			"utf8",
		),
	};
}
