export type {
	AliasEntry,
	AliasEntryInput,
	AliasIndex,
	BuildAliasIndexInput,
	CandidateOptions,
	CohesionFeatures,
	ConceptCandidate,
	ConceptRecord,
	ConceptRecordStore,
	CreateKnowledgeBaseOptions,
	DisambiguationFeatures,
	DisambiguationWeights,
	EntityCandidate,
	EntityLinkOptions,
	EntityLinkValue,
	EntityRecord,
	EntityRecordStore,
	EntityRowParseOptions,
	GazetteerOptions,
	JsonObject,
	JsonPrimitive,
	JsonValue,
	KbDiagnostic,
	KbDiagnosticSeverity,
	KbGazetteerMatch,
	KbTargetKind,
	KnowledgeBase,
	LexicalChain,
	LexicalChainOptions,
	PackageName,
	RelationDirection,
	SemanticRelation,
	SemanticRelationPath,
	SemanticRelationQuery,
	SemanticRelationStore,
	SemanticRelationStoreOptions,
	SenseCandidate,
	SenseLinkValue,
	SenseOptions,
	SenseRecord,
	SenseRecordStore,
	SourceMapping,
	TermLinkOptions,
	TermLinkValue,
	TraverseSemanticRelationsOptions,
} from "./internal/core.js";
export {
	annotateOntologyGazetteer,
	assertJsonObject,
	assertJsonValue,
	buildAliasIndex,
	candidateConcepts,
	candidateEntities,
	candidateSenses,
	cohesionFeatures,
	createConceptRecordStore,
	createEntityRecordStore,
	createKnowledgeBase,
	createSemanticRelationStore,
	createSenseRecordStore,
	disambiguateSense,
	explainCandidate,
	explainRelationPath,
	lexicalChains,
	linkEntities,
	linkTerms,
	ontologyGazetteer,
	packageName,
	parseAliasRows,
	parseEntityRows,
	parseRelationRows,
	querySemanticRelations,
	scoreDisambiguation,
	scoreValue,
	standardSemanticRelationTypes,
	TextKbError,
	thesaurusRelations,
	traverseSemanticRelations,
} from "./internal/core.js";
export type {
	WikidataAliasRecord,
	WikidataEntityRecord,
	WikidataPackOptions,
	WikidataPackResources,
	WikidataRelationRecord,
	WikidataResourceIds,
} from "./wikidata/mod.js";
export { wikidataResourcesFromPack } from "./wikidata/mod.js";
export type {
	WordNetLexicalEntryRecord,
	WordNetPackOptions,
	WordNetPackResources,
	WordNetRelationRecord,
	WordNetResourceIds,
	WordNetSenseRecord,
	WordNetSynsetRecord,
} from "./wordnet/mod.js";
export {
	openEnglishWordNetFromPack,
	openEnglishWordNetFromPackAsync,
	wordNetResourcesFromPack,
	wordNetResourcesFromPackAsync,
} from "./wordnet/mod.js";
