// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"wordnet-en-lexical-entries": {"byteLength":4202454,"checksum":"sha256:43df93cb052d566573982948efeedcae2ed4e2a18a3d3e16134a37790dfb9426","encoding":"utf8","kind":"file-backed-resource","lineCount":135971,"nonEmptyLineCount":135970,"path":"resources/wordnet-en.lexical-entries.tsv","resourceTextByteLength":4202454},
	"wordnet-en-senses": {"byteLength":13790166,"checksum":"sha256:8ca27118c686b1aea8a61d75a9bf52262c48b4999e4965b2d52c44031130fced","encoding":"utf8","kind":"file-backed-resource","lineCount":185131,"nonEmptyLineCount":185130,"path":"resources/wordnet-en.senses.tsv","resourceTextByteLength":13790166},
	"wordnet-en-synsets": {"byteLength":13924959,"checksum":"sha256:721406f066db96e780b50f31fabd476446a5f7d2e3420690fd479451ed36d255","encoding":"utf8","kind":"file-backed-resource","lineCount":107521,"nonEmptyLineCount":107520,"path":"resources/wordnet-en.synsets.tsv","resourceTextByteLength":13924959},
	"wordnet-en-relations": {"byteLength":19570884,"checksum":"sha256:fcf45d3d2ddeb3350ae18f50087387635369d8807e109bb1b30fa07ab1969ed6","encoding":"utf8","kind":"file-backed-resource","lineCount":355066,"nonEmptyLineCount":355065,"path":"resources/wordnet-en.relations.tsv","resourceTextByteLength":19570884},
	"wordnet-en-quality": {"byteLength":1401,"checksum":"sha256:c20aa32a35394b476849490164227ba64237489bbc3de36498e50d146095db94","encoding":"utf8","kind":"file-backed-resource","lineCount":54,"nonEmptyLineCount":53,"path":"resources/wordnet-en.quality.json","resourceTextByteLength":1401},
	"wordnet-en-lexicon-canonical": {"byteLength":292,"checksum":"sha256:938ab3964d5732e9517cb77d63372be6c91423343bcf417ebb980485743543e4","encoding":"utf8","kind":"file-backed-resource","lineCount":16,"nonEmptyLineCount":15,"path":"resources/wordnet-en.lexicon.json","resourceTextByteLength":292},
	"wordnet-en-kb-canonical": {"byteLength":518,"checksum":"sha256:4d2e5c099d1a5959f45818e4c315afba95d1719bb2396833377d5dc1905f0ba8","encoding":"utf8","kind":"file-backed-resource","lineCount":28,"nonEmptyLineCount":27,"path":"resources/wordnet-en.kb.json","resourceTextByteLength":518},
	"wordnet-en-quality-profile": {"byteLength":876,"checksum":"sha256:681ae437d9d4b42caa837baedd35a08c5930d45b99ecc4059a75ba3b636ac6a8","encoding":"utf8","kind":"file-backed-resource","lineCount":41,"nonEmptyLineCount":40,"path":"resources/wordnet-en.quality-profile.json","resourceTextByteLength":876},
} as const;
