// Generated by tools/textpack-forge. Do not edit.

import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import type { PackResourceMap } from "@ismail-elkorchi/textpack";

const resourceRoot = new URL("../resources/", import.meta.url);

async function readResource(
	resourcePath: string,
	encoding: "gzip-base64" | "utf8",
): Promise<string> {
	const text = await readFile(new URL(resourcePath, resourceRoot), "utf8");
	if (encoding === "utf8") return text;
	return gunzipSync(Buffer.from(text.trim(), "base64")).toString("utf8");
}

export async function resources(): Promise<PackResourceMap> {
	// biome-ignore format: generated resource map preserves deterministic resource ordering.
	return {
		"wordnet-en-lexical-entries": await readResource(
			"wordnet-en.lexical-entries.tsv",
			"utf8",
		),
		"wordnet-en-senses": await readResource(
			"wordnet-en.senses.tsv",
			"utf8",
		),
		"wordnet-en-synsets": await readResource(
			"wordnet-en.synsets.tsv",
			"utf8",
		),
		"wordnet-en-relations": await readResource(
			"wordnet-en.relations.tsv",
			"utf8",
		),
		"wordnet-en-quality": await readResource(
			"wordnet-en.quality.json",
			"utf8",
		),
	};
}
