// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:unicode-17",
	"name": "Unicode 17 Foundation Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-unicode-17",
	"targets": {
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "unicode-17-blocks",
			"kind": "unicode-profile",
			"path": "resources/unicode-17.blocks.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			]
		},
		{
			"id": "unicode-17-property-value-aliases",
			"kind": "unicode-profile",
			"path": "resources/unicode-17.property-value-aliases.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			]
		},
		{
			"id": "unicode-17-scripts",
			"kind": "unicode-profile",
			"path": "resources/unicode-17.scripts.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			]
		},
		{
			"id": "unicode-17-core-summary",
			"kind": "unicode-profile",
			"path": "resources/unicode-17.core.summary.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			]
		}
	],
	"capabilitySlots": [
		{
			"slot": "unicode-profile",
			"status": "task-supported",
			"resourceIds": [
				"unicode-17-blocks",
				"unicode-17-property-value-aliases",
				"unicode-17-scripts",
				"unicode-17-core-summary"
			],
			"notes": [
				"Unicode 17 script, block, and property-value alias resources are available for Unicode profile consumers."
			]
		}
	],
	"license": "Unicode-3.0",
	"citations": [
		"Unicode Character Database 17.0.0."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
