// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:fr-syntax-ud-gsd-sa",
	"name": "French UD GSD Syntax Share-Alike Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-fr-syntax-ud-gsd-sa",
	"targets": {
		"languages": [
			"fr"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "fr-ud-gsd-upos",
			"kind": "grammar",
			"path": "resources/ud-gsd.upos.tsv",
			"format": "tsv",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies French GSD r2.18 annotations."
			]
		},
		{
			"id": "fr-ud-gsd-features",
			"kind": "morphology",
			"path": "resources/ud-gsd.features.tsv",
			"format": "tsv",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies French GSD r2.18 annotations."
			]
		},
		{
			"id": "fr-ud-gsd-dependencies",
			"kind": "grammar",
			"path": "resources/ud-gsd.dependencies.tsv",
			"format": "tsv",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies French GSD r2.18 annotations."
			]
		},
		{
			"id": "fr-ud-gsd-sentence-profile",
			"kind": "statistical-model",
			"path": "resources/ud-gsd.sentence-profile.tsv",
			"format": "tsv",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies French GSD r2.18 annotations."
			]
		},
		{
			"id": "fr-ud-gsd-annotations",
			"kind": "dataset",
			"path": "resources/ud-gsd.annotations.tsv",
			"format": "tsv",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies French GSD r2.18 annotations."
			]
		},
		{
			"id": "fr-ud-gsd-quality",
			"kind": "quality-profile",
			"path": "resources/ud-gsd.quality.json",
			"format": "json",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies French GSD r2.18 annotations."
			]
		},
		{
			"id": "fr-ud-gsd-syntax-canonical",
			"kind": "grammar",
			"path": "resources/ud-gsd.syntax.json",
			"format": "json",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies French GSD r2.18 annotations."
			],
			"metadata": {
				"canonicalSchema": "textpack-syntax-resource.schema.json"
			}
		},
		{
			"id": "fr-ud-gsd-morphology-canonical",
			"kind": "morphology",
			"path": "resources/ud-gsd.morphology.json",
			"format": "json",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies French GSD r2.18 annotations."
			],
			"metadata": {
				"canonicalSchema": "textpack-morphology-resource.schema.json"
			}
		},
		{
			"id": "fr-ud-gsd-quality-profile",
			"kind": "quality-profile",
			"path": "resources/ud-gsd.quality-profile.json",
			"format": "json",
			"license": "CC-BY-SA-4.0",
			"citations": [
				"Universal Dependencies French GSD r2.18 annotations."
			],
			"metadata": {
				"canonicalSchema": "textpack-quality-profile-resource.schema.json"
			}
		}
	],
	"capabilitySlots": [
		{
			"slot": "tagging",
			"status": "task-supported",
			"resourceIds": [
				"fr-ud-gsd-upos",
				"fr-ud-gsd-features",
				"fr-ud-gsd-annotations",
				"fr-ud-gsd-morphology-canonical"
			],
			"capabilities": {
				"tagging": "statistical",
				"morphology": "statistical"
			},
			"notes": [
				"UD French GSD part-of-speech and morphosyntactic feature profiles are available under the share-alike policy surface."
			]
		},
		{
			"slot": "syntax",
			"status": "task-supported",
			"resourceIds": [
				"fr-ud-gsd-dependencies",
				"fr-ud-gsd-sentence-profile",
				"fr-ud-gsd-annotations",
				"fr-ud-gsd-syntax-canonical"
			],
			"notes": [
				"UD French GSD annotation-derived UPOS, feature, dependency-label, sentence-profile, and syntax resources are available under the share-alike policy surface."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"fr-ud-gsd-quality",
				"fr-ud-gsd-quality-profile"
			],
			"notes": [
				"Generated quality profile records source coverage, accepted records, rejected records, and raw-text exclusion evidence."
			]
		}
	],
	"license": "CC-BY-SA-4.0",
	"citations": [
		"Universal Dependencies French GSD r2.18 annotations."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
