// Generated by tools/textpack-forge. Do not edit.

import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import type { PackResourceMap } from "@ismail-elkorchi/textpack";

const resourceRoot = new URL("../resources/", import.meta.url);

async function readResource(
	resourcePath: string,
	encoding: "gzip-base64" | "utf8",
): Promise<string> {
	const text = await readFile(new URL(resourcePath, resourceRoot), "utf8");
	if (encoding === "utf8") return text;
	return gunzipSync(Buffer.from(text.trim(), "base64")).toString("utf8");
}

export async function resources(): Promise<PackResourceMap> {
	// biome-ignore format: generated resource map preserves deterministic resource ordering.
	return {
		"fr-ud-gsd-upos": await readResource(
			"ud-gsd.upos.tsv",
			"utf8",
		),
		"fr-ud-gsd-features": await readResource(
			"ud-gsd.features.tsv",
			"utf8",
		),
		"fr-ud-gsd-dependencies": await readResource(
			"ud-gsd.dependencies.tsv",
			"utf8",
		),
		"fr-ud-gsd-sentence-profile": await readResource(
			"ud-gsd.sentence-profile.tsv",
			"utf8",
		),
		"fr-ud-gsd-annotations": await readResource(
			"ud-gsd.annotations.tsv",
			"utf8",
		),
		"fr-ud-gsd-quality": await readResource(
			"ud-gsd.quality.json",
			"utf8",
		),
		"fr-ud-gsd-syntax-canonical": await readResource(
			"ud-gsd.syntax.json",
			"utf8",
		),
		"fr-ud-gsd-morphology-canonical": await readResource(
			"ud-gsd.morphology.json",
			"utf8",
		),
		"fr-ud-gsd-quality-profile": await readResource(
			"ud-gsd.quality-profile.json",
			"utf8",
		),
	};
}
