// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"fr-ud-gsd-upos": {"byteLength":211,"checksum":"sha256:b30d9b5935c188f22c78963d7bad7511d2c2ded496acfa7958fbc431ae77a26d","encoding":"utf8","kind":"file-backed-resource","lineCount":18,"nonEmptyLineCount":17,"path":"resources/ud-gsd.upos.tsv","resourceTextByteLength":211},
	"fr-ud-gsd-features": {"byteLength":979,"checksum":"sha256:4f8434ac18d7dcc5519bd1f8a8e297182e19401d37a779ef2a483e9449af46f9","encoding":"utf8","kind":"file-backed-resource","lineCount":61,"nonEmptyLineCount":60,"path":"resources/ud-gsd.features.tsv","resourceTextByteLength":979},
	"fr-ud-gsd-dependencies": {"byteLength":2781,"checksum":"sha256:88ac7480f6493c22225cde293b4f8cdc86d2d6005725c21dca49d759798e7e18","encoding":"utf8","kind":"file-backed-resource","lineCount":167,"nonEmptyLineCount":166,"path":"resources/ud-gsd.dependencies.tsv","resourceTextByteLength":2781},
	"fr-ud-gsd-sentence-profile": {"byteLength":140,"checksum":"sha256:de675ebdcbf4643146338b7b4a29fefa0c50015438d6e044204f3d75338e2e57","encoding":"utf8","kind":"file-backed-resource","lineCount":5,"nonEmptyLineCount":4,"path":"resources/ud-gsd.sentence-profile.tsv","resourceTextByteLength":140},
	"fr-ud-gsd-annotations": {"byteLength":25796644,"checksum":"sha256:1024b7ee512bb7b5e669931fda2914f88f7a82d452290d2ca0080abeb67142bc","encoding":"utf8","kind":"file-backed-resource","lineCount":400387,"nonEmptyLineCount":400386,"path":"resources/ud-gsd.annotations.tsv","resourceTextByteLength":25796644},
	"fr-ud-gsd-quality": {"byteLength":1011,"checksum":"sha256:18ab4dd5a7a755825b063dc53814584ae603e635dee246510c4fa90546b2c2af","encoding":"utf8","kind":"file-backed-resource","lineCount":40,"nonEmptyLineCount":39,"path":"resources/ud-gsd.quality.json","resourceTextByteLength":1011},
	"fr-ud-gsd-syntax-canonical": {"byteLength":21286,"checksum":"sha256:d78fa813f096faa29a53b7c76016bcd4a0d193d444605ff0543c1d92a3440ae8","encoding":"utf8","kind":"file-backed-resource","lineCount":1273,"nonEmptyLineCount":1272,"path":"resources/ud-gsd.syntax.json","resourceTextByteLength":21286},
	"fr-ud-gsd-morphology-canonical": {"byteLength":3274,"checksum":"sha256:f1ee619d4dd09609d4fefc3b205b7114ceb45135333b783161719237f9a6301f","encoding":"utf8","kind":"file-backed-resource","lineCount":215,"nonEmptyLineCount":214,"path":"resources/ud-gsd.morphology.json","resourceTextByteLength":3274},
	"fr-ud-gsd-quality-profile": {"byteLength":922,"checksum":"sha256:bd6953a7b90ebe283d7a9d23e0b58098f32e6b9983676609d08f217e69dd7530","encoding":"utf8","kind":"file-backed-resource","lineCount":41,"nonEmptyLineCount":40,"path":"resources/ud-gsd.quality-profile.json","resourceTextByteLength":922},
} as const;
