// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:fr-corpus",
	"name": "French Tatoeba Corpus Artifact Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-fr-corpus",
	"targets": {
		"languages": [
			"fr"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "fr-tatoeba-corpus-artifact",
			"kind": "corpus",
			"path": "resources/tatoeba-fr.corpus-artifact.json",
			"format": "json",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly French exports, 2026-06-06."
			],
			"metadata": {
				"canonicalSchema": "textpack-corpus-resource.schema.json"
			}
		},
		{
			"id": "fr-tatoeba-corpus-quality",
			"kind": "quality-profile",
			"path": "resources/tatoeba-fr.corpus-quality.json",
			"format": "json",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly French exports, 2026-06-06."
			]
		},
		{
			"id": "fr-tatoeba-corpus-quality-profile",
			"kind": "quality-profile",
			"path": "resources/tatoeba-fr.corpus-quality-profile.json",
			"format": "json",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly French exports, 2026-06-06."
			],
			"metadata": {
				"canonicalSchema": "textpack-quality-profile-resource.schema.json"
			}
		}
	],
	"artifacts": [
		{
			"artifactId": "artifact:textpack-fr-corpus:full:tatoeba-fra-sentences-detailed:2026-06-06",
			"sourceIds": [
				"source:tatoeba:weekly-french-2026-06-06"
			],
			"version": "2026-06-06",
			"profile": "full",
			"sizeBytes": 14624789,
			"mediaType": "text/tab-separated-values",
			"compression": "bzip2",
			"checksum": {
				"algorithm": "sha256",
				"value": "bc6a17bd87705dc021a1cc2fd2cddc7b6862cd60b0128ea5dda2dbb50910cfd1"
			},
			"licenseExpression": "CC-BY-2.0-FR",
			"redistributionPolicy": "redistributable-with-attribution",
			"retrieval": {
				"kind": "https",
				"uri": "https://downloads.tatoeba.org/exports/per_language/fra/fra_sentences_detailed.tsv.bz2",
				"instructions": "Fetch explicitly from Tatoeba weekly exports and verify the SHA-256 checksum before unpacking or indexing."
			},
			"cacheKey": "tatoeba-fra-sentences-detailed-tsv-bz2-2026-06-06",
			"expectedFiles": [
				{
					"path": "fra_sentences_detailed.tsv.bz2",
					"sizeBytes": 14624789,
					"checksum": "sha256:bc6a17bd87705dc021a1cc2fd2cddc7b6862cd60b0128ea5dda2dbb50910cfd1"
				}
			]
		}
	],
	"capabilitySlots": [
		{
			"slot": "corpus",
			"status": "artifact-backed",
			"resourceIds": [
				"fr-tatoeba-corpus-artifact"
			],
			"artifactIds": [
				"artifact:textpack-fr-corpus:full:tatoeba-fra-sentences-detailed:2026-06-06"
			],
			"notes": [
				"Tatoeba French detailed sentence export is available through an explicit artifact descriptor.",
				"Descriptor-only artifact metadata does not satisfy task-supported readiness until local generated rows, extracts, indexes, or databases are materialized."
			]
		},
		{
			"slot": "quality",
			"status": "artifact-backed",
			"resourceIds": [
				"fr-tatoeba-corpus-quality",
				"fr-tatoeba-corpus-quality-profile"
			],
			"notes": [
				"Generated quality profile records row count, artifact size, checksum evidence, and local materialization limitations.",
				"Descriptor-only artifact metadata does not satisfy task-supported readiness until local generated rows, extracts, indexes, or databases are materialized."
			]
		}
	],
	"license": "CC-BY-2.0-FR",
	"citations": [
		"Tatoeba weekly French exports, 2026-06-06."
	],
	"gapNotes": [
		{
			"id": "gap:pack:fr-corpus:corpus",
			"slot": "corpus",
			"status": "artifact-backed",
			"message": "corpus is artifact-backed in this source-backed concrete pack."
		},
		{
			"id": "gap:pack:fr-corpus:quality",
			"slot": "quality",
			"status": "artifact-backed",
			"message": "quality is artifact-backed in this source-backed concrete pack."
		}
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
