// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"fr-tatoeba-corpus-sentences": {"byteLength": 26671945,"checksum": "sha256:8526a9895132794ee1bfd5837c0da3e96968065b2e1c1aa482dd46669b087916","encoding": "gzip-base64","kind": "file-backed-resource","lineCount": 718598,"nonEmptyLineCount": 718597,"packageName": "@ismail-elkorchi/textpack-fr-corpus","packageRoot": new URL("../", import.meta.url).href,"path": "resources/tatoeba-fr.sentences.tsv.gz.b64","resourceTextByteLength": 77091245},
	"fr-tatoeba-corpus-canonical": {"byteLength": 1115,"checksum": "sha256:a903a5e0762abc6dc6d0ef3598b24e18ff094b83cd76013fd50a7c81607afa45","encoding": "utf8","kind": "file-backed-resource","lineCount": 34,"nonEmptyLineCount": 33,"packageName": "@ismail-elkorchi/textpack-fr-corpus","packageRoot": new URL("../", import.meta.url).href,"path": "resources/tatoeba-fr.corpus.json","resourceTextByteLength": 1115},
	"fr-tatoeba-corpus-quality": {"byteLength": 899,"checksum": "sha256:5fda2a6afa7254d3d9591c8e06d19f71bc47a7baa4e975c1b77310286791e21d","encoding": "utf8","kind": "file-backed-resource","lineCount": 21,"nonEmptyLineCount": 20,"packageName": "@ismail-elkorchi/textpack-fr-corpus","packageRoot": new URL("../", import.meta.url).href,"path": "resources/tatoeba-fr.corpus-quality.json","resourceTextByteLength": 899},
	"fr-tatoeba-corpus-quality-profile": {"byteLength": 1345,"checksum": "sha256:d5babdabae9427ebb8d3d605f4a932368765fec38666595bb9eaadd01fea8f4a","encoding": "utf8","kind": "file-backed-resource","lineCount": 46,"nonEmptyLineCount": 45,"packageName": "@ismail-elkorchi/textpack-fr-corpus","packageRoot": new URL("../", import.meta.url).href,"path": "resources/tatoeba-fr.corpus-quality-profile.json","resourceTextByteLength": 1345},
} as const;
