// Generated by tools/textpack-forge. Do not edit.

import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import type { PackResourceMap } from "@ismail-elkorchi/textpack";

const resourceRoot = new URL("../resources/", import.meta.url);

async function readResource(
	resourcePath: string,
	encoding: "gzip-base64" | "utf8",
): Promise<string> {
	const text = await readFile(new URL(resourcePath, resourceRoot), "utf8");
	if (encoding === "utf8") return text;
	return gunzipSync(Buffer.from(text.trim(), "base64")).toString("utf8");
}

export async function resources(): Promise<PackResourceMap> {
	// biome-ignore format: generated resource map preserves deterministic resource ordering.
	return {
		"fr-tatoeba-corpus-sentences": await readResource(
			"tatoeba-fr.sentences.tsv.gz.b64",
			"gzip-base64",
		),
		"fr-tatoeba-corpus-canonical": await readResource(
			"tatoeba-fr.corpus.json",
			"utf8",
		),
		"fr-tatoeba-corpus-quality": await readResource(
			"tatoeba-fr.corpus-quality.json",
			"utf8",
		),
		"fr-tatoeba-corpus-quality-profile": await readResource(
			"tatoeba-fr.corpus-quality-profile.json",
			"utf8",
		),
	};
}
