import type { TextPackManifest } from "@ismail-elkorchi/textpack";

export const manifest: TextPackManifest = {
	id: "pack:en-core",
	name: "English Core Reference Pack",
	version: "0.1.0",
	packageName: "@ismail-elkorchi/textpack-en-core",
	kind: [
		"segmentation-profile",
		"abbreviation-table",
		"stoplist",
		"lexicon",
		"gazetteer",
		"dataset",
		"morphology",
		"fst",
		"grammar",
		"corpus",
	],
	targets: {
		languages: ["en"],
		scripts: ["Latn"],
		modalities: ["typed"],
	},
	engines: {
		"@ismail-elkorchi/textpack": "^0.1.0",
	},
	resources: [
		{
			id: "profile-en-core",
			kind: "segmentation-profile",
			path: "resources/profile.en.core.txt",
			format: "lines",
		},
		{
			id: "abbrev-en-core",
			kind: "abbreviation-table",
			path: "resources/abbrev.en.common.txt",
			format: "lines",
		},
		{
			id: "stoplist-en-core",
			kind: "stoplist",
			path: "resources/stopwords.en.basic.txt",
			format: "lines",
		},
		{
			id: "lexicon-en-core",
			kind: "lexicon",
			path: "resources/lexicon.en.simple.tsv",
			format: "tsv",
		},
		{
			id: "gazetteer-en-core",
			kind: "gazetteer",
			path: "resources/gazetteer.en.core.tsv",
			format: "tsv",
		},
		{
			id: "tagset-ud-lite",
			kind: "dataset",
			path: "resources/tagset.ud-lite.tsv",
			format: "tsv",
			metadata: { datasetKind: "pos-tagset" },
		},
		{
			id: "morph-en-core",
			kind: "morphology",
			path: "resources/morph.en.simple.tsv",
			format: "tsv",
		},
		{
			id: "fst-en-core",
			kind: "fst",
			path: "resources/transducer.en.core.txt",
			format: "lines",
		},
		{
			id: "grammar-en-core",
			kind: "grammar",
			path: "resources/structure.en.core.txt",
			format: "lines",
		},
		{
			id: "corpus-en-smoke",
			kind: "corpus",
			path: "resources/benchmark.smoke.txt",
			format: "lines",
		},
	],
	capabilities: {
		segmentation: "rules",
		morphology: "fst",
		tagging: "rules",
		parsing: "rules",
		extraction: "gazetteer",
		terminology: "lexicon",
	},
	license: "MIT",
	citations: ["repo:packages/textpack-en-core/resources"],
} as const;
