// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:wikidata-fr",
	"name": "Wikidata French Entity Extract Textpack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-wikidata-fr",
	"targets": {
		"languages": [
			"fr"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "wikidata-fr-entities",
			"kind": "knowledge-base",
			"path": "resources/wikidata-fr.entities.tsv.gz.b64",
			"format": "text/tab-separated-values",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08."
			],
			"schemaId": "textkb.knowledge-base.rows.v1"
		},
		{
			"id": "wikidata-fr-aliases",
			"kind": "knowledge-base",
			"path": "resources/wikidata-fr.aliases.tsv.gz.b64",
			"format": "text/tab-separated-values",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08."
			],
			"schemaId": "textkb.knowledge-base.rows.v1"
		},
		{
			"id": "wikidata-fr-relations",
			"kind": "knowledge-base",
			"path": "resources/wikidata-fr.relations.tsv.gz.b64",
			"format": "text/tab-separated-values",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08."
			],
			"schemaId": "textkb.knowledge-base.rows.v1"
		},
		{
			"id": "wikidata-fr-kb-canonical",
			"kind": "knowledge-base",
			"path": "resources/wikidata-fr.kb.json",
			"format": "json",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08."
			],
			"schemaId": "textkb.knowledge-base.v1"
		},
		{
			"id": "wikidata-fr-quality",
			"kind": "quality-profile",
			"path": "resources/wikidata-fr.quality.json",
			"format": "json",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08."
			],
			"schemaId": "textquality.evidence.v1"
		},
		{
			"id": "wikidata-fr-quality-profile",
			"kind": "quality-profile",
			"path": "resources/wikidata-fr.quality-profile.json",
			"format": "json",
			"license": "CC0-1.0",
			"citations": [
				"Wikidata main structured data dump, 2026-06-08."
			],
			"schemaId": "textquality.profile.v1"
		}
	],
	"artifacts": [
		{
			"artifactId": "artifact:textpack-wikidata-fr:full:wikidata-entities-json:20260608",
			"sourceIds": [
				"source:wikidata:main"
			],
			"version": "20260608",
			"profile": "full",
			"sizeBytes": 142291512349,
			"mediaType": "application/json",
			"compression": "gzip",
			"checksum": {
				"algorithm": "sha1",
				"value": "7a1165f121e50eca8f2e11674971d7f2d3c47b98"
			},
			"licenseExpression": "CC0-1.0",
			"redistributionPolicy": "redistributable",
			"retrieval": {
				"kind": "https",
				"uri": "https://dumps.wikimedia.org/wikidatawiki/entities/20260608/wikidata-20260608-all.json.gz",
				"instructions": "Fetch explicitly and verify against the upstream SHA-1 checksum sidecar before unpacking or indexing."
			},
			"cacheKey": "wikidata-main-20260608-all-json-gzip",
			"expectedFiles": [
				{
					"path": "wikidata-20260608-all.json.gz",
					"sizeBytes": 142291512349,
					"checksum": "sha1:7a1165f121e50eca8f2e11674971d7f2d3c47b98"
				}
			]
		}
	],
	"capabilitySlots": [
		{
			"slot": "kb",
			"status": "task-supported",
			"resourceIds": [
				"wikidata-fr-entities",
				"wikidata-fr-aliases",
				"wikidata-fr-relations",
				"wikidata-fr-kb-canonical"
			],
			"artifactIds": [
				"artifact:textpack-wikidata-fr:full:wikidata-entities-json:20260608"
			],
			"bindings": [
				{
					"role": "primary",
					"resourceId": "wikidata-fr-kb-canonical",
					"schemaId": "textkb.knowledge-base.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textkb"
				},
				{
					"role": "table",
					"resourceId": "wikidata-fr-aliases",
					"schemaId": "textkb.knowledge-base.rows.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textkb"
				},
				{
					"role": "table",
					"resourceId": "wikidata-fr-entities",
					"schemaId": "textkb.knowledge-base.rows.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textkb"
				},
				{
					"role": "table",
					"resourceId": "wikidata-fr-relations",
					"schemaId": "textkb.knowledge-base.rows.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textkb"
				}
			],
			"readerRequired": true,
			"notes": [
				"Wikidata French entity labels, aliases, selected relations, and canonical KB metadata are materialized locally for the declared extract scope.",
				"The local extract is scoped and does not claim complete Wikidata dump coverage."
			],
			"capabilities": {
				"terminology": "kb",
				"extraction": "gazetteer"
			}
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"wikidata-fr-quality",
				"wikidata-fr-quality-profile"
			],
			"bindings": [
				{
					"role": "evidence",
					"resourceId": "wikidata-fr-quality",
					"schemaId": "textquality.evidence.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textquality"
				},
				{
					"role": "quality",
					"resourceId": "wikidata-fr-quality-profile",
					"schemaId": "textquality.profile.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textquality"
				}
			],
			"readerRequired": true,
			"notes": [
				"Generated quality profile records local row counts, upstream checksum sidecar evidence, and extract-scope limitations."
			]
		}
	],
	"license": "CC0-1.0",
	"citations": [
		"Wikidata main structured data dump, 2026-06-08."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
