// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"ar-tatoeba-corpus-sentences": {"byteLength": 2210785,"checksum": "sha256:25934fc4d63b72bcfac67c1f83d3617da81f7c0d520af4f9b35063666d82f6bc","encoding": "gzip-base64","kind": "file-backed-resource","lineCount": 67976,"nonEmptyLineCount": 67975,"packageName": "@ismail-elkorchi/textpack-ar-corpus","packageRoot": new URL("../", import.meta.url).href,"path": "resources/tatoeba-ar.sentences.tsv.gz.b64","resourceTextByteLength": 7313057},
	"ar-tatoeba-corpus-canonical": {"byteLength": 1114,"checksum": "sha256:ee7122e25157b3610c12f94ae539a124ba31133bb94cfbd64c1cf9126bd9252d","encoding": "utf8","kind": "file-backed-resource","lineCount": 34,"nonEmptyLineCount": 33,"packageName": "@ismail-elkorchi/textpack-ar-corpus","packageRoot": new URL("../", import.meta.url).href,"path": "resources/tatoeba-ar.corpus.json","resourceTextByteLength": 1114},
	"ar-tatoeba-corpus-quality": {"byteLength": 895,"checksum": "sha256:4ed720b4e8d06a9c3eb4da1342e0549c5cec19283f44ded459f44ca31a6d5b44","encoding": "utf8","kind": "file-backed-resource","lineCount": 21,"nonEmptyLineCount": 20,"packageName": "@ismail-elkorchi/textpack-ar-corpus","packageRoot": new URL("../", import.meta.url).href,"path": "resources/tatoeba-ar.corpus-quality.json","resourceTextByteLength": 895},
	"ar-tatoeba-corpus-quality-profile": {"byteLength": 1344,"checksum": "sha256:fd8a5aa6b8b4f90c6a5ffa2ea0d18740f778d405f23466c0746a789d3b8a652d","encoding": "utf8","kind": "file-backed-resource","lineCount": 46,"nonEmptyLineCount": 45,"packageName": "@ismail-elkorchi/textpack-ar-corpus","packageRoot": new URL("../", import.meta.url).href,"path": "resources/tatoeba-ar.corpus-quality-profile.json","resourceTextByteLength": 1344},
} as const;
