// Generated by tools/textpack-forge. Do not edit.

export { manifest } from "./manifest.js";
export { resources } from "./resources.js";

import {
	loadPack,
	type ResolveTextPackComponentsOptions,
	resolvePackComponents,
	type TextPackComponent,
} from "@ismail-elkorchi/textpack";
import { manifest } from "./manifest.js";
import { resources } from "./resources.js";

export interface LoadFrenchQualityShareAlikeOptions
	extends Omit<ResolveTextPackComponentsOptions, "resolveComponent"> {
	readonly resolveComponent?: ResolveTextPackComponentsOptions["resolveComponent"];
}

async function resolveGeneratedComponent(
	component: TextPackComponent,
	options: LoadFrenchQualityShareAlikeOptions,
): Promise<unknown> {
	void options;
	switch (component.packageName) {
		case "@ismail-elkorchi/textpack-fr-core":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-fr-normalization":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-fr-segmentation":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-fr-lexicon-sa": {
			const module = await import(component.packageName);
			const loader = module.loadFrenchLexiconShareAlike;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFrenchLexiconShareAlike.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-fr-morphology-sa": {
			const module = await import(component.packageName);
			const loader = module.loadFrenchMorphologyShareAlike;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFrenchMorphologyShareAlike.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-fr-syntax-sa": {
			const module = await import(component.packageName);
			const loader = module.loadFrenchSyntaxShareAlike;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFrenchSyntaxShareAlike.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-fr-search-sa": {
			const module = await import(component.packageName);
			const loader = module.loadFrenchSearchShareAlike;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFrenchSearchShareAlike.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-fr-kb": {
			const module = await import(component.packageName);
			const loader = module.loadFrenchKnowledgeBase;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFrenchKnowledgeBase.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-fr-corpus":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-fr-parallel":
			return import(component.packageName);
		default:
			throw new TypeError(
				`No generated resolver entry for ${component.packageName}.`,
			);
	}
}

export async function loadFrenchQualityShareAlike(
	options: LoadFrenchQualityShareAlikeOptions = {},
) {
	return resolvePackComponents(await loadPack({ manifest, resources }), {
		...options,
		licensePolicy: options.licensePolicy ?? "allow-share-alike",
		artifactPolicy: options.artifactPolicy ?? "fetch-explicit",
		conflictPolicy: options.conflictPolicy ?? "first",
		resolveComponent:
			options.resolveComponent ??
			((component) => resolveGeneratedComponent(component, options)),
	});
}

export default { manifest, resources, loadFrenchQualityShareAlike };
