export type {
	AlignmentAnnotateOptions,
	AlignmentLink,
	AlignmentRelation,
	BaseParallelOptions,
	BilingualDictionaryEntry,
	BilingualLexiconCandidate,
	BilingualLexiconOptions,
	BilingualTermCandidate,
	BilingualTermOptions,
	CollocationComparisonOptions,
	CorpusReference,
	JsonObject,
	JsonPrimitive,
	JsonValue,
	PackageName,
	ParallelCollocationComparison,
	ParallelCorpus,
	ParallelCorpusOptions,
	ParallelDiagnostic,
	ParallelDiagnosticSeverity,
	ParallelDocument,
	ParallelDocumentOptions,
	SentenceAlignmentModel,
	SentenceAlignOptions,
	TmOptions,
	TmSearchOptions,
	TransferOptions,
	TransferResources,
	TranslationMemory,
	TranslationMemoryHit,
	TranslationMemoryRow,
	WordAlignmentModel,
	WordAlignOptions,
} from "./internal/core.ts";
export {
	alignSentences,
	alignWords,
	annotateAlignment,
	assertJsonObject,
	assertJsonValue,
	buildAlignmentLink,
	buildTranslationMemory,
	compareAlignmentLinks,
	compareParallelCollocations,
	createParallelCorpus,
	createParallelDocument,
	extractBilingualTerms,
	induceBilingualLexicon,
	packageName,
	packageVersion,
	parallelDocumentsFromRecords,
	parallelEvidence,
	searchTranslationMemory,
	shallowTransfer,
	TextParallelError,
	trainSentenceAligner,
	trainWordAligner,
} from "./internal/core.ts";
export type {
	ParallelLinkRow,
	ParallelRowsFromPackOptions,
	ParallelTableResource,
} from "./textpack.ts";
export {
	parallelCorpusFromPack,
	parallelLinkRowsFromPack,
	parallelTablesFromPack,
} from "./textpack.ts";
