// Generated by tools/textpack-forge. Do not edit.

import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import type { PackResourceMap } from "@ismail-elkorchi/textpack";

const resourceRoot = new URL("../resources/", import.meta.url);

async function readResource(
	resourcePath: string,
	encoding: "gzip-base64" | "utf8",
): Promise<string> {
	const text = await readFile(new URL(resourcePath, resourceRoot), "utf8");
	if (encoding === "utf8") return text;
	return gunzipSync(Buffer.from(text.trim(), "base64")).toString("utf8");
}

export async function resources(): Promise<PackResourceMap> {
	// biome-ignore format: generated resource map preserves deterministic resource ordering.
	return {
		"fr-lexique-entries": await readResource(
			"lexique-383.entries.tsv.gz.b64",
			"gzip-base64",
		),
		"fr-lexique-lemmas": await readResource(
			"lexique-383.lemmas.tsv.gz.b64",
			"gzip-base64",
		),
		"fr-lexique-pos-inventory": await readResource(
			"lexique-383.pos.tsv",
			"utf8",
		),
		"fr-lexique-lexicon-canonical": await readResource(
			"lexique-383.lexicon.json",
			"utf8",
		),
		"fr-lexique-morphology-canonical": await readResource(
			"lexique-383.morphology.json",
			"utf8",
		),
		"fr-lexique-search-profile": await readResource(
			"lexique-383.search-profile.json",
			"utf8",
		),
		"fr-lexique-quality": await readResource(
			"lexique-383.quality.json",
			"utf8",
		),
		"fr-lexique-quality-profile": await readResource(
			"lexique-383.quality-profile.json",
			"utf8",
		),
	};
}
