// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:fr-unimorph-sa",
	"name": "French UniMorph Share-Alike Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-fr-unimorph-sa",
	"targets": {
		"languages": [
			"fr"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "fr-unimorph-paradigms",
			"kind": "morphology",
			"path": "resources/unimorph-fra.paradigms.tsv.gz.b64",
			"format": "tsv+gzip+base64",
			"license": "CC-BY-SA-3.0",
			"citations": [
				"UniMorph French repository, commit f672f8cceb2d5f5a1e2241b5622c8845f8274635."
			]
		},
		{
			"id": "fr-unimorph-lookup-analyzer",
			"kind": "morphology",
			"path": "resources/unimorph-fra.lookup-analyzer.tsv.gz.b64",
			"format": "tsv+gzip+base64",
			"license": "CC-BY-SA-3.0",
			"citations": [
				"UniMorph French repository, commit f672f8cceb2d5f5a1e2241b5622c8845f8274635."
			]
		},
		{
			"id": "fr-unimorph-lookup-generator",
			"kind": "morphology",
			"path": "resources/unimorph-fra.lookup-generator.tsv.gz.b64",
			"format": "tsv+gzip+base64",
			"license": "CC-BY-SA-3.0",
			"citations": [
				"UniMorph French repository, commit f672f8cceb2d5f5a1e2241b5622c8845f8274635."
			]
		},
		{
			"id": "fr-unimorph-feature-inventory",
			"kind": "morphology",
			"path": "resources/unimorph-fra.features.tsv",
			"format": "tsv",
			"license": "CC-BY-SA-3.0",
			"citations": [
				"UniMorph French repository, commit f672f8cceb2d5f5a1e2241b5622c8845f8274635."
			]
		},
		{
			"id": "fr-unimorph-pos-inventory",
			"kind": "morphology",
			"path": "resources/unimorph-fra.pos.tsv",
			"format": "tsv",
			"license": "CC-BY-SA-3.0",
			"citations": [
				"UniMorph French repository, commit f672f8cceb2d5f5a1e2241b5622c8845f8274635."
			]
		},
		{
			"id": "fr-unimorph-morphology-canonical",
			"kind": "morphology",
			"path": "resources/unimorph-fra.morphology.json",
			"format": "json",
			"license": "CC-BY-SA-3.0",
			"citations": [
				"UniMorph French repository, commit f672f8cceb2d5f5a1e2241b5622c8845f8274635."
			],
			"metadata": {
				"canonicalSchema": "textpack-morphology-resource.schema.json"
			}
		},
		{
			"id": "fr-unimorph-quality",
			"kind": "quality-profile",
			"path": "resources/unimorph-fra.quality.json",
			"format": "json",
			"license": "CC-BY-SA-3.0",
			"citations": [
				"UniMorph French repository, commit f672f8cceb2d5f5a1e2241b5622c8845f8274635."
			]
		},
		{
			"id": "fr-unimorph-quality-profile",
			"kind": "quality-profile",
			"path": "resources/unimorph-fra.quality-profile.json",
			"format": "json",
			"license": "CC-BY-SA-3.0",
			"citations": [
				"UniMorph French repository, commit f672f8cceb2d5f5a1e2241b5622c8845f8274635."
			],
			"metadata": {
				"canonicalSchema": "textpack-quality-profile-resource.schema.json"
			}
		}
	],
	"capabilitySlots": [
		{
			"slot": "morphology",
			"status": "task-supported",
			"resourceIds": [
				"fr-unimorph-paradigms",
				"fr-unimorph-lookup-analyzer",
				"fr-unimorph-lookup-generator",
				"fr-unimorph-feature-inventory",
				"fr-unimorph-pos-inventory",
				"fr-unimorph-morphology-canonical"
			],
			"capabilities": {
				"morphology": "paradigm-table"
			},
			"notes": [
				"UniMorph French lemma/form paradigms, feature bundles, lookup analyzer rows, and lookup generator rows are available under the share-alike policy surface."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"fr-unimorph-quality",
				"fr-unimorph-quality-profile"
			],
			"notes": [
				"Generated quality profile records source coverage, accepted records, rejected records, and share-alike isolation evidence."
			]
		}
	],
	"license": "CC-BY-SA-3.0",
	"citations": [
		"UniMorph French repository, commit f672f8cceb2d5f5a1e2241b5622c8845f8274635."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
