// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"fr-unimorph-paradigms": {"byteLength":4339245,"checksum":"sha256:af854f6251e94d5ba5469ea5d9fb1680656777ac87b1daf0ef11a8e2dd522ede","encoding":"gzip-base64","kind":"file-backed-resource","lineCount":367734,"nonEmptyLineCount":367733,"path":"resources/unimorph-fra.paradigms.tsv.gz.b64","resourceTextByteLength":25167521},
	"fr-unimorph-lookup-analyzer": {"byteLength":3819421,"checksum":"sha256:02700dd8f417411d84fc5ca8be07a2d62cb427c288366be6439ffeb2ddcb0985","encoding":"gzip-base64","kind":"file-backed-resource","lineCount":367734,"nonEmptyLineCount":367733,"path":"resources/unimorph-fra.lookup-analyzer.tsv.gz.b64","resourceTextByteLength":21969003},
	"fr-unimorph-lookup-generator": {"byteLength":2978997,"checksum":"sha256:0486e62bca8d4cbe68f7965208f93d63005edf6da2ba327c5055e208e59c7253","encoding":"gzip-base64","kind":"file-backed-resource","lineCount":367734,"nonEmptyLineCount":367733,"path":"resources/unimorph-fra.lookup-generator.tsv.gz.b64","resourceTextByteLength":21969003},
	"fr-unimorph-feature-inventory": {"byteLength":210,"checksum":"sha256:398ac0e5974e1408a8e1da1983d5445d3e0e467df44d56eaff1e9ccba61a4713","encoding":"utf8","kind":"file-backed-resource","lineCount":21,"nonEmptyLineCount":20,"path":"resources/unimorph-fra.features.tsv","resourceTextByteLength":210},
	"fr-unimorph-pos-inventory": {"byteLength":52,"checksum":"sha256:71c6e52446ede637bd7bf3de9a839d81ab3ab82669116a21ea02af64afb99744","encoding":"utf8","kind":"file-backed-resource","lineCount":5,"nonEmptyLineCount":4,"path":"resources/unimorph-fra.pos.tsv","resourceTextByteLength":52},
	"fr-unimorph-morphology-canonical": {"byteLength":1650,"checksum":"sha256:0490c0a1246de5e59e96cd6a001cbf59ad743a40be29b432b296c6d73de1c4eb","encoding":"utf8","kind":"file-backed-resource","lineCount":84,"nonEmptyLineCount":83,"path":"resources/unimorph-fra.morphology.json","resourceTextByteLength":1650},
	"fr-unimorph-quality": {"byteLength":705,"checksum":"sha256:e0d90487864de078813601eab1a6feff09d9e118c6615fcc3f56f9d5de904209","encoding":"utf8","kind":"file-backed-resource","lineCount":21,"nonEmptyLineCount":20,"path":"resources/unimorph-fra.quality.json","resourceTextByteLength":705},
	"fr-unimorph-quality-profile": {"byteLength":1242,"checksum":"sha256:a833ad661ac36374a66da9802bc62489f0681b58843b10c1f449e834835e4bf0","encoding":"utf8","kind":"file-backed-resource","lineCount":54,"nonEmptyLineCount":53,"path":"resources/unimorph-fra.quality-profile.json","resourceTextByteLength":1242},
} as const;
