// Generated by tools/textpack-forge. Do not edit.

import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import type { PackResourceMap } from "@ismail-elkorchi/textpack";

const resourceRoot = new URL("../resources/", import.meta.url);

async function readResource(
	resourcePath: string,
	encoding: "gzip-base64" | "utf8",
): Promise<string> {
	const text = await readFile(new URL(resourcePath, resourceRoot), "utf8");
	if (encoding === "utf8") return text;
	return gunzipSync(Buffer.from(text.trim(), "base64")).toString("utf8");
}

export async function resources(): Promise<PackResourceMap> {
	// biome-ignore format: generated resource map preserves deterministic resource ordering.
	return {
		"fr-unimorph-paradigms": await readResource(
			"unimorph-fra.paradigms.tsv.gz.b64",
			"gzip-base64",
		),
		"fr-unimorph-lookup-analyzer": await readResource(
			"unimorph-fra.lookup-analyzer.tsv.gz.b64",
			"gzip-base64",
		),
		"fr-unimorph-lookup-generator": await readResource(
			"unimorph-fra.lookup-generator.tsv.gz.b64",
			"gzip-base64",
		),
		"fr-unimorph-feature-inventory": await readResource(
			"unimorph-fra.features.tsv",
			"utf8",
		),
		"fr-unimorph-pos-inventory": await readResource(
			"unimorph-fra.pos.tsv",
			"utf8",
		),
		"fr-unimorph-morphology-canonical": await readResource(
			"unimorph-fra.morphology.json",
			"utf8",
		),
		"fr-unimorph-quality": await readResource(
			"unimorph-fra.quality.json",
			"utf8",
		),
		"fr-unimorph-quality-profile": await readResource(
			"unimorph-fra.quality-profile.json",
			"utf8",
		),
	};
}
