// Generated by tools/textpack-forge. Do not edit.

export { manifest } from "./manifest.js";
export { resources } from "./resources.js";

import {
	loadPack,
	type ResolveTextPackComponentsOptions,
	resolvePackComponents,
	type TextPackComponent,
} from "@ismail-elkorchi/textpack";
import { manifest } from "./manifest.js";
import { resources } from "./resources.js";

export interface LoadFrenchLexiconOptions
	extends Omit<ResolveTextPackComponentsOptions, "resolveComponent"> {
	readonly resolveComponent?: ResolveTextPackComponentsOptions["resolveComponent"];
}

async function resolveGeneratedComponent(
	component: TextPackComponent,
	options: LoadFrenchLexiconOptions,
): Promise<unknown> {
	void options;
	switch (component.packageName) {
		case "@ismail-elkorchi/textpack-fr-lexicon-sa": {
			const module = await import(component.packageName);
			const loader = module.loadFrenchLexiconShareAlike;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFrenchLexiconShareAlike.`,
				);
			}
			return loader(options);
		}
		default:
			throw new TypeError(
				`No generated resolver entry for ${component.packageName}.`,
			);
	}
}

export async function loadFrenchLexicon(
	options: LoadFrenchLexiconOptions = {},
) {
	return resolvePackComponents(await loadPack({ manifest, resources }), {
		...options,
		licensePolicy: options.licensePolicy ?? "allow-share-alike",
		artifactPolicy: options.artifactPolicy ?? "none",
		conflictPolicy: options.conflictPolicy ?? "first",
		resolveComponent:
			options.resolveComponent ??
			((component) => resolveGeneratedComponent(component, options)),
	});
}

export default { manifest, resources, loadFrenchLexicon };
