// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:fr-lexicon",
	"name": "French Lexicon Policy-Expanded Wrapper Textpack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-fr-lexicon",
	"targets": {
		"languages": [
			"fr"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [],
	"components": [
		{
			"packageName": "@ismail-elkorchi/textpack-fr-lexicon-sa",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Share-alike isolated French lexicon composite over Lexique 3.83 resources.",
			"licensePolicy": "allow-share-alike",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		}
	],
	"capabilitySlots": [
		{
			"slot": "lexicon",
			"status": "task-supported",
			"notes": [
				"The required component graph provides Lexique 3.83 lexical entries, lemmas, frequency fields, and canonical lexicon resources through an explicit share-alike policy wrapper."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"notes": [
				"Generated component reports and evaluation records are available for the required share-alike lexicon component."
			]
		}
	],
	"license": "CC-BY-SA-4.0",
	"citations": [
		"Lexique 3.83, 2019-06-04."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
