// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:language-registry",
	"name": "Language Registry Foundation Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-language-registry",
	"targets": {
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "bcp47-language-subtags",
			"kind": "language-registry",
			"path": "resources/bcp47.language-subtags.tsv",
			"format": "tsv",
			"license": "LicenseRef-IANA-Language-Subtag-Registry",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05."
			]
		},
		{
			"id": "bcp47-language-registry-summary",
			"kind": "language-registry",
			"path": "resources/bcp47.language-registry.summary.json",
			"format": "json",
			"license": "LicenseRef-IANA-Language-Subtag-Registry",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05."
			]
		}
	],
	"capabilitySlots": [
		{
			"slot": "language-registry",
			"status": "task-supported",
			"resourceIds": [
				"bcp47-language-subtags",
				"bcp47-language-registry-summary"
			],
			"notes": [
				"BCP 47 subtag registry resources are available for language, script, region, variant, grandfathered, and redundant tag consumers."
			]
		}
	],
	"license": "LicenseRef-IANA-Language-Subtag-Registry",
	"citations": [
		"IANA Language Subtag Registry, File-Date 2026-05-05."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:12e98edb0c3ebf9a839773b624b51a935a7dc8d57894c7dd29bc64944572dd19",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
