// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:fr-core",
	"name": "French Core Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-fr-core",
	"targets": {
		"languages": [
			"fr"
		],
		"scripts": [
			"Latn"
		],
		"regions": [
			"FR"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "fr-core-language-profile",
			"kind": "locale-profile",
			"path": "resources/fr.core.language-profile.json",
			"format": "json",
			"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05.",
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			]
		},
		{
			"id": "fr-core-orthography",
			"kind": "locale-profile",
			"path": "resources/fr.core.orthography.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			]
		},
		{
			"id": "fr-core-punctuation",
			"kind": "locale-profile",
			"path": "resources/fr.core.punctuation.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			]
		},
		{
			"id": "fr-core-basic-segmentation",
			"kind": "segmentation-profile",
			"path": "resources/fr.core.basic-segmentation.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"metadata": {
				"canonicalSchema": "textpack-segmentation-resource.schema.json"
			}
		},
		{
			"id": "fr-core-quality",
			"kind": "quality-profile",
			"path": "resources/fr.core.quality.json",
			"format": "json",
			"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05.",
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			]
		},
		{
			"id": "fr-core-quality-profile",
			"kind": "quality-profile",
			"path": "resources/fr.core.quality-profile.json",
			"format": "json",
			"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05.",
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"metadata": {
				"canonicalSchema": "textpack-quality-profile-resource.schema.json"
			}
		}
	],
	"capabilitySlots": [
		{
			"slot": "core",
			"status": "task-supported",
			"resourceIds": [
				"fr-core-language-profile",
				"fr-core-orthography",
				"fr-core-punctuation",
				"fr-core-basic-segmentation"
			],
			"capabilities": {
				"segmentation": "profile",
				"normalization": "unicode"
			},
			"notes": [
				"Core profile resources cover modern typed French identity, Latin-script orthography, Unicode punctuation, and a basic UAX #29 segmentation baseline."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"fr-core-quality",
				"fr-core-quality-profile"
			],
			"notes": [
				"Generated quality profile records source coverage, accepted records, rejected records, and scope limitations."
			]
		}
	],
	"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry",
	"citations": [
		"IANA Language Subtag Registry, File-Date 2026-05-05.",
		"Unicode Character Database 17.0.0.",
		"Unicode CLDR core data, cldr-core npm package 48.2.0."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
