function generatedHeader() {
	return "// Generated by tools/textpack-forge. Do not edit.\n\n";
}

function jsonFile(value) {
	return `${JSON.stringify(value, null, "\t")}\n`;
}

function sortJson(value) {
	if (Array.isArray(value)) return value.map((entry) => sortJson(entry));
	if (value === null || typeof value !== "object") return value;
	const output = {};
	for (const key of Object.keys(value).sort())
		output[key] = sortJson(value[key]);
	return output;
}

export function manifestModule(manifest) {
	return `${generatedHeader()}import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = ${jsonFile(manifest).trimEnd()} as const;
`;
}

export function indexModule() {
	return `${generatedHeader()}export { manifest } from "./manifest.js";
export { pack } from "./pack.js";
export { resources } from "./resources.js";

import { pack } from "./pack.js";

export default pack;
`;
}

export function packModule() {
	return `${generatedHeader()}import { createPack } from "@ismail-elkorchi/textpack";

import { manifest } from "./manifest.js";
import { resources } from "./resources.js";

export const pack = createPack(manifest, resources);
`;
}

function resourceMapValue(pack, payload) {
	const descriptor = sortJson({
		kind: "file-backed-resource",
		packageName: pack.packageName,
		packageRoot: "__TEXTPACK_PACKAGE_ROOT__",
		path: payload.path,
		encoding: payload.encoded,
		checksum: payload.checksum,
		byteLength: payload.byteLength,
		resourceTextByteLength: payload.resourceTextByteLength,
		lineCount: payload.lineCount,
		nonEmptyLineCount: payload.nonEmptyLineCount,
	});
	const properties = Object.entries(descriptor).map(([key, value]) => {
		if (key === "packageRoot") {
			return `${JSON.stringify(key)}: new URL("../", import.meta.url).href`;
		}
		return `${JSON.stringify(key)}: ${JSON.stringify(value)}`;
	});
	return `{${properties.join(",")}}`;
}

export function resourcesModule(pack) {
	const entries = pack.payloads
		.map(
			(payload) =>
				`\t${JSON.stringify(payload.id)}: ${resourceMapValue(pack, payload)},`,
		)
		.join("\n");
	const body = entries.length === 0 ? "" : `\n${entries}\n`;
	return `${generatedHeader()}import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {${body}} as const;
`;
}

import { readFile } from "node:fs/promises";
import path from "node:path";

import {
	assertModelBackedEvidence,
	coverageReportFor,
	evaluationReportFor,
	qualityReportFor,
} from "./evaluation.mjs";
import {
	isLicenseInclusiveDistribution,
	publishableSourcePolicyClasses,
	requiredSourcePolicyLanguageTags,
	sourcePolicyAllowsLicenseInclusiveDistribution,
	sourcePolicyClasses,
} from "./policy.mjs";
import { buildUnitIdForPackageName } from "./validation.mjs";

const ROOT = path.resolve(new URL("../../..", import.meta.url).pathname);
const GENERATED_BY = "tools/textpack-forge";
export const BUILD_COMMAND = "node tools/textpack-forge/cli.mjs build";
export const LOCK_PATH = "tools/textpack-forge/forge.lock.json";
const DEFAULT_PACK_SPEC_PATH =
	"tools/textpack-forge/packs/foundation-packs.pack.json";

export const PACKAGE_REPORT_FILES = [
	"LICENSE.generated.md",
	"NOTICE.generated.md",
	"SOURCES.generated.json",
	"ATTRIBUTION.generated.md",
	"COVERAGE.generated.json",
	"EVALUATION.generated.json",
	"QUALITY.generated.json",
];

const PACKAGE_SCRIPTS = {
	build:
		"node ../../../tools/clean-build-output.mjs dist && tsc -p tsconfig.build.json",
	lint: "biome check src test README.md package.json tsconfig.json tsconfig.build.json --files-ignore-unknown=true",
	"check:static":
		"tsc -p tsconfig.build.json --noEmit --noUnusedLocals --noUnusedParameters",
	"check:pack": "npm pack --dry-run",
	test: "npm run test:all",
	prepack: "npm run build",
};

function expect(condition, message, details) {
	if (condition) return;
	throw new Error(details === undefined ? message : `${message}\n${details}`);
}

function sorted(values) {
	return [...values].sort((left, right) => left.localeCompare(right));
}

function stableJson(value) {
	return `${JSON.stringify(sortJson(value), null, 2)}\n`;
}

function isDistributionPack(pack) {
	return pack.distribution === true;
}

export function packageId(packageName) {
	return packageName.replace("@ismail-elkorchi/", "");
}

function sizeClass(byteLength) {
	if (byteLength <= 500 * 1024) return "tiny";
	if (byteLength <= 5 * 1024 * 1024) return "small";
	if (byteLength <= 50 * 1024 * 1024) return "medium";
	if (byteLength <= 500 * 1024 * 1024) return "large";
	return "huge";
}

function capabilityStatusSupportsReadiness(slot, status) {
	return (
		["task-supported", "feature-complete"].includes(status) ||
		(["foundation", "core"].includes(slot) && status === "profiled")
	);
}

function packagePathId(value) {
	const slug = value
		.toLowerCase()
		.replace(/[^a-z0-9._-]+/gu, "-")
		.replace(/^-+|-+$/gu, "");
	return slug.length === 0 ? "source" : slug;
}

function licenseExpressionUsesLocalRefs(licenseExpression) {
	return /\bLicenseRef-/u.test(licenseExpression ?? "");
}

function packageJsonLicenseField(pack) {
	return licenseExpressionUsesLocalRefs(pack.licenseExpression)
		? "SEE LICENSE IN LICENSE.generated.md"
		: pack.licenseExpression;
}

function urlBasename(value) {
	try {
		return path.basename(new URL(value).pathname);
	} catch {
		return path.basename(value);
	}
}

export function localLicenseEvidenceFilesForIds(
	sourceIds,
	snapshotIds,
	context,
) {
	const sources = sourceIds
		.map((sourceId) => context.sourceById.get(sourceId))
		.filter((source) => source !== undefined);
	const evidenceUrls = new Set(
		sources.flatMap((source) => source.licenseEvidence ?? []),
	);
	const evidenceBasenames = new Set([...evidenceUrls].map(urlBasename));
	const filesByPackagePath = new Map();
	for (const snapshotId of snapshotIds) {
		const snapshot = context.snapshotById.get(snapshotId);
		if (snapshot === undefined || !sourceIds.includes(snapshot.sourceId)) {
			continue;
		}
		for (const file of snapshot.files ?? []) {
			const basename = path.basename(file.path);
			const matchesLicenseName =
				/(^|[._-])(license|licence|copying|notice|copyright)([._-]|$)/iu.test(
					basename,
				);
			const matchesEvidenceBasename =
				evidenceBasenames.has(basename) && matchesLicenseName;
			if (!matchesLicenseName && !matchesEvidenceBasename) {
				continue;
			}
			const packagePath = `licenses/${packagePathId(snapshot.sourceId)}/${basename}`;
			filesByPackagePath.set(packagePath, {
				byteLength: file.byteLength,
				checksum: file.checksum,
				mediaType: file.mediaType,
				packagePath,
				snapshotId,
				sourceId: snapshot.sourceId,
				sourcePath: file.path,
				sourceUrl: file.sourceUrl,
			});
		}
	}
	return [...filesByPackagePath.values()].sort((left, right) =>
		left.packagePath.localeCompare(right.packagePath),
	);
}

const REQUIRED_PUBLISHABILITY_EVIDENCE = [
	"productionGradeSourceCoverage",
	"auditedLicense",
	"declaredScope",
	"conformanceEvidence",
	"generatedReports",
];

function missingPublishabilityEvidence(spec) {
	const evidence = spec.publishabilityEvidence ?? {};
	const missing = [];
	for (const field of REQUIRED_PUBLISHABILITY_EVIDENCE) {
		const value = evidence[field];
		if (Array.isArray(value)) {
			if (value.length === 0) missing.push(field);
			continue;
		}
		if (typeof value !== "string" || value.trim().length === 0) {
			missing.push(field);
		}
	}
	if (
		Array.isArray(evidence.generatedReports) &&
		!PACKAGE_REPORT_FILES.every((report) =>
			evidence.generatedReports.includes(report),
		)
	) {
		missing.push("generatedReports:standard-report-set");
	}
	return missing;
}

function publishabilityFor(spec, manifest, context) {
	const requested = spec.publishable === true;
	const reasons = [];
	const sourceIds = spec.sourceIds ?? spec.catalogSourceIds ?? [];
	const snapshotIds = spec.snapshotIds ?? spec.catalogSnapshotIds ?? [];
	if (!requested) {
		reasons.push("generated packs are non-publishable by default");
	}
	if (
		(spec.generationMode !== undefined &&
			spec.generationMode !== "source-backed") ||
		(spec.mode !== undefined && spec.mode !== "source-backed")
	) {
		reasons.push("only source-backed generated packs can be publishable");
	}
	if (spec.supportLevel === "sampled") {
		reasons.push("sampled support level is not production-grade");
	}
	if (spec.supportLevel === "artifact-backed") {
		reasons.push(
			"artifact-backed descriptors require local materialized payloads before publishability",
		);
	}
	if (
		spec.packageName.includes("demo") ||
		manifest.targets?.domains?.includes("demo") === true
	) {
		reasons.push("demo packs are validation outputs");
	}
	for (const slot of manifest.capabilitySlots ?? []) {
		if (slot.status === "sampled") {
			reasons.push(`capability slot ${slot.slot} is sampled`);
		}
		if (slot.status === "artifact-backed") {
			reasons.push(
				`capability slot ${slot.slot} is artifact-backed without local task-usable payloads`,
			);
		}
	}
	if (requested) {
		for (const missing of missingPublishabilityEvidence(spec)) {
			reasons.push(`missing publishability evidence: ${missing}`);
		}
		if (
			licenseExpressionUsesLocalRefs(manifest.license) &&
			localLicenseEvidenceFilesForIds(sourceIds, snapshotIds, context)
				.length === 0
		) {
			reasons.push(
				"LicenseRef package licenses require local snapshot license evidence files",
			);
		}
	}
	const uniqueReasons = sorted(new Set(reasons));
	const publishable = requested && uniqueReasons.length === 0;
	return {
		publishable,
		status: publishable ? "publishable" : "blocked",
		reasons: uniqueReasons,
	};
}

export function assertPublishabilityRequest(spec, manifest, context) {
	const publishability = publishabilityFor(spec, manifest, context);
	expect(
		spec.publishable !== true || publishability.publishable,
		`${spec.packageName} requested publishable output but failed the publishability gate.`,
		publishability.reasons.join("\n"),
	);
	return publishability;
}

function packagePublishFields(pack) {
	if (pack.publishable) {
		return {
			publishConfig: {
				access: "public",
			},
		};
	}
	return { private: true };
}

function publishabilityMarkdown(pack) {
	const reasons =
		pack.publishability.reasons.length === 0
			? "- None"
			: pack.publishability.reasons.map((reason) => `- ${reason}`).join("\n");
	return `## Publishability

Publishable: \`${pack.publishable ? "true" : "false"}\`
Status: \`${pack.publishability.status}\`

${reasons}
`;
}

function concretePackageJson(pack) {
	const packageJson = {
		name: pack.packageName,
		version: pack.packageVersion,
		description: pack.description,
		type: "module",
		sideEffects: false,
		exports: {
			".": {
				types: "./dist/index.d.ts",
				import: "./dist/index.js",
			},
			"./pack.manifest.json": "./pack.manifest.json",
		},
		scripts: {
			...PACKAGE_SCRIPTS,
			"test:all":
				"npm run -s build && node test/smoke.mjs && npm run -s check:pack",
		},
		dependencies: {
			"@ismail-elkorchi/textpack": "0.1.0",
		},
		license: packageJsonLicenseField(pack),
		files: [
			"dist",
			"pack.manifest.json",
			...pack.payloads.map((payload) => payload.path),
			".textpack-generated.json",
			...(pack.licenseEvidenceFiles.length === 0 ? [] : ["licenses"]),
			"LICENSE.generated.md",
			"NOTICE.generated.md",
			"SOURCES.generated.json",
			"ATTRIBUTION.generated.md",
			"COVERAGE.generated.json",
			"EVALUATION.generated.json",
			"QUALITY.generated.json",
			"README.md",
			"CHANGELOG.md",
		],
		...packagePublishFields(pack),
	};
	return jsonFile(packageJson);
}

function tsconfigJson() {
	return `{
\t"extends": "../../../tsconfig.json",
\t"compilerOptions": {
\t\t"noEmit": true,
\t\t"types": ["node"]
\t},
\t"include": ["src/**/*.ts"]
}
`;
}

function tsconfigBuildJson() {
	return `{
\t"extends": "./tsconfig.json",
\t"compilerOptions": {
\t\t"noEmit": false,
\t\t"declaration": true,
\t\t"declarationMap": true,
\t\t"sourceMap": true,
\t\t"outDir": "dist",
\t\t"rootDir": "src",
\t\t"allowImportingTsExtensions": false,
\t\t"paths": {}
\t},
\t"include": ["src/**/*.ts"]
}
`;
}

function concreteReadme(pack) {
	const resources = pack.manifest.resources
		.map(
			(resource) =>
				`- \`${resource.id}\` (${resource.kind}, ${resource.format})`,
		)
		.join("\n");
	const summary = isDistributionPack(pack)
		? `Generated self-contained ${pack.display.languageName} language textpack.`
		: `Generated ${pack.packClass} textpack.`;
	return `# ${pack.packageName}

${summary}

This package is a generated data package. It exports structural textpack data only.
Use \`@ismail-elkorchi/text-computing\` for developer-facing NLP task APIs.
It is generated from pinned source snapshots by \`${GENERATED_BY}\`.
${isDistributionPack(pack) ? "All resources are included directly; installing this package does not install component textpacks.\n" : ""}

\`\`\`ts
import pack, { manifest, resources } from "${pack.packageName}";

console.log(manifest.packageName);
console.log(Object.keys(resources).length);
console.log(pack.manifest.resources.length);
\`\`\`

## Resources

${resources}

${publishabilityMarkdown(pack)}
`;
}

function concreteChangelog(pack) {
	return `# ${pack.packageName}

## 0.1.0

- Generated ${isDistributionPack(pack) ? "self-contained language distribution" : "source-backed data package"}.
`;
}

function concreteSmokeTest(pack) {
	return `import assert from "node:assert/strict";
import pack, { manifest, resources } from "../dist/index.js";

const packageName = ${JSON.stringify(pack.packageName)};

assert.equal(manifest.packageName, packageName);
assert.equal(typeof resources, "object");
assert.equal(Object.keys(resources).length, manifest.resources.length);
assert.ok(manifest.resources.length > 0);
assert.deepEqual(pack.manifest, manifest);
assert.deepEqual(pack.resources, resources);

for (const resource of manifest.resources) {
\tconst value = resources[resource.id];
\tassert.equal(typeof value, "object");
\tassert.equal(value?.kind, "file-backed-resource");
\tassert.equal(value?.path, resource.path);
\tassert.equal(typeof value?.checksum, "string");
\tassert.equal(typeof value?.byteLength, "number");
\tassert.equal(typeof value?.encoding, "string");
\tassert.equal(typeof value?.lineCount, "number");
}
`;
}

function noticeMarkdown(pack, context) {
	const packageDescription = isDistributionPack(pack)
		? "This package is a self-contained language distribution. Its audited resource payloads are generated from pinned local source snapshots and shipped directly in this package; no component textpacks are installed."
		: pack.packClass === "language-composite"
			? "This is an internal source-backed composition recipe over selected build units. It is not a public textpack distribution."
			: "This package is source-backed. Its resource payloads are deterministic transform outputs from pinned local source snapshots. The normal forge build is offline and verifies input checksums before emitting package files.";
	return `# NOTICE

Generated by \`${GENERATED_BY}\`.

Package: \`${pack.packageName}\`
Mode: \`${context.mode}\`
Policy surface: \`${pack.policySurface ?? "default"}\`
Generated at: \`${context.generatedAt}\`
Publishable: \`${pack.publishable ? "true" : "false"}\`
Publishability status: \`${pack.publishability.status}\`

${packageDescription}

License expression: \`${pack.licenseExpression}\`
Source ids: ${pack.sourceIds.map((sourceId) => `\`${sourceId}\``).join(", ")}
Snapshot ids: ${pack.snapshotIds.map((snapshotId) => `\`${snapshotId}\``).join(", ")}

${licenseEvidenceMarkdown(pack, context)}

## Publishability Gate

${pack.publishability.reasons.map((reason) => `- ${reason}`).join("\n") || "- No blocking reasons."}
`;
}

function licenseEvidenceMarkdown(pack, context) {
	const sources = pack.sourceIds
		.map((sourceId) => context.sourceById.get(sourceId))
		.filter((source) => source !== undefined);
	const evidenceUrls = sorted(
		new Set(sources.flatMap((source) => source.licenseEvidence ?? [])),
	);
	const snapshots = pack.snapshotIds
		.map((snapshotId) => context.snapshotById.get(snapshotId))
		.filter((snapshot) => snapshot !== undefined);
	const localEvidenceFiles = sorted(
		new Set(
			snapshots.flatMap((snapshot) =>
				(snapshot.files ?? [])
					.filter(
						(file) =>
							/license/iu.test(file.path) ||
							(file.sourceUrl !== undefined &&
								evidenceUrls.includes(file.sourceUrl)),
					)
					.map((file) => `${file.path} (${file.checksum})`),
			),
		),
	);
	const sourceEvidence =
		evidenceUrls.length === 0
			? "- No source license evidence URLs declared."
			: evidenceUrls.map((url) => `- ${url}`).join("\n");
	const localEvidence =
		(pack.licenseEvidenceFiles ?? []).length > 0
			? pack.licenseEvidenceFiles
					.map(
						(file) =>
							`- \`${file.packagePath}\` from \`${file.sourcePath}\` (${file.checksum})`,
					)
					.join("\n")
			: localEvidenceFiles.length === 0
				? "- No local snapshot license files declared."
				: localEvidenceFiles.map((entry) => `- \`${entry}\``).join("\n");
	return `## License Evidence

Source evidence:

${sourceEvidence}

Local snapshot evidence:

${localEvidence}`;
}

async function licenseReportMarkdown(pack, context) {
	const sourceRows = pack.sourceIds
		.map((sourceId) => context.sourceById.get(sourceId))
		.filter((source) => source !== undefined)
		.map(
			(source) =>
				`- \`${source.sourceId}\`: \`${source.licenseExpression}\` (${source.redistributionPolicy})`,
		)
		.join("\n");
	const sourceEvidenceUrls = sorted(
		new Set(
			pack.sourceIds.flatMap(
				(sourceId) => context.sourceById.get(sourceId)?.licenseEvidence ?? [],
			),
		),
	);
	const sourceEvidence =
		sourceEvidenceUrls.length === 0
			? "- No source license evidence URLs declared."
			: sourceEvidenceUrls.map((url) => `- ${url}`).join("\n");
	const includedFiles =
		pack.licenseEvidenceFiles.length === 0
			? "- No package-local license evidence files were copied from snapshots."
			: pack.licenseEvidenceFiles
					.map(
						(file) =>
							`- \`${file.packagePath}\` from \`${file.sourcePath}\` (${file.checksum})`,
					)
					.join("\n");
	const localLicenseTexts = [];
	for (const file of pack.licenseEvidenceFiles) {
		const text = await readFile(path.join(ROOT, file.sourcePath), "utf8");
		localLicenseTexts.push(`### ${file.packagePath}

Source id: \`${file.sourceId}\`
Snapshot id: \`${file.snapshotId}\`
Checksum: \`${file.checksum}\`

\`\`\`text
${text.replaceAll("```", "\\`\\`\\`")}
\`\`\``);
	}
	const localTextSection =
		localLicenseTexts.length === 0
			? "No package-local license text is available for this generated package."
			: localLicenseTexts.join("\n\n");
	return `# License

Generated by \`${GENERATED_BY}\` at \`${context.generatedAt}\`.

Package: \`${pack.packageName}\`
Package.json license field: \`${packageJsonLicenseField(pack)}\`
Manifest license expression: \`${pack.licenseExpression}\`

## Source License Expressions

${sourceRows || "- No source license expressions declared."}

## Source License Evidence URLs

${sourceEvidence}

## Included Package License Files

${includedFiles}

## Included License Text

${localTextSection}
`;
}

function attributionMarkdown(pack, context) {
	const citations =
		pack.manifest.citations?.map((citation) => `- ${citation}`).join("\n") ??
		"- No citation entries declared.";
	return `# Attribution

Generated by \`${GENERATED_BY}\` at \`${context.generatedAt}\`.

Package: \`${pack.packageName}\`
License expression: \`${pack.licenseExpression}\`

## Sources

${pack.sourceIds.map((sourceId) => `- \`${sourceId}\``).join("\n")}

${licenseEvidenceMarkdown(pack, context)}

## Citations

${citations}
`;
}

function sourcesReportFor(pack, context) {
	const sources = pack.sourceIds.map((sourceId) =>
		context.sourceById.get(sourceId),
	);
	const sourcePolicies = pack.sourceIds.map((sourceId) =>
		context.sourcePolicyById.get(sourceId),
	);
	const snapshots = pack.snapshotIds.map((snapshotId) =>
		context.snapshotById.get(snapshotId),
	);
	return {
		schemaVersion: "1",
		generatedAt: context.generatedAt,
		generatedBy: GENERATED_BY,
		mode: context.mode,
		packageName: pack.packageName,
		packageId: pack.packageId,
		policySurface: pack.policySurface ?? "default",
		publishable: pack.publishable,
		publishability: pack.publishability,
		sourceIds: pack.sourceIds,
		snapshotIds: pack.snapshotIds,
		resourceSpecIds: pack.resourceSpecIds ?? [],
		sources,
		sourcePolicies,
		snapshots,
		buildUnits: pack.buildUnits ?? [],
		resources: pack.resourceStats.map((resource) => {
			const resourceSpec = context.resourceSpecById.get(
				resource.resourceSpecId,
			);
			const descriptor = pack.manifest.resources.find(
				(candidate) => candidate.id === resource.id,
			);
			return {
				id: resource.id,
				kind: resource.kind,
				path: resource.path,
				...(resource.resourceSpecId === undefined
					? {}
					: {
							resourceSpecId: resource.resourceSpecId,
							pipelineId: resource.pipelineId,
							pipelineVersion: resource.pipelineVersion,
						}),
				sourceIds: resourceSpec?.sourceIds ?? [],
				snapshotIds: resourceSpec?.snapshotIds ?? [],
				...(descriptor?.license === undefined
					? {}
					: { license: descriptor.license }),
				...(descriptor?.citations === undefined
					? {}
					: { citations: descriptor.citations }),
				checksum: resource.checksum,
				byteLength: resource.byteLength,
			};
		}),
	};
}

function assertFeatureCompleteLanguageCompositeEvidence(
	pack,
	evaluationRecords,
) {
	if (
		pack.packClass !== "language-composite" ||
		pack.supportLevel !== "feature-complete"
	) {
		return;
	}
	const evaluatedSlots = new Set(
		evaluationRecords
			.filter((record) => record.result === "pass")
			.map((record) => record.capabilitySlot),
	);
	for (const slot of languageDistributionRequiredSlots) {
		const declaredSlot = pack.capabilitySlots.find(
			(candidate) => candidate.slot === slot,
		);
		expect(
			capabilityStatusSupportsReadiness(slot, declaredSlot?.status) &&
				evaluatedSlots.has(slot),
			`${pack.packageName} is feature-complete but slot ${slot} lacks passing generated evaluation evidence.`,
		);
	}
}

export async function packageOutputsFor(pack, context) {
	const outputs = new Map();
	const evaluationReport = evaluationReportFor(pack, context);
	assertModelBackedEvidence(pack, evaluationReport.records);
	assertFeatureCompleteLanguageCompositeEvidence(
		pack,
		evaluationReport.records,
	);
	outputs.set(`${pack.packageDir}/package.json`, concretePackageJson(pack));
	outputs.set(`${pack.packageDir}/README.md`, concreteReadme(pack));
	outputs.set(`${pack.packageDir}/CHANGELOG.md`, concreteChangelog(pack));
	outputs.set(`${pack.packageDir}/tsconfig.json`, tsconfigJson());
	outputs.set(`${pack.packageDir}/tsconfig.build.json`, tsconfigBuildJson());
	outputs.set(`${pack.packageDir}/test/smoke.mjs`, concreteSmokeTest(pack));
	outputs.set(`${pack.packageDir}/pack.manifest.json`, jsonFile(pack.manifest));
	outputs.set(`${pack.packageDir}/src/index.ts`, indexModule());
	outputs.set(`${pack.packageDir}/src/pack.ts`, packModule());
	outputs.set(
		`${pack.packageDir}/src/manifest.ts`,
		manifestModule(pack.manifest),
	);
	outputs.set(`${pack.packageDir}/src/resources.ts`, resourcesModule(pack));
	for (const payload of pack.payloads) {
		outputs.set(`${pack.packageDir}/${payload.path}`, payload.text);
	}
	for (const licenseFile of pack.licenseEvidenceFiles ?? []) {
		outputs.set(
			`${pack.packageDir}/${licenseFile.packagePath}`,
			await readFile(path.join(ROOT, licenseFile.sourcePath), "utf8"),
		);
	}
	outputs.set(
		`${pack.packageDir}/LICENSE.generated.md`,
		await licenseReportMarkdown(pack, context),
	);
	outputs.set(
		`${pack.packageDir}/NOTICE.generated.md`,
		noticeMarkdown(pack, context),
	);
	outputs.set(
		`${pack.packageDir}/SOURCES.generated.json`,
		stableJson(sourcesReportFor(pack, context)),
	);
	outputs.set(
		`${pack.packageDir}/ATTRIBUTION.generated.md`,
		attributionMarkdown(pack, context),
	);
	outputs.set(
		`${pack.packageDir}/COVERAGE.generated.json`,
		stableJson(coverageReportFor(pack, context, evaluationReport.records)),
	);
	outputs.set(
		`${pack.packageDir}/EVALUATION.generated.json`,
		stableJson(evaluationReport),
	);
	outputs.set(
		`${pack.packageDir}/QUALITY.generated.json`,
		stableJson(qualityReportFor(pack, context)),
	);
	return outputs;
}

export function expectedGeneratedFilesForPack(pack) {
	const files = [
		"package.json",
		"README.md",
		"CHANGELOG.md",
		"tsconfig.json",
		"tsconfig.build.json",
		"test/smoke.mjs",
		"pack.manifest.json",
		"src/index.ts",
		"src/pack.ts",
		"src/manifest.ts",
		"src/resources.ts",
	];
	files.push(...pack.payloads.map((payload) => payload.path));
	files.push(
		...(pack.licenseEvidenceFiles ?? []).map((file) => file.packagePath),
	);
	files.push(...PACKAGE_REPORT_FILES);
	return sorted(new Set(files));
}

const developerFacingLanguageTags = ["en", "ar", "fr"];
export const languageDistributionRequiredSlots = [
	"foundation",
	"core",
	"normalization",
	"segmentation",
	"lexicon",
	"morphology",
	"kb",
	"search",
	"quality",
];
const languageReadinessSlotAliases = {
	foundation: ["language-registry", "locale-profile", "unicode-profile"],
	core: ["core", "language-core"],
	normalization: ["normalization"],
	segmentation: ["segmentation"],
	lexicon: ["lexicon", "lexical-semantics"],
	morphology: ["morphology", "tagging"],
	syntax: ["syntax", "tagging"],
	kb: ["kb", "lexical-semantics", "entity-linking"],
	search: ["search"],
	corpus: ["corpus"],
	parallel: ["parallel"],
	quality: ["quality"],
};
const languageReadinessSourceRequirements = {
	en: {
		lexicon: [
			{
				label: "ESDB exact audited English wordlist source",
				anySourceIds: ["source:esdb:wordlist-diff-en-default-2026-02-25"],
			},
			{
				label: "SCOWLv2 exact audited English inflection inventory source",
				anySourceIds: ["source:scowl:v2-rel-2026-02-25"],
			},
			{
				label: "Open English WordNet lexical-semantic source",
				anySourceIds: ["source:wordnet:open-english-2025"],
			},
		],
		morphology: [
			{
				label:
					"SCOWLv2 exact audited default-safe English lookup morphology source",
				anySourceIds: ["source:scowl:v2-rel-2026-02-25"],
			},
		],
		syntax: [
			{
				label: "audited exact UD English treebank source boundary",
				anySourceIds: ["source:ud:english-gumreddit-r2.18"],
			},
		],
		kb: [
			{
				label: "Open English WordNet lexical-semantic source",
				anySourceIds: ["source:wordnet:open-english-2025"],
			},
			{
				label:
					"Wikidata main structured data for entity labels, aliases, and KB links",
				anySourceIds: ["source:wikidata:main"],
			},
		],
		search: [
			{
				label: "ESDB exact audited English search-profile source",
				anySourceIds: ["source:esdb:wordlist-diff-en-default-2026-02-25"],
			},
		],
		corpus: [
			{
				label: "Tatoeba exact audited English corpus artifact source",
				anySourceIds: ["source:tatoeba:weekly-2026-06-06"],
			},
		],
		parallel: [
			{
				label: "Tatoeba exact audited English parallel artifact source",
				anySourceIds: ["source:tatoeba:weekly-2026-06-06"],
			},
		],
		quality: [
			{
				label:
					"English quality evidence must cover the audited lexicon/search source",
				anySourceIds: ["source:esdb:wordlist-diff-en-default-2026-02-25"],
			},
			{
				label:
					"English quality evidence must cover the audited morphology source",
				anySourceIds: ["source:scowl:v2-rel-2026-02-25"],
			},
			{
				label: "English quality evidence must cover the audited KB source",
				anySourceIds: ["source:wordnet:open-english-2025"],
			},
			{
				label: "English quality evidence must cover the audited entity source",
				anySourceIds: ["source:wikidata:main"],
			},
		],
	},
	ar: {
		lexicon: [
			{
				label: "Arabic WordNet exact audited lexical-semantic source",
				anySourceIds: ["source:wordnet:arabic-v4.1.0"],
			},
			{
				label: "CAMeL Morph exact audited Arabic MSA lexicon inventory source",
				anySourceIds: ["source:camel:morph-msa-lrec-coling-2024"],
			},
		],
		segmentation: [
			{
				label: "CAMeL Morph exact audited Arabic segmentation source",
				anySourceIds: ["source:camel:morph-msa-lrec-coling-2024"],
			},
		],
		morphology: [
			{
				label: "CAMeL Morph exact audited Arabic morphology source",
				anySourceIds: ["source:camel:morph-msa-lrec-coling-2024"],
			},
		],
		syntax: [
			{
				label:
					"audited exact UD Arabic treebank source boundary; audited PADT, PUD, and NYUAD rows are isolated or blocked and do not unlock default Arabic syntax",
				anySourceIds: [
					"source:ud:arabic-padt-r2.18",
					"source:ud:arabic-pud-r2.18",
					"source:ud:arabic-nyuad-r2.18",
				],
			},
		],
		kb: [
			{
				label: "Arabic WordNet exact audited lexical-semantic source",
				anySourceIds: ["source:wordnet:arabic-v4.1.0"],
			},
			{
				label:
					"Wikidata main structured data for Arabic entity labels, aliases, and KB links",
				anySourceIds: ["source:wikidata:main"],
			},
		],
		search: [
			{
				label: "CAMeL Morph exact audited Arabic MSA analyzer source",
				anySourceIds: ["source:camel:morph-msa-lrec-coling-2024"],
			},
			{
				label: "Arabic WordNet exact audited search expansion source",
				anySourceIds: ["source:wordnet:arabic-v4.1.0"],
			},
		],
		corpus: [
			{
				label: "Tatoeba exact audited Arabic corpus artifact source",
				anySourceIds: ["source:tatoeba:weekly-arabic-2026-06-06"],
			},
		],
		parallel: [
			{
				label: "Tatoeba exact audited Arabic parallel artifact source",
				anySourceIds: ["source:tatoeba:weekly-arabic-2026-06-06"],
			},
		],
		quality: [
			{
				label:
					"Arabic quality evidence must cover the audited morphology source",
				anySourceIds: ["source:camel:morph-msa-lrec-coling-2024"],
			},
			{
				label: "Arabic quality evidence must cover the audited KB source",
				anySourceIds: ["source:wordnet:arabic-v4.1.0"],
			},
			{
				label: "Arabic quality evidence must cover the audited entity source",
				anySourceIds: ["source:wikidata:main"],
			},
		],
	},
	fr: {
		lexicon: [
			{
				label:
					"audited exact French lexical source boundary; Morphalou and Lefff are isolated copyleft sources, and Lexique 3.83 is share-alike isolated",
				anySourceIds: [
					"source:fr:morphalou",
					"source:fr:lefff",
					"source:fr:lexique-383",
					"source:fr:lexique",
				],
			},
		],
		morphology: [
			{
				label:
					"audited exact French morphology source boundary; UniMorph French and Lexique 3.83 are share-alike isolated, while Morphalou and Lefff are copyleft isolated",
				anySourceIds: [
					"source:unimorph:french-master-f672f8c",
					"source:fr:morphalou",
					"source:fr:lefff",
					"source:fr:lexique-383",
					"source:fr:lexique",
				],
			},
		],
		syntax: [
			{
				label:
					"audited exact UD French treebank source boundary; audited ALTS, FQB, GSD, ParisStories, PoitevinDIVITAL, Rhapsodie, Spoken, PUD, Sequoia, and ParTUT rows are isolated or blocked and do not unlock default French syntax",
				anySourceIds: [
					"source:ud:french-alts-r2.18",
					"source:ud:french-fqb-r2.18",
					"source:ud:french-gsd-r2.18",
					"source:ud:french-sequoia-r2.18",
					"source:ud:french-parisstories-r2.18",
					"source:ud:french-rhapsodie-r2.18",
					"source:ud:french-spoken-r2.18",
					"source:ud:french-partut-r2.18",
					"source:ud:french-poitevindivital-r2.18",
					"source:ud:french-pud-r2.18",
				],
			},
		],
		kb: [
			{
				label:
					"Wikidata main structured data for French entity labels, aliases, and KB links",
				anySourceIds: ["source:wikidata:main"],
			},
		],
		search: [
			{
				label:
					"audited exact French search source boundary; Unicode/CLDR alone is not enough for full French search readiness",
				anySourceIds: [
					"source:fr:lexique-383",
					"source:fr:lexique",
					"source:fr:morphalou",
					"source:fr:lefff",
					"source:unimorph:french-master-f672f8c",
				],
			},
		],
		quality: [
			{
				label:
					"French quality evidence must wait for audited French lexicon source coverage",
				anySourceIds: [
					"source:fr:morphalou",
					"source:fr:lefff",
					"source:fr:lexique-383",
					"source:fr:lexique",
				],
			},
			{
				label:
					"French quality evidence must wait for audited French morphology source coverage",
				anySourceIds: [
					"source:unimorph:french-master-f672f8c",
					"source:fr:morphalou",
					"source:fr:lefff",
					"source:fr:lexique-383",
					"source:fr:lexique",
				],
			},
		],
	},
};

export function markerFor(pack, context) {
	return {
		schemaVersion: "1",
		generatedBy: GENERATED_BY,
		forgeVersion: context.forgeVersion,
		mode: context.mode,
		generatedAt: context.generatedAt,
		generatorCommand: BUILD_COMMAND,
		lockfile: LOCK_PATH,
		lockfileChecksum: context.lockfileChecksum,
		packageName: pack.packageName,
		packageVersion: pack.packageVersion,
		policySurface: pack.policySurface ?? "default",
		publishable: pack.publishable,
		publishability: pack.publishability,
		packSpecPath: pack.specPath ?? DEFAULT_PACK_SPEC_PATH,
		outputChecksum: pack.outputChecksum,
		generatedFiles: pack.generatedFiles,
		fileDigests: pack.fileDigests,
	};
}

export function inventoryFor(context) {
	return {
		schemaVersion: "1",
		generatedAt: context.generatedAt,
		generatedBy: GENERATED_BY,
		mode: context.mode,
		packages: context.packs.filter(isDistributionPack).map((pack) => ({
			packageId: pack.packageId,
			packageName: pack.packageName,
			version: pack.packageVersion,
			packClass: pack.packClass,
			policySurface: pack.policySurface ?? "default",
			supportLevel: pack.supportLevel,
			publishable: pack.publishable,
			publishability: pack.publishability,
			sourceIds: pack.sourceIds,
			snapshotIds: pack.snapshotIds,
			licenseExpression: pack.licenseExpression,
			npmShippedSizeBytes: pack.npmShippedSizeBytes,
			artifactBackedSizeBytes: pack.artifactBackedSizeBytes,
			artifactProfiles: pack.artifactProfiles,
			outputChecksum: pack.outputChecksum,
			generatedFiles: pack.generatedFiles,
			fileDigests: pack.fileDigests,
			reports: PACKAGE_REPORT_FILES,
			buildUnits: pack.buildUnits ?? [],
			capabilitySlots: pack.capabilitySlots.map((slot) => ({
				slot: slot.slot,
				status: slot.status,
				tier: slot.tier,
				...(slot.resourceIds === undefined
					? {}
					: { resourceIds: slot.resourceIds }),
				...(slot.artifactIds === undefined
					? {}
					: { artifactIds: slot.artifactIds }),
				...(slot.bindings === undefined ? {} : { bindings: slot.bindings }),
				...(slot.prerequisites === undefined
					? {}
					: { prerequisites: slot.prerequisites }),
				...(slot.readerRequired === undefined
					? {}
					: { readerRequired: slot.readerRequired }),
				...(slot.notes === undefined ? {} : { notes: slot.notes }),
				...(slot.capabilities === undefined
					? {}
					: { capabilities: slot.capabilities }),
			})),
			knownGaps: pack.knownGaps,
		})),
	};
}

export function inventoryMarkdown(inventory) {
	const lines = [
		"# Generated Textpack Inventory",
		"",
		"Status: three self-contained source-backed language distributions; forge build units are internal and are not npm packages",
		`Generated at: \`${inventory.generatedAt}\``,
		"",
		"| Package | Class | Support | Publishable | npm bytes | Artifact bytes | Slots | Reports | Known gaps |",
		"| --- | --- | --- | --- | ---: | ---: | --- | --- | --- |",
	];
	for (const pack of inventory.packages) {
		const slots = pack.capabilitySlots
			.map((slot) => `${slot.slot}:${slot.status}`)
			.join(", ");
		lines.push(
			`| \`${pack.packageName}\` | \`${pack.packClass}\` | \`${pack.supportLevel}\` | \`${pack.publishable ? "true" : "false"}\` | ${pack.npmShippedSizeBytes} | ${pack.artifactBackedSizeBytes} | ${slots} | ${pack.reports.map((report) => `\`${report}\``).join(", ")} | ${pack.knownGaps.join("; ")} |`,
		);
	}
	lines.push("");
	return `${lines.join("\n")}\n`;
}

function requiredLanguageSlotPackageName(languageTag) {
	return `@ismail-elkorchi/textpack-${languageTag}`;
}

function languageDisplayName(languageTag, context) {
	return (
		context.languagePolicyByTag.get(languageTag)?.languageName ?? languageTag
	);
}

function slotAliases(slot) {
	return languageReadinessSlotAliases[slot] ?? [slot];
}

function packSupportsLanguage(pack, languageTag) {
	return (pack.manifest.targets?.languages ?? []).includes(languageTag);
}

function packSupportsReadinessSlot(pack, slot) {
	const aliases = new Set(slotAliases(slot));
	return pack.capabilitySlots.some(
		(capabilitySlot) =>
			aliases.has(capabilitySlot.slot) &&
			capabilityStatusSupportsReadiness(slot, capabilitySlot.status),
	);
}

function standardReportsGenerated(pack) {
	const generatedFiles = new Set(pack.generatedFiles ?? []);
	return PACKAGE_REPORT_FILES.every((report) => generatedFiles.has(report));
}

function sourceAuditedForDefaultComposite(pack, context) {
	return pack.sourceIds.every((sourceId) => {
		const policy = context.sourcePolicyById.get(sourceId);
		if (isLicenseInclusiveDistribution(pack)) {
			return (
				policy !== undefined &&
				sourcePolicyAllowsLicenseInclusiveDistribution(policy)
			);
		}
		return (
			policy !== undefined &&
			policy.reviewState === "approved" &&
			policy.publishableByDefault === true &&
			policy.defaultCompositeAllowed === true &&
			publishableSourcePolicyClasses.has(policy.policyClass)
		);
	});
}

function sourceRequirementsFor(languageTag, slot) {
	return languageReadinessSourceRequirements[languageTag]?.[slot] ?? [];
}

function sourceRequirementSatisfied(requirement, sourceIds) {
	const sourceIdSet = new Set(sourceIds);
	if (Array.isArray(requirement.allSourceIds)) {
		return requirement.allSourceIds.every((sourceId) =>
			sourceIdSet.has(sourceId),
		);
	}
	if (Array.isArray(requirement.anySourceIds)) {
		return requirement.anySourceIds.some((sourceId) =>
			sourceIdSet.has(sourceId),
		);
	}
	return true;
}

function languageSlotSourceRequirementBlockers({
	exactPack,
	languageTag,
	slot,
}) {
	const requirements = sourceRequirementsFor(languageTag, slot);
	if (requirements.length === 0) return [];
	if (exactPack === undefined) {
		return requirements.map((requirement) => {
			const sourceIds = [
				...(requirement.allSourceIds ?? []),
				...(requirement.anySourceIds ?? []),
			];
			return `${requirement.label}; expected one of ${sourceIds.join(", ")} before full ${languageTag} ${slot} readiness can be marked ready.`;
		});
	}
	return requirements
		.filter(
			(requirement) =>
				!sourceRequirementSatisfied(requirement, exactPack.sourceIds),
		)
		.map((requirement) => {
			const sourceIds = [
				...(requirement.allSourceIds ?? []),
				...(requirement.anySourceIds ?? []),
			];
			return `${requirement.label} is required for full ${languageTag} ${slot} readiness; expected one of ${sourceIds.join(", ")}.`;
		});
}

function languageReadinessStage({
	adapterValid,
	artifactBacked,
	distributionReady,
	evaluated,
	exactPack,
	generated,
	publishable,
	schemaValid,
	sourceAudited,
	sourceRequirementsSatisfied,
}) {
	if (exactPack === undefined) return "missing";
	if (!sourceAudited) return generated ? "generated" : "missing";
	if (!generated) return "source-audited";
	if (!schemaValid) return "generated";
	if (!adapterValid) return "schema-valid";
	if (artifactBacked) return "artifact-backed";
	if (!evaluated) return "adapter-valid";
	if (!publishable) return "evaluated";
	if (!sourceRequirementsSatisfied) return "source-requirements-missing";
	if (!distributionReady) return "publishable";
	return "distribution-ready";
}

function languageSlotBlockers({
	adapterValid,
	artifactBacked,
	candidatePacks,
	distributionReady,
	evaluated,
	exactPack,
	generated,
	publishable,
	requiredPackageName,
	schemaValid,
	sourceAudited,
	sourceRequirementBlockers,
	sourceRequirementsSatisfied,
	standardReports,
	slot,
	slotCapabilitySatisfied,
}) {
	const blockers = [];
	if (exactPack === undefined) {
		blockers.push(`${requiredPackageName} has not been generated.`);
		if (candidatePacks.length > 0) {
			blockers.push(
				"Candidate internal build units exist, but no self-contained language distribution has selected them for this slot.",
			);
		}
		blockers.push(...sourceRequirementBlockers);
		return blockers;
	}
	if (!sourceAudited) {
		blockers.push(
			"source policy audit is incomplete for default distribution use.",
		);
	}
	if (!generated) blockers.push("generated package files are incomplete.");
	if (!schemaValid)
		blockers.push("manifest/resource schema validation is incomplete.");
	if (!standardReports)
		blockers.push("standard generated reports are incomplete.");
	if (!evaluated) blockers.push("evaluation evidence is incomplete.");
	if (!adapterValid) blockers.push("runtime adapter evidence is incomplete.");
	if (artifactBacked) {
		blockers.push(
			"slot is artifact-backed; descriptor-only metadata must be materialized into local task-usable payloads.",
		);
	}
	if (!publishable)
		blockers.push("package has not passed the publishability gate.");
	if (!sourceRequirementsSatisfied) {
		blockers.push(...sourceRequirementBlockers);
	}
	if (!slotCapabilitySatisfied) {
		blockers.push(
			`${requiredPackageName} does not declare production coverage for the ${slot} slot.`,
		);
	}
	if (!distributionReady && blockers.length === 0) {
		blockers.push("slot is not marked distribution-ready.");
	}
	return blockers;
}

export function languageDistributionReadinessFor(context) {
	const packageByName = new Map(
		context.packs.map((pack) => [pack.packageName, pack]),
	);
	return {
		schemaVersion: "1",
		generatedAt: context.generatedAt,
		generatedBy: GENERATED_BY,
		mode: context.mode,
		languages: developerFacingLanguageTags.map((languageTag) => {
			const slots = languageDistributionRequiredSlots.map((slot) => {
				const requiredPackageName = requiredLanguageSlotPackageName(
					languageTag,
					slot,
				);
				const exactPack = packageByName.get(requiredPackageName);
				const selectedBuildUnitNames = new Set(
					(exactPack?.components ?? [])
						.filter((component) => component.role === "required")
						.map((component) => component.packageName),
				);
				const candidatePacks = context.packs
					.filter(
						(pack) =>
							pack.packageName !== requiredPackageName &&
							pack.packClass !== "language-composite" &&
							(exactPack === undefined
								? packSupportsLanguage(pack, languageTag)
								: selectedBuildUnitNames.has(pack.packageName)) &&
							packSupportsReadinessSlot(pack, slot),
					)
					.map((pack) => ({
						buildUnitId: buildUnitIdForPackageName(pack.packageName),
						buildUnitClass: pack.packClass,
						publishable: pack.publishable,
						capabilitySlots: pack.capabilitySlots.map(
							(capabilitySlot) => capabilitySlot.slot,
						),
					}))
					.sort((left, right) =>
						left.buildUnitId.localeCompare(right.buildUnitId),
					);
				const sourceAudited =
					exactPack !== undefined &&
					sourceAuditedForDefaultComposite(exactPack, context);
				const generated =
					exactPack !== undefined &&
					typeof exactPack.outputChecksum === "string" &&
					exactPack.generatedFiles.length > 0;
				const schemaValid = exactPack !== undefined;
				const standardReports =
					exactPack !== undefined && standardReportsGenerated(exactPack);
				const evaluated =
					exactPack !== undefined &&
					standardReports &&
					exactPack.generatedFiles.includes("EVALUATION.generated.json");
				const adapterValid = exactPack !== undefined && standardReports;
				const publishable =
					exactPack !== undefined && exactPack.publishable === true;
				const exactSlot = exactPack?.capabilitySlots.find(
					(capabilitySlot) =>
						capabilitySlot.slot === slot ||
						slotAliases(slot).includes(capabilitySlot.slot),
				);
				const artifactBacked =
					exactPack?.supportLevel === "artifact-backed" ||
					exactSlot?.status === "artifact-backed";
				const slotCapabilitySatisfied =
					exactPack !== undefined && packSupportsReadinessSlot(exactPack, slot);
				const sourceRequirements = sourceRequirementsFor(languageTag, slot);
				const sourceRequirementBlockers = languageSlotSourceRequirementBlockers(
					{
						exactPack,
						languageTag,
						slot,
					},
				);
				const sourceRequirementsSatisfied =
					sourceRequirementBlockers.length === 0;
				const distributionReady =
					exactPack !== undefined &&
					sourceAudited &&
					generated &&
					schemaValid &&
					standardReports &&
					evaluated &&
					adapterValid &&
					publishable &&
					sourceRequirementsSatisfied &&
					slotCapabilitySatisfied;
				const state = {
					adapterValid,
					artifactBacked,
					distributionReady,
					evaluated,
					exactPack,
					generated,
					publishable,
					schemaValid,
					sourceAudited,
					sourceRequirementsSatisfied,
				};
				const blockers = languageSlotBlockers({
					...state,
					candidatePacks,
					requiredPackageName,
					sourceRequirementBlockers,
					standardReports,
					slot,
					slotCapabilitySatisfied,
				});
				return {
					slot,
					requiredPackageName,
					stage: languageReadinessStage(state),
					checks: {
						packagePresent: exactPack !== undefined,
						sourceAudited,
						generated,
						schemaValid,
						standardReports,
						adapterValid,
						artifactBacked,
						evaluated,
						publishable,
						sourceRequirementsSatisfied,
						slotCapabilitySatisfied,
						distributionReady,
					},
					capabilityAliases: slotAliases(slot),
					capabilitySlots:
						exactPack?.capabilitySlots.map((capabilitySlot) => ({
							slot: capabilitySlot.slot,
							status: capabilitySlot.status,
							tier: capabilitySlot.tier,
						})) ?? [],
					sourceIds: exactPack?.sourceIds ?? [],
					sourceRequirements,
					selectedBuildUnits: candidatePacks,
					blockers,
				};
			});
			const readySlots = slots.filter((slot) => slot.checks.distributionReady);
			const blockedSlots = slots.filter(
				(slot) => !slot.checks.distributionReady,
			);
			const distributionPackageName = `@ismail-elkorchi/textpack-${languageTag}`;
			return {
				languageTag,
				languageName: languageDisplayName(languageTag, context),
				distributionPackageName,
				distributionReady: blockedSlots.length === 0,
				summary: {
					requiredSlotCount: slots.length,
					readySlotCount: readySlots.length,
					blockedSlotCount: blockedSlots.length,
					readySlots: readySlots.map((slot) => slot.slot),
					blockedSlots: blockedSlots.map((slot) => slot.slot),
				},
				requiredSlots: slots,
			};
		}),
	};
}

export function validateDeveloperFacingDistributionPublishability(
	context,
	readiness,
) {
	const packageByName = new Map(
		context.packs.map((pack) => [pack.packageName, pack]),
	);
	for (const language of readiness.languages) {
		const pack = packageByName.get(language.distributionPackageName);
		if (pack?.publishable !== true) continue;
		expect(
			language.distributionReady === true,
			`${language.distributionPackageName} cannot be publishable until every required language slot is distribution-ready. Blocked slots: ${language.summary.blockedSlots.join(", ") || "none"}.`,
		);
	}
}

export function languageDistributionReadinessMarkdown(readiness) {
	const lines = [
		"# Language Distribution Readiness",
		"",
		`Generated at: \`${readiness.generatedAt}\``,
		"",
		"This report is generated from the active forge graph. It gates the self-contained `textpack-en`, `textpack-ar`, and `textpack-fr` distributions.",
		"",
		"A slot is ready only when the language distribution contains audited, evaluated, task-usable resources for it.",
		"",
		"## Summary",
		"",
		"| Language | Distribution | Ready slots | Blocked slots | Distribution ready |",
		"| --- | --- | ---: | --- | --- |",
	];
	for (const language of readiness.languages) {
		lines.push(
			`| \`${language.languageTag}\` ${markdownCell(language.languageName)} | \`${language.distributionPackageName}\` | ${language.summary.readySlotCount}/${language.summary.requiredSlotCount} | ${language.summary.blockedSlots.map((slot) => `\`${slot}\``).join(", ") || "None"} | \`${language.distributionReady ? "true" : "false"}\` |`,
		);
	}
	for (const language of readiness.languages) {
		lines.push(
			"",
			`## ${language.languageName} (${language.languageTag})`,
			"",
			"| Slot | Distribution | Stage | Selected build units | Blockers |",
			"| --- | --- | --- | --- | --- |",
		);
		for (const slot of language.requiredSlots) {
			lines.push(
				`| \`${slot.slot}\` | \`${slot.requiredPackageName}\` | \`${slot.stage}\` | ${slot.selectedBuildUnits.map((unit) => `\`${unit.buildUnitId}\``).join(", ") || "None"} | ${slot.blockers.map(markdownCell).join("<br>") || "None"} |`,
			);
		}
	}
	lines.push("");
	return `${lines.join("\n")}\n`;
}

export function sizeReportFor(context) {
	return {
		schemaVersion: "1",
		generatedAt: context.generatedAt,
		generatedBy: GENERATED_BY,
		mode: context.mode,
		limits: {
			tinyUnpackedBytes: 500 * 1024,
			smallUnpackedBytes: 5 * 1024 * 1024,
			mediumUnpackedBytes: 50 * 1024 * 1024,
			hugeUnpackedBytes: 500 * 1024 * 1024,
			compositePackedBytes: 500 * 1024,
		},
		packages: context.packs.filter(isDistributionPack).map((pack) => ({
			packageName: pack.packageName,
			packageDir: pack.packageDir,
			publishable: pack.publishable,
			publishability: pack.publishability,
			npmShippedSizeBytes: pack.npmShippedSizeBytes,
			artifactBackedSizeBytes: pack.artifactBackedSizeBytes,
			sizeClass: sizeClass(pack.npmShippedSizeBytes),
			outputChecksum: pack.outputChecksum,
			resources: pack.resourceStats,
		})),
	};
}

function countBy(values, selector) {
	const counts = {};
	for (const value of values) {
		const key = selector(value);
		counts[key] = (counts[key] ?? 0) + 1;
	}
	return sortJson(counts);
}

export function sourcePolicyGeneratedFor(context) {
	return {
		schemaVersion: "1",
		generatedAt: context.generatedAt,
		generatedBy: GENERATED_BY,
		mode: context.mode,
		policyIds: context.sourcePolicySpecs.map(
			(policySpec) => policySpec.policyId,
		),
		summaries: {
			sourceCount: context.sourcePolicies.length,
			languageCount: context.languagePolicies.length,
			activeSourceCount: context.sources.length,
			byPolicyClass: countBy(
				context.sourcePolicies,
				(policy) => policy.policyClass,
			),
			byReviewState: countBy(
				context.sourcePolicies,
				(policy) => policy.reviewState,
			),
			byPriority: countBy(context.sourcePolicies, (policy) => policy.priority),
		},
		licenseClasses: sourcePolicyClasses.map((policyClass) => ({
			class: policyClass,
			defaultCompositeAllowed:
				context.licenseClassByName.get(policyClass).defaultCompositeAllowed,
			publishableByDefault:
				context.licenseClassByName.get(policyClass).publishableByDefault,
			packageNameSuffixes:
				context.licenseClassByName.get(policyClass).packageNameSuffixes,
			description: context.licenseClassByName.get(policyClass).description,
		})),
		languages: context.languagePolicies.map((language) => ({
			languageTag: language.languageTag,
			languageName: language.languageName,
			firstSources: language.firstSources,
			secondWaveSources: language.secondWaveSources,
			isolatedSources: language.isolatedSources,
		})),
		sources: context.sourcePolicies.map((policy) => ({
			sourceId: policy.sourceId,
			family: policy.family,
			name: policy.name,
			policyClass: policy.policyClass,
			redistributionPolicy: policy.redistributionPolicy,
			reviewState: policy.reviewState,
			defaultCompositeAllowed: policy.defaultCompositeAllowed,
			publishableByDefault: policy.publishableByDefault,
			requiredPackageNameSuffixes: policy.requiredPackageNameSuffixes,
			languages: policy.languages,
			capabilitySlots: policy.capabilitySlots,
			priority: policy.priority,
			licenseExpression: policy.licenseExpression,
			homepageUrl: policy.homepageUrl,
			notes: policy.notes,
		})),
	};
}

function markdownCell(value) {
	return String(value ?? "")
		.replace(/\\/gu, "\\\\")
		.replace(/\|/gu, "\\|")
		.replace(/\r?\n/gu, " ")
		.trim();
}

function linkedSourceId(sourceId) {
	return `\`${sourceId}\``;
}

function sourcePolicySummaryCell(sourceIds, sourcePolicyById) {
	return sourceIds
		.map((sourceId) => {
			const policy = sourcePolicyById.get(sourceId);
			if (policy === undefined) return `${linkedSourceId(sourceId)}:unknown`;
			return `${linkedSourceId(sourceId)}:${policy.policyClass}/${policy.reviewState}`;
		})
		.join("<br>");
}

export function sourceReadinessMarkdown(context) {
	const lines = [
		"# Source Readiness",
		"",
		`Generated at: \`${context.generatedAt}\``,
		"",
		"This report is generated from the forge source-policy universe. It is metadata-only unless a source also appears in `sourcePaths`, `snapshotPaths`, and a resource spec.",
		"",
		"Policy rule: a source may not generate a pack until its policy class, package name, composite license policy, publishability gate, and source review state all agree.",
		"",
		"## License Classes",
		"",
		"| Class | Default composite | Publishable by default | Required suffixes | Source count |",
		"| --- | --- | --- | --- | ---: |",
	];
	const countsByClass = new Map(
		Object.entries(
			countBy(context.sourcePolicies, (policy) => policy.policyClass),
		),
	);
	for (const policyClass of sourcePolicyClasses) {
		const definition = context.licenseClassByName.get(policyClass);
		lines.push(
			`| \`${policyClass}\` | \`${definition.defaultCompositeAllowed ? "true" : "false"}\` | \`${definition.publishableByDefault ? "true" : "false"}\` | ${definition.packageNameSuffixes.map((suffix) => `\`${suffix}\``).join(", ") || "None"} | ${countsByClass.get(policyClass) ?? 0} |`,
		);
	}
	lines.push(
		"",
		"## Language Priorities",
		"",
		"| Language | First sources | Second wave | Isolated / review-only |",
		"| --- | --- | --- | --- |",
	);
	for (const languageTag of requiredSourcePolicyLanguageTags) {
		const language = context.languagePolicyByTag.get(languageTag);
		lines.push(
			`| \`${language.languageTag}\` ${markdownCell(language.languageName)} | ${sourcePolicySummaryCell(language.firstSources, context.sourcePolicyById)} | ${sourcePolicySummaryCell(language.secondWaveSources, context.sourcePolicyById)} | ${sourcePolicySummaryCell(language.isolatedSources, context.sourcePolicyById)} |`,
		);
	}
	lines.push(
		"",
		"## Source Catalog",
		"",
		"| Source | Family | Policy | Review | Priority | Default composite | Publishable source posture | Languages | Capabilities | Notes |",
		"| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
	);
	for (const policy of context.sourcePolicies) {
		lines.push(
			`| ${linkedSourceId(policy.sourceId)} | \`${markdownCell(policy.family)}\` | \`${policy.policyClass}\` | \`${policy.reviewState}\` | \`${policy.priority}\` | \`${policy.defaultCompositeAllowed ? "true" : "false"}\` | \`${policy.publishableByDefault ? "true" : "false"}\` | ${policy.languages.map((language) => `\`${language}\``).join(", ")} | ${policy.capabilitySlots.map((slot) => `\`${slot}\``).join(", ")} | ${markdownCell(policy.notes)} |`,
		);
	}
	lines.push("");
	return `${lines.join("\n")}\n`;
}
