// Generated by tools/textpack-forge. Do not edit.

export { manifest } from "./manifest.js";
export { resources } from "./resources.js";

import {
	loadPack,
	type ResolveTextPackComponentsOptions,
	resolvePackComponents,
	type TextPackComponent,
} from "@ismail-elkorchi/textpack";
import { manifest } from "./manifest.js";
import { resources } from "./resources.js";

export interface LoadArabicOptions
	extends Omit<ResolveTextPackComponentsOptions, "resolveComponent"> {
	readonly resolveComponent?: ResolveTextPackComponentsOptions["resolveComponent"];
}

async function resolveGeneratedComponent(
	component: TextPackComponent,
	options: LoadArabicOptions,
): Promise<unknown> {
	void options;
	switch (component.packageName) {
		case "@ismail-elkorchi/textpack-foundation": {
			const module = await import(component.packageName);
			const loader = module.loadFoundation;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadFoundation.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-ar-core":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-ar-normalization":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-ar-segmentation": {
			const module = await import(component.packageName);
			const loader = module.loadArabicSegmentation;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadArabicSegmentation.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-ar-lexicon": {
			const module = await import(component.packageName);
			const loader = module.loadArabicLexicon;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadArabicLexicon.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-ar-morphology": {
			const module = await import(component.packageName);
			const loader = module.loadArabicMorphology;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadArabicMorphology.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-ar-syntax": {
			const module = await import(component.packageName);
			const loader = module.loadArabicSyntax;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadArabicSyntax.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-ar-kb": {
			const module = await import(component.packageName);
			const loader = module.loadArabicKnowledgeBase;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadArabicKnowledgeBase.`,
				);
			}
			return loader(options);
		}
		case "@ismail-elkorchi/textpack-ar-search":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-ar-corpus":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-ar-parallel":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-ar-quality": {
			const module = await import(component.packageName);
			const loader = module.loadArabicQuality;
			if (typeof loader !== "function") {
				throw new TypeError(
					`Generated component resolver for ${component.packageName} did not export loadArabicQuality.`,
				);
			}
			return loader(options);
		}
		default:
			throw new TypeError(
				`No generated resolver entry for ${component.packageName}.`,
			);
	}
}

export async function loadArabic(options: LoadArabicOptions = {}) {
	return resolvePackComponents(await loadPack({ manifest, resources }), {
		...options,
		licensePolicy: options.licensePolicy ?? "allow-share-alike",
		artifactPolicy: options.artifactPolicy ?? "fetch-explicit",
		conflictPolicy: options.conflictPolicy ?? "first",
		resolveComponent:
			options.resolveComponent ??
			((component) => resolveGeneratedComponent(component, options)),
	});
}

export default { manifest, resources, loadArabic };
