import assert from "node:assert/strict";
import test from "node:test";
import {
	indexModule,
	manifestModule,
	packModule,
	resourcesModule,
} from "../lib/emission.mjs";

test("generated pack entrypoints contain only local data composition", () => {
	assert.equal(
		packModule(),
		`// Generated by tools/textpack-forge. Do not edit.\n\nimport { manifest } from "./manifest.js";\nimport { resources } from "./resources.js";\n\nexport const pack = { manifest, resources } as const;\n`,
	);
	for (const output of [
		indexModule(),
		packModule(),
		manifestModule({ id: "test" }),
		resourcesModule({ payloads: [] }),
	]) {
		assert.doesNotMatch(output, /@ismail-elkorchi\/|createPack|\n\n\n/);
	}
});

test("resource modules preserve descriptors without adding loaders or dependencies", () => {
	const output = resourcesModule({
		packageName: "@example/pack",
		payloads: [
			{
				id: "words",
				path: "data/words.json",
				encoded: "utf8",
				checksum: "sha256:abc",
				byteLength: 2,
				resourceTextByteLength: 2,
				lineCount: 1,
				nonEmptyLineCount: 1,
			},
		],
	});
	assert.match(output, /new URL\("\.\.\/", import.meta.url\).href/);
	assert.match(output, /"path": "data\/words.json"/);
	assert.doesNotMatch(output, /import .+ from|function |=>|fetch\(/);
});
