// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:fr-kb",
	"name": "French Knowledge Base Composite Textpack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-fr-kb",
	"targets": {
		"languages": [
			"fr"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [],
	"components": [
		{
			"packageName": "@ismail-elkorchi/textpack-wikidata-fr",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Default French Wikidata entity labels, aliases, relations, and ontology artifact descriptor.",
			"licensePolicy": "default",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "fetch-explicit"
		}
	],
	"capabilitySlots": [
		{
			"slot": "kb",
			"status": "artifact-backed",
			"notes": [
				"The required component graph provides French Wikidata entity labels, aliases, relations, and ontology artifact descriptors.",
				"WOLF/OMW French wordnet resources are CeCILL-C isolated and are not part of this default KB component.",
				"Descriptor-only artifact metadata does not satisfy task-supported readiness until local generated rows, extracts, indexes, or databases are materialized."
			]
		},
		{
			"slot": "quality",
			"status": "artifact-backed",
			"notes": [
				"Generated component reports and evaluation records are available for the required KB component.",
				"Descriptor-only artifact metadata does not satisfy task-supported readiness until local generated rows, extracts, indexes, or databases are materialized."
			]
		}
	],
	"license": "CC0-1.0",
	"citations": [
		"Wikidata main structured data dump, 2026-06-08."
	],
	"gapNotes": [
		{
			"id": "gap:pack:fr-kb:kb",
			"slot": "kb",
			"status": "artifact-backed",
			"message": "kb is artifact-backed in this source-backed recipe composite pack."
		},
		{
			"id": "gap:pack:fr-kb:quality",
			"slot": "quality",
			"status": "artifact-backed",
			"message": "quality is artifact-backed in this source-backed recipe composite pack."
		}
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
