// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:ar-sa",
	"name": "Arabic Share-Alike Developer Composite Textpack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-ar-sa",
	"targets": {
		"languages": [
			"ar"
		],
		"scripts": [
			"Arab"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [],
	"components": [
		{
			"packageName": "@ismail-elkorchi/textpack-foundation",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Default Unicode, CLDR, and BCP 47 foundation resources.",
			"licensePolicy": "default",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-ar-core",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Arabic core language profile resources.",
			"licensePolicy": "default",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-ar-normalization",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Arabic MSA normalization policy and quality resources.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-ar-segmentation",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Arabic MSA segmentation profiles.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-ar-lexicon",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Arabic MSA lexicon resources.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-ar-morphology",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Arabic MSA morphology resources.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-ar-syntax-sa",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Share-alike isolated Arabic UD-derived syntax and tagging resources.",
			"licensePolicy": "allow-share-alike",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-ar-kb",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Arabic WordNet lexical-semantic resources and Wikidata entity artifact descriptors.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "fetch-explicit"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-ar-search",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Arabic MSA search analyzer profile resources.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-ar-corpus",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Arabic promoted Tatoeba corpus artifact descriptors and quality evidence.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "fetch-explicit"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-ar-parallel",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Arabic promoted Tatoeba parallel artifact descriptors and quality evidence.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "fetch-explicit"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-ar-quality-sa",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Arabic generated quality evidence over the required policy-expanded component graph.",
			"licensePolicy": "allow-share-alike",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		}
	],
	"capabilitySlots": [
		{
			"slot": "foundation",
			"status": "task-supported"
		},
		{
			"slot": "core",
			"status": "task-supported"
		},
		{
			"slot": "normalization",
			"status": "task-supported"
		},
		{
			"slot": "segmentation",
			"status": "task-supported"
		},
		{
			"slot": "lexicon",
			"status": "task-supported"
		},
		{
			"slot": "morphology",
			"status": "task-supported"
		},
		{
			"slot": "syntax",
			"status": "task-supported"
		},
		{
			"slot": "kb",
			"status": "task-supported"
		},
		{
			"slot": "search",
			"status": "task-supported"
		},
		{
			"slot": "corpus",
			"status": "task-supported"
		},
		{
			"slot": "parallel",
			"status": "task-supported"
		},
		{
			"slot": "quality",
			"status": "task-supported"
		}
	],
	"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry AND CC-BY-4.0 AND CC0-1.0 AND CC-BY-2.0-FR AND CC-BY-SA-4.0",
	"citations": [
		"IANA Language Subtag Registry, File-Date 2026-05-05.",
		"Unicode Character Database 17.0.0.",
		"Unicode CLDR core data, cldr-core npm package 48.2.0.",
		"CAMeL Morph MSA LREC-COLING 2024 release.",
		"Arabic WordNet 4.1.0.",
		"Wikidata main structured data dump, 2026-06-08.",
		"Tatoeba weekly Arabic exports, 2026-06-06.",
		"Universal Dependencies Arabic NYUAD r2.18 annotations."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
