// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"en-normalization-rules": {"byteLength":443,"checksum":"sha256:7162c5b9d2b2234ce8c44fe8432e995f42d39c585c0d9ad86fdc65cc0dd1b7a9","encoding":"utf8","kind":"file-backed-resource","lineCount":5,"nonEmptyLineCount":4,"path":"resources/en.normalization-rules.tsv","resourceTextByteLength":443},
	"en-normalization-profile": {"byteLength":1532,"checksum":"sha256:7bff0c8f82389849ee811fff868ce9c7f76e888d70bd88e67372b899d00a59ff","encoding":"utf8","kind":"file-backed-resource","lineCount":53,"nonEmptyLineCount":52,"path":"resources/en.normalization.json","resourceTextByteLength":1532},
	"en-normalization-quality": {"byteLength":825,"checksum":"sha256:f4c43f23f3afccf79bb291b27dd527c818054b398c14365d311d191d0947883e","encoding":"utf8","kind":"file-backed-resource","lineCount":31,"nonEmptyLineCount":30,"path":"resources/en.normalization.quality.json","resourceTextByteLength":825},
	"en-normalization-quality-profile": {"byteLength":1184,"checksum":"sha256:2b998774efaf4f4b045f3567365aaf47ced790d0603087f00216bfbe4768faa8","encoding":"utf8","kind":"file-backed-resource","lineCount":51,"nonEmptyLineCount":50,"path":"resources/en.normalization.quality-profile.json","resourceTextByteLength":1184},
} as const;
