// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"wordnet-ar-lexical-entries": {"byteLength":5814865,"checksum":"sha256:4254fb7dcd9bfa0a3b5b4d9512840a153970d9abdca1c0758d751a649eee74c5","encoding":"utf8","kind":"file-backed-resource","lineCount":136043,"nonEmptyLineCount":136042,"path":"resources/wordnet-ar.lexical-entries.tsv","resourceTextByteLength":5814865},
	"wordnet-ar-senses": {"byteLength":14091110,"checksum":"sha256:76cc757aba2da2646b7f285a4c829f310464d988410265eae4a6d1326791c220","encoding":"utf8","kind":"file-backed-resource","lineCount":184240,"nonEmptyLineCount":184239,"path":"resources/wordnet-ar.senses.tsv","resourceTextByteLength":14091110},
	"wordnet-ar-synsets": {"byteLength":14041525,"checksum":"sha256:2022730099d05091854ab45420787472e1aebbde2e8fcab92580247778bf6569","encoding":"utf8","kind":"file-backed-resource","lineCount":120632,"nonEmptyLineCount":120631,"path":"resources/wordnet-ar.synsets.tsv","resourceTextByteLength":14041525},
	"wordnet-ar-relations": {"byteLength":14510261,"checksum":"sha256:8b0a9afd6e9dfb393eca5f0959481553f27374d2509746ac4c6505675baf9e7d","encoding":"utf8","kind":"file-backed-resource","lineCount":297152,"nonEmptyLineCount":297151,"path":"resources/wordnet-ar.relations.tsv","resourceTextByteLength":14510261},
	"wordnet-ar-quality": {"byteLength":1207,"checksum":"sha256:ccc8e95b79a9be634efdd4d76dd9b3e6483ec5b70a7c0c46ae8e5629dfd0a046","encoding":"utf8","kind":"file-backed-resource","lineCount":46,"nonEmptyLineCount":45,"path":"resources/wordnet-ar.quality.json","resourceTextByteLength":1207},
	"wordnet-ar-lexicon-canonical": {"byteLength":292,"checksum":"sha256:7074f09d301beb8bd3cefb472574dfcb90d29c0b9ea762a34b8c91e954090b18","encoding":"utf8","kind":"file-backed-resource","lineCount":16,"nonEmptyLineCount":15,"path":"resources/wordnet-ar.lexicon.json","resourceTextByteLength":292},
	"wordnet-ar-kb-canonical": {"byteLength":518,"checksum":"sha256:682ff3f41f8947e9cbbc6837113c720f28155bdb0311d5f6d618f89ea2023b90","encoding":"utf8","kind":"file-backed-resource","lineCount":28,"nonEmptyLineCount":27,"path":"resources/wordnet-ar.kb.json","resourceTextByteLength":518},
	"wordnet-ar-quality-profile": {"byteLength":876,"checksum":"sha256:08b8157d6ea3f692751131a51219d318f301b077575d6fa72dab158a7e89b04a","encoding":"utf8","kind":"file-backed-resource","lineCount":41,"nonEmptyLineCount":40,"path":"resources/wordnet-ar.quality-profile.json","resourceTextByteLength":876},
} as const;
