// Generated by tools/textpack-forge. Do not edit.

import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import type { PackResourceMap } from "@ismail-elkorchi/textpack";

const resourceRoot = new URL("../resources/", import.meta.url);

async function readResource(
	resourcePath: string,
	encoding: "gzip-base64" | "utf8",
): Promise<string> {
	const text = await readFile(new URL(resourcePath, resourceRoot), "utf8");
	if (encoding === "utf8") return text;
	return gunzipSync(Buffer.from(text.trim(), "base64")).toString("utf8");
}

export async function resources(): Promise<PackResourceMap> {
	// biome-ignore format: generated resource map preserves deterministic resource ordering.
	return {
		"wordnet-ar-lexical-entries": await readResource(
			"wordnet-ar.lexical-entries.tsv",
			"utf8",
		),
		"wordnet-ar-senses": await readResource(
			"wordnet-ar.senses.tsv",
			"utf8",
		),
		"wordnet-ar-synsets": await readResource(
			"wordnet-ar.synsets.tsv",
			"utf8",
		),
		"wordnet-ar-relations": await readResource(
			"wordnet-ar.relations.tsv",
			"utf8",
		),
		"wordnet-ar-quality": await readResource(
			"wordnet-ar.quality.json",
			"utf8",
		),
		"wordnet-ar-lexicon-canonical": await readResource(
			"wordnet-ar.lexicon.json",
			"utf8",
		),
		"wordnet-ar-kb-canonical": await readResource(
			"wordnet-ar.kb.json",
			"utf8",
		),
		"wordnet-ar-quality-profile": await readResource(
			"wordnet-ar.quality-profile.json",
			"utf8",
		),
	};
}
