// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:fr-normalization",
	"name": "French Normalization Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-fr-normalization",
	"targets": {
		"languages": [
			"fr"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "fr-normalization-rules",
			"kind": "normalization-profile",
			"path": "resources/fr.normalization-rules.tsv",
			"format": "tsv",
			"license": "Unicode-3.0 AND CC-BY-2.0-FR",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"Tatoeba weekly French exports, 2026-06-06."
			],
			"schemaId": "textnorm.rules.v1"
		},
		{
			"id": "fr-normalization-profile",
			"kind": "normalization-profile",
			"path": "resources/fr.normalization.json",
			"format": "json",
			"license": "Unicode-3.0 AND CC-BY-2.0-FR",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"Tatoeba weekly French exports, 2026-06-06."
			],
			"schemaId": "textnorm.profile.v1"
		},
		{
			"id": "fr-normalization-elision-prefixes",
			"kind": "normalization-profile",
			"path": "resources/fr.normalization-elision-prefixes.tsv",
			"format": "tsv",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly French exports, 2026-06-06."
			],
			"schemaId": "textnorm.rules.v1"
		},
		{
			"id": "fr-normalization-contraction-forms",
			"kind": "normalization-profile",
			"path": "resources/fr.normalization-contraction-forms.tsv",
			"format": "tsv",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly French exports, 2026-06-06."
			],
			"schemaId": "textnorm.rules.v1"
		},
		{
			"id": "fr-normalization-gold-cases",
			"kind": "quality-profile",
			"path": "resources/fr.normalization-gold-cases.json",
			"format": "json",
			"license": "CC-BY-2.0-FR",
			"citations": [
				"Tatoeba weekly French exports, 2026-06-06."
			],
			"schemaId": "textquality.evidence.v1"
		},
		{
			"id": "fr-normalization-quality",
			"kind": "quality-profile",
			"path": "resources/fr.normalization.quality.json",
			"format": "json",
			"license": "Unicode-3.0 AND CC-BY-2.0-FR",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"Tatoeba weekly French exports, 2026-06-06."
			],
			"schemaId": "textquality.evidence.v1"
		},
		{
			"id": "fr-normalization-quality-profile",
			"kind": "quality-profile",
			"path": "resources/fr.normalization.quality-profile.json",
			"format": "json",
			"license": "Unicode-3.0 AND CC-BY-2.0-FR",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"Tatoeba weekly French exports, 2026-06-06."
			],
			"schemaId": "textquality.profile.v1"
		}
	],
	"capabilitySlots": [
		{
			"slot": "normalization",
			"status": "task-supported",
			"resourceIds": [
				"fr-normalization-rules",
				"fr-normalization-profile",
				"fr-normalization-elision-prefixes",
				"fr-normalization-contraction-forms",
				"fr-normalization-gold-cases"
			],
			"bindings": [
				{
					"role": "profile",
					"resourceId": "fr-normalization-profile",
					"schemaId": "textnorm.profile.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textnorm"
				},
				{
					"role": "table",
					"resourceId": "fr-normalization-contraction-forms",
					"schemaId": "textnorm.rules.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textnorm"
				},
				{
					"role": "table",
					"resourceId": "fr-normalization-elision-prefixes",
					"schemaId": "textnorm.rules.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textnorm"
				},
				{
					"role": "table",
					"resourceId": "fr-normalization-rules",
					"schemaId": "textnorm.rules.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textnorm"
				},
				{
					"role": "evidence",
					"resourceId": "fr-normalization-gold-cases",
					"schemaId": "textquality.evidence.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textquality"
				}
			],
			"readerRequired": true,
			"notes": [
				"Unicode/CLDR-backed NFC and lookup casefold policy plus Tatoeba-observed apostrophe, elision-prefix, contraction-surface, accent-fold, and gold-case resources for modern typed French text."
			],
			"capabilities": {
				"normalization": "rules"
			}
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"fr-normalization-quality",
				"fr-normalization-quality-profile",
				"fr-normalization-gold-cases"
			],
			"bindings": [
				{
					"role": "evidence",
					"resourceId": "fr-normalization-gold-cases",
					"schemaId": "textquality.evidence.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textquality"
				},
				{
					"role": "evidence",
					"resourceId": "fr-normalization-quality",
					"schemaId": "textquality.evidence.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textquality"
				},
				{
					"role": "quality",
					"resourceId": "fr-normalization-quality-profile",
					"schemaId": "textquality.profile.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textquality"
				}
			],
			"readerRequired": true,
			"notes": [
				"Generated quality profile records source coverage, accepted records, observed French surface-policy counts, and gold-case coverage."
			]
		}
	],
	"license": "Unicode-3.0 AND CC-BY-2.0-FR",
	"citations": [
		"Unicode Character Database 17.0.0.",
		"Unicode CLDR core data, cldr-core npm package 48.2.0.",
		"Tatoeba weekly French exports, 2026-06-06."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
