// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:en-search",
	"name": "English Search Composite Textpack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-en-search",
	"targets": {
		"languages": [
			"en"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [],
	"components": [
		{
			"packageName": "@ismail-elkorchi/textpack-en-wordlist-esdb",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Default English regional spelling wordlists and spelling-aware analyzer profile.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		}
	],
	"capabilitySlots": [
		{
			"slot": "search",
			"status": "task-supported",
			"notes": [
				"The required component graph provides an English spelling-aware analyzer profile backed by ESDB default regional wordlists."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"notes": [
				"Generated component reports and evaluation records are available for the required search component."
			]
		}
	],
	"license": "LicenseRef-ESDB-MIT-Like",
	"citations": [
		"English Speller Database generated wordlist outputs, rel-2026.02.25."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
