// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:en-kb",
	"name": "English Knowledge Base Composite Textpack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-en-kb",
	"targets": {
		"languages": [
			"en"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [],
	"components": [
		{
			"packageName": "@ismail-elkorchi/textpack-wordnet-en",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Default English lexical-semantic WordNet KB resources.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-wikidata-en",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Default English Wikidata entity labels, aliases, relations, and ontology artifact descriptor.",
			"licensePolicy": "default",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "fetch-explicit"
		}
	],
	"capabilitySlots": [
		{
			"slot": "kb",
			"status": "task-supported",
			"notes": [
				"The required component graph provides English WordNet synsets, senses, lexical entries, semantic relations, and Wikidata entity artifact descriptors."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"notes": [
				"Generated component reports and evaluation records are available for the required KB component."
			]
		}
	],
	"license": "LicenseRef-Princeton-WordNet AND CC-BY-4.0 AND CC0-1.0",
	"citations": [
		"Open English WordNet 2025.",
		"Wikidata main structured data dump, 2026-06-08."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
