// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:fr-sa",
	"name": "French Share-Alike Developer Composite Textpack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-fr-sa",
	"targets": {
		"languages": [
			"fr"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [],
	"components": [
		{
			"packageName": "@ismail-elkorchi/textpack-foundation",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Default Unicode, CLDR, and BCP 47 foundation resources.",
			"licensePolicy": "default",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-fr-core",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "French core language profile resources.",
			"licensePolicy": "default",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-fr-normalization",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "French normalization policy and quality resources.",
			"licensePolicy": "default",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-fr-segmentation",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "French segmentation profiles.",
			"licensePolicy": "default",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-fr-lexicon-sa",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Share-alike isolated French lexicon resources.",
			"licensePolicy": "allow-share-alike",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-fr-morphology-sa",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Share-alike isolated French morphology resources.",
			"licensePolicy": "allow-share-alike",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-fr-syntax-sa",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Share-alike isolated French UD-derived syntax and tagging resources.",
			"licensePolicy": "allow-share-alike",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-fr-kb",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "French Wikidata entity artifact descriptors.",
			"licensePolicy": "default",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "fetch-explicit"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-fr-search-sa",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Share-alike isolated French search analyzer profile resources.",
			"licensePolicy": "allow-share-alike",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-fr-corpus",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "French promoted Tatoeba corpus artifact descriptors and quality evidence.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "fetch-explicit"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-fr-parallel",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "French promoted Tatoeba parallel artifact descriptors and quality evidence.",
			"licensePolicy": "allow-attribution",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "fetch-explicit"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-fr-quality-sa",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "French generated quality evidence over the required policy-expanded component graph.",
			"licensePolicy": "allow-share-alike",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "none"
		}
	],
	"capabilitySlots": [
		{
			"slot": "foundation",
			"status": "task-supported"
		},
		{
			"slot": "core",
			"status": "task-supported"
		},
		{
			"slot": "normalization",
			"status": "task-supported"
		},
		{
			"slot": "segmentation",
			"status": "task-supported"
		},
		{
			"slot": "lexicon",
			"status": "task-supported"
		},
		{
			"slot": "morphology",
			"status": "task-supported"
		},
		{
			"slot": "syntax",
			"status": "task-supported"
		},
		{
			"slot": "kb",
			"status": "task-supported"
		},
		{
			"slot": "search",
			"status": "task-supported"
		},
		{
			"slot": "corpus",
			"status": "task-supported"
		},
		{
			"slot": "parallel",
			"status": "task-supported"
		},
		{
			"slot": "quality",
			"status": "task-supported"
		}
	],
	"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry AND CC0-1.0 AND CC-BY-2.0-FR AND CC-BY-SA-4.0 AND CC-BY-SA-3.0",
	"citations": [
		"IANA Language Subtag Registry, File-Date 2026-05-05.",
		"Unicode Character Database 17.0.0.",
		"Unicode CLDR core data, cldr-core npm package 48.2.0.",
		"Wikidata main structured data dump, 2026-06-08.",
		"Tatoeba weekly French exports, 2026-06-06.",
		"Lexique 3.83, 2019-06-04.",
		"UniMorph French repository, commit f672f8cceb2d5f5a1e2241b5622c8845f8274635.",
		"Universal Dependencies French GSD r2.18 annotations."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
