// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:ar-core",
	"name": "Arabic Core Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-ar-core",
	"targets": {
		"languages": [
			"ar"
		],
		"scripts": [
			"Arab"
		],
		"regions": [
			"EG"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "ar-core-language-profile",
			"kind": "locale-profile",
			"path": "resources/ar.core.language-profile.json",
			"format": "json",
			"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05.",
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textfacts.locale-profile.v1"
		},
		{
			"id": "ar-core-orthography",
			"kind": "locale-profile",
			"path": "resources/ar.core.orthography.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			],
			"schemaId": "textfacts.locale-profile.v1"
		},
		{
			"id": "ar-core-punctuation",
			"kind": "locale-profile",
			"path": "resources/ar.core.punctuation.tsv",
			"format": "tsv",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0."
			],
			"schemaId": "textfacts.locale-profile.v1"
		},
		{
			"id": "ar-core-basic-segmentation",
			"kind": "segmentation-profile",
			"path": "resources/ar.core.basic-segmentation.json",
			"format": "json",
			"license": "Unicode-3.0",
			"citations": [
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textdata.segmentation-profile.v1"
		},
		{
			"id": "ar-core-quality",
			"kind": "quality-profile",
			"path": "resources/ar.core.quality.json",
			"format": "json",
			"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05.",
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textquality.evidence.v1"
		},
		{
			"id": "ar-core-quality-profile",
			"kind": "quality-profile",
			"path": "resources/ar.core.quality-profile.json",
			"format": "json",
			"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry",
			"citations": [
				"IANA Language Subtag Registry, File-Date 2026-05-05.",
				"Unicode Character Database 17.0.0.",
				"Unicode CLDR core data, cldr-core npm package 48.2.0."
			],
			"schemaId": "textquality.profile.v1"
		}
	],
	"capabilitySlots": [
		{
			"slot": "core",
			"status": "task-supported",
			"resourceIds": [
				"ar-core-language-profile",
				"ar-core-orthography",
				"ar-core-punctuation",
				"ar-core-basic-segmentation"
			],
			"bindings": [
				{
					"role": "profile",
					"resourceId": "ar-core-basic-segmentation",
					"schemaId": "textdata.segmentation-profile.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textdata"
				}
			],
			"readerRequired": true,
			"notes": [
				"Core profile resources cover modern typed Arabic identity, Arabic-script orthography, Unicode punctuation, and a basic UAX #29 segmentation baseline."
			],
			"capabilities": {
				"segmentation": "profile",
				"normalization": "unicode"
			}
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"ar-core-quality",
				"ar-core-quality-profile"
			],
			"bindings": [
				{
					"role": "evidence",
					"resourceId": "ar-core-quality",
					"schemaId": "textquality.evidence.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textquality"
				},
				{
					"role": "quality",
					"resourceId": "ar-core-quality-profile",
					"schemaId": "textquality.profile.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textquality"
				}
			],
			"readerRequired": true,
			"notes": [
				"Generated quality profile records source coverage, accepted records, rejected records, and scope limitations."
			]
		}
	],
	"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry",
	"citations": [
		"IANA Language Subtag Registry, File-Date 2026-05-05.",
		"Unicode Character Database 17.0.0.",
		"Unicode CLDR core data, cldr-core npm package 48.2.0."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
