// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:ar-msa-morphology",
	"name": "Arabic MSA CAMeL Morphology Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-ar-msa-morphology",
	"targets": {
		"languages": [
			"ar"
		],
		"scripts": [
			"Arab"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "ar-msa-camel-morph-features",
			"kind": "morphology",
			"path": "resources/camel-morph-msa.features.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-msa-camel-morph-defaults",
			"kind": "morphology",
			"path": "resources/camel-morph-msa.defaults.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-msa-camel-morph-tokenizations",
			"kind": "segmentation-profile",
			"path": "resources/camel-morph-msa.tokenizations.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-msa-camel-morph-morphemes",
			"kind": "morphology",
			"path": "resources/camel-morph-msa.morphemes.tsv.gz.b64",
			"format": "tsv+gzip+base64",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-msa-camel-morph-compatibility",
			"kind": "morphology",
			"path": "resources/camel-morph-msa.compatibility.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-msa-camel-morph-quality",
			"kind": "quality-profile",
			"path": "resources/camel-morph-msa.quality.json",
			"format": "json",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-msa-camel-morphology-canonical",
			"kind": "morphology",
			"path": "resources/camel-morph-msa.morphology.json",
			"format": "json",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			],
			"metadata": {
				"canonicalSchema": "textpack-morphology-resource.schema.json"
			}
		},
		{
			"id": "ar-msa-camel-segmentation-canonical",
			"kind": "segmentation-profile",
			"path": "resources/camel-morph-msa.segmentation.json",
			"format": "json",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			],
			"metadata": {
				"canonicalSchema": "textpack-segmentation-resource.schema.json"
			}
		},
		{
			"id": "ar-msa-camel-quality-profile",
			"kind": "quality-profile",
			"path": "resources/camel-morph-msa.quality-profile.json",
			"format": "json",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			],
			"metadata": {
				"canonicalSchema": "textpack-quality-profile-resource.schema.json"
			}
		}
	],
	"capabilitySlots": [
		{
			"slot": "morphology",
			"status": "task-supported",
			"resourceIds": [
				"ar-msa-camel-morph-features",
				"ar-msa-camel-morph-defaults",
				"ar-msa-camel-morph-morphemes",
				"ar-msa-camel-morph-compatibility",
				"ar-msa-camel-morphology-canonical"
			],
			"capabilities": {
				"morphology": "lookup"
			},
			"notes": [
				"CAMeL Morph MSA morpheme inventory, feature inventory, defaults, and compatibility tables are available as generated lookup resources."
			]
		},
		{
			"slot": "segmentation",
			"status": "task-supported",
			"resourceIds": [
				"ar-msa-camel-morph-tokenizations",
				"ar-msa-camel-segmentation-canonical"
			],
			"capabilities": {
				"segmentation": "dictionary"
			},
			"notes": [
				"CAMeL Morph tokenization schemes are available for Arabic MSA segmentation consumers."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"ar-msa-camel-morph-quality",
				"ar-msa-camel-quality-profile"
			],
			"notes": [
				"Generated quality profile records source counts, accepted records, and transform warnings."
			]
		}
	],
	"license": "CC-BY-4.0",
	"citations": [
		"CAMeL Morph MSA LREC-COLING 2024 release."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
