// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:ar-msa-morphology",
	"name": "Arabic MSA CAMeL Morphology Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-ar-msa-morphology",
	"targets": {
		"languages": [
			"ar"
		],
		"scripts": [
			"Arab"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "ar-msa-camel-morph-features",
			"kind": "morphology",
			"path": "resources/camel-morph-msa.features.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-msa-camel-morph-defaults",
			"kind": "morphology",
			"path": "resources/camel-morph-msa.defaults.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-msa-camel-morph-tokenizations",
			"kind": "segmentation-profile",
			"path": "resources/camel-morph-msa.tokenizations.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-msa-camel-morph-morphemes",
			"kind": "morphology",
			"path": "resources/camel-morph-msa.morphemes.tsv.gz.b64",
			"format": "tsv+gzip+base64",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-msa-camel-morph-compatibility",
			"kind": "morphology",
			"path": "resources/camel-morph-msa.compatibility.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-msa-camel-morph-quality",
			"kind": "quality-profile",
			"path": "resources/camel-morph-msa.quality.json",
			"format": "json",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		}
	],
	"capabilitySlots": [
		{
			"slot": "morphology",
			"status": "task-supported",
			"resourceIds": [
				"ar-msa-camel-morph-features",
				"ar-msa-camel-morph-defaults",
				"ar-msa-camel-morph-morphemes",
				"ar-msa-camel-morph-compatibility"
			],
			"capabilities": {
				"morphology": "lookup"
			},
			"notes": [
				"CAMeL Morph MSA morpheme inventory, feature inventory, defaults, and compatibility tables are available as generated lookup resources."
			]
		},
		{
			"slot": "segmentation",
			"status": "task-supported",
			"resourceIds": [
				"ar-msa-camel-morph-tokenizations"
			],
			"capabilities": {
				"segmentation": "dictionary"
			},
			"notes": [
				"CAMeL Morph tokenization schemes are available for Arabic MSA segmentation consumers."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"ar-msa-camel-morph-quality"
			],
			"notes": [
				"Generated quality profile records source counts, accepted records, and transform warnings."
			]
		}
	],
	"license": "CC-BY-4.0",
	"citations": [
		"CAMeL Morph MSA LREC-COLING 2024 release."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:12e98edb0c3ebf9a839773b624b51a935a7dc8d57894c7dd29bc64944572dd19",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
