// Generated by tools/textpack-forge. Do not edit.

import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import type { PackResourceMap } from "@ismail-elkorchi/textpack";

const resourceRoot = new URL("../resources/", import.meta.url);

async function readResource(
	resourcePath: string,
	encoding: "gzip-base64" | "utf8",
): Promise<string> {
	const text = await readFile(new URL(resourcePath, resourceRoot), "utf8");
	if (encoding === "utf8") return text;
	return gunzipSync(Buffer.from(text.trim(), "base64")).toString("utf8");
}

export async function resources(): Promise<PackResourceMap> {
	// biome-ignore format: generated resource map preserves deterministic resource ordering.
	return {
		"ar-msa-camel-morph-features": await readResource(
			"camel-morph-msa.features.tsv",
			"utf8",
		),
		"ar-msa-camel-morph-defaults": await readResource(
			"camel-morph-msa.defaults.tsv",
			"utf8",
		),
		"ar-msa-camel-morph-tokenizations": await readResource(
			"camel-morph-msa.tokenizations.tsv",
			"utf8",
		),
		"ar-msa-camel-morph-morphemes": await readResource(
			"camel-morph-msa.morphemes.tsv.gz.b64",
			"gzip-base64",
		),
		"ar-msa-camel-morph-compatibility": await readResource(
			"camel-morph-msa.compatibility.tsv",
			"utf8",
		),
		"ar-msa-camel-morph-quality": await readResource(
			"camel-morph-msa.quality.json",
			"utf8",
		),
		"ar-msa-camel-morphology-canonical": await readResource(
			"camel-morph-msa.morphology.json",
			"utf8",
		),
		"ar-msa-camel-segmentation-canonical": await readResource(
			"camel-morph-msa.segmentation.json",
			"utf8",
		),
		"ar-msa-camel-quality-profile": await readResource(
			"camel-morph-msa.quality-profile.json",
			"utf8",
		),
	};
}
