// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:ar-search",
	"name": "Arabic MSA Search Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-ar-search",
	"targets": {
		"languages": [
			"ar"
		],
		"scripts": [
			"Arab"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "ar-search-normalization-policy",
			"kind": "normalization-profile",
			"path": "resources/ar.search.normalization-policy.json",
			"format": "json",
			"license": "Unicode-3.0 AND CC-BY-4.0",
			"citations": [
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-search-tokenization-hooks",
			"kind": "segmentation-profile",
			"path": "resources/ar.search.tokenization-hooks.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-search-morphology-hooks",
			"kind": "morphology",
			"path": "resources/ar.search.morphology-hooks.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"CAMeL Morph MSA LREC-COLING 2024 release."
			]
		},
		{
			"id": "ar-search-wordnet-synonyms",
			"kind": "lexicon",
			"path": "resources/ar.search.wordnet-synonyms.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"Arabic WordNet 4.1.0."
			]
		},
		{
			"id": "ar-search-profile",
			"kind": "search-profile",
			"path": "resources/ar.search.profile.json",
			"format": "json",
			"license": "Unicode-3.0 AND CC-BY-4.0",
			"citations": [
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"CAMeL Morph MSA LREC-COLING 2024 release.",
				"Arabic WordNet 4.1.0."
			],
			"metadata": {
				"canonicalSchema": "textpack-search-analyzer-resource.schema.json"
			}
		},
		{
			"id": "ar-search-quality",
			"kind": "quality-profile",
			"path": "resources/ar.search.quality.json",
			"format": "json",
			"license": "Unicode-3.0 AND CC-BY-4.0",
			"citations": [
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"CAMeL Morph MSA LREC-COLING 2024 release.",
				"Arabic WordNet 4.1.0."
			]
		},
		{
			"id": "ar-search-quality-profile",
			"kind": "quality-profile",
			"path": "resources/ar.search.quality-profile.json",
			"format": "json",
			"license": "Unicode-3.0 AND CC-BY-4.0",
			"citations": [
				"Unicode CLDR core data, cldr-core npm package 48.2.0.",
				"CAMeL Morph MSA LREC-COLING 2024 release.",
				"Arabic WordNet 4.1.0."
			],
			"metadata": {
				"canonicalSchema": "textpack-quality-profile-resource.schema.json"
			}
		}
	],
	"capabilitySlots": [
		{
			"slot": "search",
			"status": "task-supported",
			"resourceIds": [
				"ar-search-normalization-policy",
				"ar-search-tokenization-hooks",
				"ar-search-morphology-hooks",
				"ar-search-wordnet-synonyms",
				"ar-search-profile"
			],
			"capabilities": {
				"search": "analyzer"
			},
			"notes": [
				"Arabic MSA lookup/search analyzer resources are generated from CLDR context, CAMeL Morph MSA tokenization and morphology hooks, and Arabic WordNet synonym hooks."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"ar-search-quality",
				"ar-search-quality-profile"
			],
			"notes": [
				"Generated quality profile records source coverage, synonym and morphology hook counts, accepted records, rejected records, and scope limitations."
			]
		}
	],
	"license": "Unicode-3.0 AND CC-BY-4.0",
	"citations": [
		"Unicode CLDR core data, cldr-core npm package 48.2.0.",
		"CAMeL Morph MSA LREC-COLING 2024 release.",
		"Arabic WordNet 4.1.0."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
