// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"ar-search-normalization-policy": {"byteLength":329,"checksum":"sha256:4a8da095f0b9859473291b4089d05e3b1257517b2ea20e78e9cf0bfcc56bbdba","encoding":"utf8","kind":"file-backed-resource","lineCount":15,"nonEmptyLineCount":14,"path":"resources/ar.search.normalization-policy.json","resourceTextByteLength":329},
	"ar-search-tokenization-hooks": {"byteLength":86,"checksum":"sha256:4d9213255e9a95e68267cced8d89e2adcfda0cab020edd32d4e9669d17dd1203","encoding":"utf8","kind":"file-backed-resource","lineCount":11,"nonEmptyLineCount":10,"path":"resources/ar.search.tokenization-hooks.tsv","resourceTextByteLength":86},
	"ar-search-morphology-hooks": {"byteLength":125,"checksum":"sha256:583391d3c16a1936ccc934339859a8c5b0047b51156ff9361c5908c8c0bca0c0","encoding":"utf8","kind":"file-backed-resource","lineCount":10,"nonEmptyLineCount":9,"path":"resources/ar.search.morphology-hooks.tsv","resourceTextByteLength":125},
	"ar-search-wordnet-synonyms": {"byteLength":12056116,"checksum":"sha256:12e5f5617e8b557e8b9de5f465021f2f8ddeae606b623ee020a683a76d4f5a41","encoding":"utf8","kind":"file-backed-resource","lineCount":139454,"nonEmptyLineCount":139453,"path":"resources/ar.search.wordnet-synonyms.tsv","resourceTextByteLength":12056116},
	"ar-search-profile": {"byteLength":2269,"checksum":"sha256:253d5ef2b16b4b9d59f5af72e9b2eb21dbf2589a8527eaa7df6c2cbcd376f394","encoding":"utf8","kind":"file-backed-resource","lineCount":98,"nonEmptyLineCount":97,"path":"resources/ar.search.profile.json","resourceTextByteLength":2269},
	"ar-search-quality": {"byteLength":860,"checksum":"sha256:688500196554d7e489f5c06c27f3c0f5fd7b0f5b8ee5c0a0c91e4f873863b10d","encoding":"utf8","kind":"file-backed-resource","lineCount":26,"nonEmptyLineCount":25,"path":"resources/ar.search.quality.json","resourceTextByteLength":860},
	"ar-search-quality-profile": {"byteLength":1095,"checksum":"sha256:d451d67d2eb26bb4f77ab3f3fa06a392e1e5ba1575a28d8d4d1275bb6a3d1c67","encoding":"utf8","kind":"file-backed-resource","lineCount":46,"nonEmptyLineCount":45,"path":"resources/ar.search.quality-profile.json","resourceTextByteLength":1095},
} as const;
