// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:en-syntax-ud-gumreddit",
	"name": "English UD GUMReddit Syntax Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-en-syntax-ud-gumreddit",
	"targets": {
		"languages": [
			"en"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed",
			"social"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "en-ud-gumreddit-upos",
			"kind": "grammar",
			"path": "resources/ud-gumreddit.upos.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			]
		},
		{
			"id": "en-ud-gumreddit-features",
			"kind": "morphology",
			"path": "resources/ud-gumreddit.features.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			]
		},
		{
			"id": "en-ud-gumreddit-dependencies",
			"kind": "grammar",
			"path": "resources/ud-gumreddit.dependencies.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			]
		},
		{
			"id": "en-ud-gumreddit-sentence-profile",
			"kind": "statistical-model",
			"path": "resources/ud-gumreddit.sentence-profile.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			]
		},
		{
			"id": "en-ud-gumreddit-annotations",
			"kind": "dataset",
			"path": "resources/ud-gumreddit.annotations.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			]
		},
		{
			"id": "en-ud-gumreddit-quality",
			"kind": "quality-profile",
			"path": "resources/ud-gumreddit.quality.json",
			"format": "json",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			]
		}
	],
	"capabilitySlots": [
		{
			"slot": "tagging",
			"status": "task-supported",
			"resourceIds": [
				"en-ud-gumreddit-upos",
				"en-ud-gumreddit-features",
				"en-ud-gumreddit-annotations"
			],
			"capabilities": {
				"tagging": "statistical",
				"morphology": "statistical"
			},
			"notes": [
				"Annotation-derived UPOS, XPOS, and morphological feature profiles are available without redistributing Reddit text."
			]
		},
		{
			"slot": "syntax",
			"status": "task-supported",
			"resourceIds": [
				"en-ud-gumreddit-dependencies",
				"en-ud-gumreddit-sentence-profile",
				"en-ud-gumreddit-annotations"
			],
			"capabilities": {
				"parsing": "statistical"
			},
			"notes": [
				"Annotation-derived dependency and sentence profiles are available without redistributing Reddit text."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"en-ud-gumreddit-quality"
			],
			"notes": [
				"Generated quality profile records annotation counts and confirms no raw text fields are emitted."
			]
		}
	],
	"license": "CC-BY-4.0",
	"citations": [
		"Universal Dependencies English GUMReddit r2.18 annotations."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:12e98edb0c3ebf9a839773b624b51a935a7dc8d57894c7dd29bc64944572dd19",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
