// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:en-syntax-ud-gumreddit",
	"name": "English UD GUMReddit Syntax Pack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-en-syntax-ud-gumreddit",
	"targets": {
		"languages": [
			"en"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed",
			"social"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [
		{
			"id": "en-ud-gumreddit-upos",
			"kind": "grammar",
			"path": "resources/ud-gumreddit.upos.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			],
			"schemaId": "textdata.syntax-table.v1"
		},
		{
			"id": "en-ud-gumreddit-features",
			"kind": "morphology",
			"path": "resources/ud-gumreddit.features.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			],
			"schemaId": "textlex.morphology.rows.v1"
		},
		{
			"id": "en-ud-gumreddit-dependencies",
			"kind": "grammar",
			"path": "resources/ud-gumreddit.dependencies.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			],
			"schemaId": "textdata.syntax-table.v1"
		},
		{
			"id": "en-ud-gumreddit-sentence-profile",
			"kind": "statistical-model",
			"path": "resources/ud-gumreddit.sentence-profile.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			],
			"schemaId": "textdata.syntax-profile.v1"
		},
		{
			"id": "en-ud-gumreddit-annotations",
			"kind": "dataset",
			"path": "resources/ud-gumreddit.annotations.tsv",
			"format": "tsv",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			],
			"schemaId": "textdata.dataset.v1"
		},
		{
			"id": "en-ud-gumreddit-quality",
			"kind": "quality-profile",
			"path": "resources/ud-gumreddit.quality.json",
			"format": "json",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			],
			"schemaId": "textquality.evidence.v1"
		},
		{
			"id": "en-ud-gumreddit-syntax-canonical",
			"kind": "grammar",
			"path": "resources/ud-gumreddit.syntax.json",
			"format": "json",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			],
			"schemaId": "textdata.syntax.v1"
		},
		{
			"id": "en-ud-gumreddit-morphology-canonical",
			"kind": "morphology",
			"path": "resources/ud-gumreddit.morphology.json",
			"format": "json",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			],
			"schemaId": "textlex.morphology.v1"
		},
		{
			"id": "en-ud-gumreddit-quality-profile",
			"kind": "quality-profile",
			"path": "resources/ud-gumreddit.quality-profile.json",
			"format": "json",
			"license": "CC-BY-4.0",
			"citations": [
				"Universal Dependencies English GUMReddit r2.18 annotations."
			],
			"schemaId": "textquality.profile.v1"
		}
	],
	"capabilitySlots": [
		{
			"slot": "tagging",
			"status": "task-supported",
			"resourceIds": [
				"en-ud-gumreddit-upos",
				"en-ud-gumreddit-features",
				"en-ud-gumreddit-annotations",
				"en-ud-gumreddit-morphology-canonical"
			],
			"bindings": [
				{
					"role": "table",
					"resourceId": "en-ud-gumreddit-annotations",
					"schemaId": "textdata.dataset.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textdata"
				},
				{
					"role": "table",
					"resourceId": "en-ud-gumreddit-upos",
					"schemaId": "textdata.syntax-table.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textdata"
				},
				{
					"role": "primary",
					"resourceId": "en-ud-gumreddit-morphology-canonical",
					"schemaId": "textlex.morphology.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textlex"
				},
				{
					"role": "table",
					"resourceId": "en-ud-gumreddit-features",
					"schemaId": "textlex.morphology.rows.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textlex"
				}
			],
			"readerRequired": true,
			"notes": [
				"Annotation-derived UPOS, XPOS, and morphological feature profiles are available without redistributing Reddit text."
			],
			"capabilities": {
				"tagging": "statistical",
				"morphology": "statistical"
			}
		},
		{
			"slot": "syntax",
			"status": "task-supported",
			"resourceIds": [
				"en-ud-gumreddit-dependencies",
				"en-ud-gumreddit-sentence-profile",
				"en-ud-gumreddit-annotations",
				"en-ud-gumreddit-syntax-canonical"
			],
			"bindings": [
				{
					"role": "primary",
					"resourceId": "en-ud-gumreddit-syntax-canonical",
					"schemaId": "textdata.syntax.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textdata"
				},
				{
					"role": "table",
					"resourceId": "en-ud-gumreddit-annotations",
					"schemaId": "textdata.dataset.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textdata"
				},
				{
					"role": "table",
					"resourceId": "en-ud-gumreddit-dependencies",
					"schemaId": "textdata.syntax-table.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textdata"
				},
				{
					"role": "table",
					"resourceId": "en-ud-gumreddit-sentence-profile",
					"schemaId": "textdata.syntax-profile.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textdata"
				}
			],
			"readerRequired": true,
			"notes": [
				"Annotation-derived dependency and sentence profiles are available without redistributing Reddit text."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"resourceIds": [
				"en-ud-gumreddit-quality",
				"en-ud-gumreddit-quality-profile"
			],
			"bindings": [
				{
					"role": "evidence",
					"resourceId": "en-ud-gumreddit-quality",
					"schemaId": "textquality.evidence.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textquality"
				},
				{
					"role": "quality",
					"resourceId": "en-ud-gumreddit-quality-profile",
					"schemaId": "textquality.profile.v1",
					"required": true,
					"ownerPackage": "@ismail-elkorchi/textquality"
				}
			],
			"readerRequired": true,
			"notes": [
				"Generated quality profile records annotation counts and confirms no raw text fields are emitted."
			]
		}
	],
	"license": "CC-BY-4.0",
	"citations": [
		"Universal Dependencies English GUMReddit r2.18 annotations."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
