// Generated by tools/textpack-forge. Do not edit.

import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import type { PackResourceMap } from "@ismail-elkorchi/textpack";

const resourceRoot = new URL("../resources/", import.meta.url);

async function readResource(
	resourcePath: string,
	encoding: "gzip-base64" | "utf8",
): Promise<string> {
	const text = await readFile(new URL(resourcePath, resourceRoot), "utf8");
	if (encoding === "utf8") return text;
	return gunzipSync(Buffer.from(text.trim(), "base64")).toString("utf8");
}

export async function resources(): Promise<PackResourceMap> {
	// biome-ignore format: generated resource map preserves deterministic resource ordering.
	return {
		"en-ud-gumreddit-upos": await readResource(
			"ud-gumreddit.upos.tsv",
			"utf8",
		),
		"en-ud-gumreddit-features": await readResource(
			"ud-gumreddit.features.tsv",
			"utf8",
		),
		"en-ud-gumreddit-dependencies": await readResource(
			"ud-gumreddit.dependencies.tsv",
			"utf8",
		),
		"en-ud-gumreddit-sentence-profile": await readResource(
			"ud-gumreddit.sentence-profile.tsv",
			"utf8",
		),
		"en-ud-gumreddit-annotations": await readResource(
			"ud-gumreddit.annotations.tsv",
			"utf8",
		),
		"en-ud-gumreddit-quality": await readResource(
			"ud-gumreddit.quality.json",
			"utf8",
		),
		"en-ud-gumreddit-syntax-canonical": await readResource(
			"ud-gumreddit.syntax.json",
			"utf8",
		),
		"en-ud-gumreddit-morphology-canonical": await readResource(
			"ud-gumreddit.morphology.json",
			"utf8",
		),
		"en-ud-gumreddit-quality-profile": await readResource(
			"ud-gumreddit.quality-profile.json",
			"utf8",
		),
	};
}
