// Generated by tools/textpack-forge. Do not edit.

import type { PackResourceMap } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated resource map preserves deterministic payload ordering.
export const resources: PackResourceMap = {
	"en-ud-gumreddit-upos": {"byteLength":789,"checksum":"sha256:d912a7810541f1063a5db1a5a6e654981c8a4ddb71dde80f0ff1453e201ff199","encoding":"utf8","kind":"file-backed-resource","lineCount":70,"nonEmptyLineCount":69,"path":"resources/ud-gumreddit.upos.tsv","resourceTextByteLength":789},
	"en-ud-gumreddit-features": {"byteLength":852,"checksum":"sha256:d76d1aae120352ab5cb75f5e5ef64853a4dbbdd0567b646b237986322202d53b","encoding":"utf8","kind":"file-backed-resource","lineCount":57,"nonEmptyLineCount":56,"path":"resources/ud-gumreddit.features.tsv","resourceTextByteLength":852},
	"en-ud-gumreddit-dependencies": {"byteLength":2081,"checksum":"sha256:0b3114df9d760fdd1fca89176c3a09969776c32c6c11b2210d7e121bb08e0fc3","encoding":"utf8","kind":"file-backed-resource","lineCount":136,"nonEmptyLineCount":135,"path":"resources/ud-gumreddit.dependencies.tsv","resourceTextByteLength":2081},
	"en-ud-gumreddit-sentence-profile": {"byteLength":133,"checksum":"sha256:5aedb284f73960c0dd7ab49e434d068dd2b372ad2818bc46471757476bc5b7c0","encoding":"utf8","kind":"file-backed-resource","lineCount":5,"nonEmptyLineCount":4,"path":"resources/ud-gumreddit.sentence-profile.tsv","resourceTextByteLength":133},
	"en-ud-gumreddit-annotations": {"byteLength":1678076,"checksum":"sha256:490dfb61690af9f9d2c14a0b78576935518e36957d1be650916ef187dca7740f","encoding":"utf8","kind":"file-backed-resource","lineCount":16366,"nonEmptyLineCount":16365,"path":"resources/ud-gumreddit.annotations.tsv","resourceTextByteLength":1678076},
	"en-ud-gumreddit-quality": {"byteLength":961,"checksum":"sha256:014fe6479a0e7303dc2490c225a20ee8105f862d1e028e1cb0bb5a8b189201d2","encoding":"utf8","kind":"file-backed-resource","lineCount":39,"nonEmptyLineCount":38,"path":"resources/ud-gumreddit.quality.json","resourceTextByteLength":961},
	"en-ud-gumreddit-syntax-canonical": {"byteLength":23466,"checksum":"sha256:6344de276f9b76a4b323a6645d32816e7ac44304828c62358b206ba90905328d","encoding":"utf8","kind":"file-backed-resource","lineCount":1358,"nonEmptyLineCount":1357,"path":"resources/ud-gumreddit.syntax.json","resourceTextByteLength":23466},
	"en-ud-gumreddit-morphology-canonical": {"byteLength":3245,"checksum":"sha256:9709b9573be9dea59fe920e3fbe5ce0af4fb0debe05a5392b740005761cf9e5b","encoding":"utf8","kind":"file-backed-resource","lineCount":211,"nonEmptyLineCount":210,"path":"resources/ud-gumreddit.morphology.json","resourceTextByteLength":3245},
	"en-ud-gumreddit-quality-profile": {"byteLength":932,"checksum":"sha256:f1b6220500c62dd212053da7181597af2a76d6091dad5bbb17093e875e0f5034","encoding":"utf8","kind":"file-backed-resource","lineCount":41,"nonEmptyLineCount":40,"path":"resources/ud-gumreddit.quality-profile.json","resourceTextByteLength":932},
} as const;
