// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:fr-morphology-sa",
	"name": "French Morphology Share-Alike Composite Textpack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-fr-morphology-sa",
	"targets": {
		"languages": [
			"fr"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [],
	"components": [
		{
			"packageName": "@ismail-elkorchi/textpack-fr-lexique-sa",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Share-alike isolated Lexique 3.83 POS inventory and canonical morphology resources.",
			"licensePolicy": "allow-share-alike",
			"capabilityPolicy": "available-optional",
			"artifactPolicy": "none"
		},
		{
			"packageName": "@ismail-elkorchi/textpack-fr-unimorph-sa",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Share-alike isolated UniMorph French paradigm rows and lookup analyzer/generator resources.",
			"licensePolicy": "allow-share-alike",
			"capabilityPolicy": "available-optional",
			"artifactPolicy": "none"
		}
	],
	"capabilitySlots": [
		{
			"slot": "morphology",
			"status": "task-supported",
			"notes": [
				"The required component graph provides Lexique 3.83 lemma/form metadata and POS inventory plus UniMorph French paradigm rows, feature bundles, lookup analyzer rows, and lookup generator rows under the share-alike policy surface."
			]
		},
		{
			"slot": "quality",
			"status": "task-supported",
			"notes": [
				"Generated component reports and evaluation records are available for the required share-alike morphology component."
			]
		}
	],
	"license": "CC-BY-SA-4.0 AND CC-BY-SA-3.0",
	"citations": [
		"Lexique 3.83, 2019-06-04.",
		"UniMorph French repository, commit f672f8cceb2d5f5a1e2241b5622c8845f8274635."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:47e22f7d7e35324945ccf546ccb43d204cd6941b133a20a6988898b7e3280d64",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
