// Generated by tools/textpack-forge. Do not edit.

import type { TextPackManifest } from "@ismail-elkorchi/textpack";

// biome-ignore format: generated manifest preserves the canonical JSON projection.
export const manifest: TextPackManifest = {
	"schemaVersion": "1",
	"id": "pack:fr-quality",
	"name": "French Quality Policy-Expanded Wrapper Textpack",
	"version": "0.1.0",
	"packageName": "@ismail-elkorchi/textpack-fr-quality",
	"targets": {
		"languages": [
			"fr"
		],
		"scripts": [
			"Latn"
		],
		"modalities": [
			"typed"
		]
	},
	"engines": {
		"@ismail-elkorchi/textpack": "^0.1.0"
	},
	"resources": [],
	"components": [
		{
			"packageName": "@ismail-elkorchi/textpack-fr-quality-sa",
			"versionRange": "0.1.0",
			"role": "required",
			"reason": "Share-alike isolated French quality component graph with full generated evaluation evidence.",
			"licensePolicy": "allow-share-alike",
			"capabilityPolicy": "contributes-default",
			"artifactPolicy": "fetch-explicit"
		}
	],
	"capabilitySlots": [
		{
			"slot": "quality",
			"status": "task-supported",
			"notes": [
				"The required component graph provides French quality-profile resources, generated quality reports, coverage reports, and evaluation records through an explicit share-alike policy wrapper."
			]
		}
	],
	"license": "Unicode-3.0 AND LicenseRef-IANA-Language-Subtag-Registry AND CC0-1.0 AND CC-BY-2.0-FR AND CC-BY-SA-4.0 AND CC-BY-SA-3.0",
	"citations": [
		"IANA Language Subtag Registry, File-Date 2026-05-05.",
		"Unicode Character Database 17.0.0.",
		"Unicode CLDR core data, cldr-core npm package 48.2.0.",
		"Wikidata main structured data dump, 2026-06-08.",
		"Tatoeba weekly French exports, 2026-06-06.",
		"Lexique 3.83, 2019-06-04.",
		"UniMorph French repository, commit f672f8cceb2d5f5a1e2241b5622c8845f8274635.",
		"Universal Dependencies French GSD r2.18 annotations."
	],
	"generated": {
		"forgeVersion": "0.1.0",
		"lockfileChecksum": "sha256:bfb26766d581816c40cb7a51c8de8a8ee3b5d902bfec74d803466a791a1e72c8",
		"generatedAt": "2026-06-08T00:00:00.000Z",
		"generatorCommand": "node tools/textpack-forge/cli.mjs build"
	}
} as const;
