// Generated by tools/textpack-forge. Do not edit.

export { manifest } from "./manifest.js";
export { resources } from "./resources.js";

import {
	loadPack,
	type ResolveTextPackComponentsOptions,
	resolvePackComponents,
	type TextPackComponent,
} from "@ismail-elkorchi/textpack";
import { manifest } from "./manifest.js";
import { resources } from "./resources.js";

export interface LoadEnglishQualityOptions
	extends Omit<ResolveTextPackComponentsOptions, "resolveComponent"> {
	readonly resolveComponent?: ResolveTextPackComponentsOptions["resolveComponent"];
}

async function resolveGeneratedComponent(
	component: TextPackComponent,
	options: LoadEnglishQualityOptions,
): Promise<unknown> {
	void options;
	switch (component.packageName) {
		case "@ismail-elkorchi/textpack-en-core":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-en-normalization":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-en-segmentation":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-en-wordlist-esdb":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-en-inflection-scowl":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-en-syntax-ud-gumreddit":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-wordnet-en":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-wikidata-en":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-en-corpus":
			return import(component.packageName);
		case "@ismail-elkorchi/textpack-en-parallel":
			return import(component.packageName);
		default:
			throw new TypeError(
				`No generated resolver entry for ${component.packageName}.`,
			);
	}
}

export async function loadEnglishQuality(
	options: LoadEnglishQualityOptions = {},
) {
	return resolvePackComponents(await loadPack({ manifest, resources }), {
		...options,
		licensePolicy: options.licensePolicy ?? "allow-attribution",
		artifactPolicy: options.artifactPolicy ?? "none",
		conflictPolicy: options.conflictPolicy ?? "first",
		resolveComponent:
			options.resolveComponent ??
			((component) => resolveGeneratedComponent(component, options)),
	});
}

export default { manifest, resources, loadEnglishQuality };
